/*
 * 제조 실적 관리 > LotNo 변경 관리 > LotNo 변경 상세 조회
 */
const { ValueType } = require('realgrid');
const { rgDisplayDate, rgDisplayTime } = require('@/utils/dateUtils');

const grid = {
  options: {
    checkBar: { visible: false },
    copy: { enabled: true, singleMode: false },
    display: {
      columnMovable: false,
      emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'NONE',
      hscrollBar: true,
      showEmptyMessage: true,
    },
    edit: { editable: false },
    footers: { visible: false },
    paste: { enabled: false },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
  },

  fields: [
		{ fieldName: '변경일자', dataType: ValueType.TEXT },
		{ fieldName: '변경시각', dataType: ValueType.TEXT },
		{ fieldName: '작업완료공정', dataType: ValueType.TEXT },
		{ fieldName: '작업대기공정', dataType: ValueType.TEXT },
		{ fieldName: '구lotNo', dataType: ValueType.TEXT },
		{ fieldName: '신lotNo', dataType: ValueType.TEXT },
		{ fieldName: 'fromcell', dataType: ValueType.TEXT },
		{ fieldName: 'tocell', dataType: ValueType.TEXT },
		{ fieldName: '담당자', dataType: ValueType.TEXT },
		{ fieldName: '변환사유', dataType: ValueType.TEXT },
		{ fieldName: 'lot변경가능여부', dataType: ValueType.TEXT },
		{ fieldName: '구lot원장재질', dataType: ValueType.TEXT },
		{ fieldName: '신lot원장재질', dataType: ValueType.TEXT },
		{ fieldName: '변경내용', dataType: ValueType.TEXT },
		{ fieldName: '구lot모델', dataType: ValueType.TEXT },
		{ fieldName: '신lot모델', dataType: ValueType.TEXT },
		{ fieldName: '구lot작업구분', dataType: ValueType.TEXT },
		{ fieldName: '신lot작업구분', dataType: ValueType.TEXT },
		{ fieldName: '구lot생성월', dataType: ValueType.TEXT },
		{ fieldName: '신lot생성월', dataType: ValueType.TEXT },
		{ fieldName: '구lotpono', dataType: ValueType.TEXT },
		{ fieldName: '신lotpono', dataType: ValueType.TEXT },
		{ fieldName: '구lotMin공정코드', dataType: ValueType.TEXT },
		{ fieldName: '구lotMax공정코드', dataType: ValueType.TEXT },
		{ fieldName: '신lotMin공정코드', dataType: ValueType.TEXT },
		{ fieldName: '신lotMax공정코드', dataType: ValueType.TEXT },
		{ fieldName: '처리여부', dataType: ValueType.TEXT },
  ],

  columns: [
		{ name: '변경일자', fieldName: '변경일자', width: '120', header: { text: '변경일자' }, autoFilter: true, styleName: 'tl'},
		{ name: '변경시각', fieldName: '변경시각', width: '120', header: { text: '변경시각' }, autoFilter: true, styleName: 'tl'},
		{ name: '작업완료공정', fieldName: '작업완료공정', width: '180', header: { text: '작업완료공정' }, autoFilter: true, styleName: 'tl'},
		{ name: '작업대기공정', fieldName: '작업대기공정', width: '180', header: { text: '작업대기공정' }, autoFilter: true, styleName: 'tl'},
		{ name: '구lotNo', fieldName: '구lotNo', width: '90', header: { text: '구lot_no' }, autoFilter: true, styleName: 'tl'},
		{ name: '신lotNo', fieldName: '신lotNo', width: '90', header: { text: '신lot_no' }, autoFilter: true, styleName: 'tl'},
		{ name: 'fromcell', fieldName: 'fromcell', width: '80', header: { text: 'fromCell' }, autoFilter: true, styleName: 'tr'},
		{ name: 'tocell', fieldName: 'tocell', width: '80', header: { text: 'toCell' }, autoFilter: true, styleName: 'tr'},
		{ name: '담당자', fieldName: '담당자', width: '90', header: { text: '담당자' }, autoFilter: true, styleName: 'tl'},
		{ name: '변환사유', fieldName: '변환사유', width: '120', header: { text: '변환사유' }, autoFilter: true, styleName: 'tl'},
		{ name: 'lot변경가능여부', fieldName: 'lot변경가능여부', width: '210', header: { text: 'Lot변경가능여부' }, autoFilter: true, styleName: 'tl'},
		{ name: '구lot원장재질', fieldName: '구lot원장재질', width: '190', header: { text: '구lot_원장재질' }, autoFilter: true, styleName: 'tl'},
		{ name: '신lot원장재질', fieldName: '신lot원장재질', width: '190', header: { text: '신lot_원장재질' }, autoFilter: true, styleName: 'tl'},
		{ name: '변경내용', fieldName: '변경내용', width: '120', header: { text: '변경내용' }, autoFilter: true, styleName: 'tl'},
		{ name: '구lot모델', fieldName: '구lot모델', width: '120', header: { text: '구lot모델' }, autoFilter: true, styleName: 'tl'},
		{ name: '신lot모델', fieldName: '신lot모델', width: '120', header: { text: '신lot모델' }, autoFilter: true, styleName: 'tl'},
		{ name: '구lot작업구분', fieldName: '구lot작업구분', width: '190', header: { text: '구lot_작업구분' }, autoFilter: true, styleName: 'tl'},
		{ name: '신lot작업구분', fieldName: '신lot작업구분', width: '190', header: { text: '신lot_작업구분' }, autoFilter: true, styleName: 'tl'},
		{ name: '구lot생성월', fieldName: '구lot생성월', width: '160', header: { text: '구lot_생성월' }, autoFilter: true, styleName: 'tl'},
		{ name: '신lot생성월', fieldName: '신lot생성월', width: '160', header: { text: '신lot_생성월' }, autoFilter: true, styleName: 'tl'},
		{ name: '구lotpono', fieldName: '구lotpono', width: '100', header: { text: '구LotPoNo' }, autoFilter: true, styleName: 'tl'},
		{ name: '신lotpono', fieldName: '신lotpono', width: '100', header: { text: '신LotPoNo' }, autoFilter: true, styleName: 'tl'},
		{ name: '구lotMin공정코드', fieldName: '구lotMin공정코드', width: '230', header: { text: '구Lot_min_공정코드' }, autoFilter: true, styleName: 'tl'},
		{ name: '구lotMax공정코드', fieldName: '구lotMax공정코드', width: '230', header: { text: '구Lot_max_공정코드' }, autoFilter: true, styleName: 'tl'},
		{ name: '신lotMin공정코드', fieldName: '신lotMin공정코드', width: '230', header: { text: '신Lot_min_공정코드' }, autoFilter: true, styleName: 'tl'},
		{ name: '신lotMax공정코드', fieldName: '신lotMax공정코드', width: '230', header: { text: '신Lot_max_공정코드' }, autoFilter: true, styleName: 'tl'},
    {
      name: '처리여부',
      fieldName: '처리여부',
      width: '100',
      header: { text: '처리여부' },
      autoFilter: true,
      renderer: {
        type: 'check',
        trueValues: '1',
        falseValues: '0',
      },
    },
  ],
};

module.exports = grid;
