/*
* 기준정보 > 사용자-메뉴 권한 관리 - 메뉴
*/
const { ValueType } = require('realgrid');

const grid = {

	options: {
		checkBar: { visible: true, exclusive: false,syncHeadCheck:true },
		copy: { enabled: true, singleMode: false },
		//dataDrop: {},
		display: { columnMovable: false, editItemMerging: true, fitStyle: "even" },
		edit: { editable: true, commitByCell: true },
		//editor: {},
		//filtering: {},
		//filterMode: {},
		//filterPanel: {},
		//fixed: {},
		footer: { visible: false },
		//footers: {},
		//format: {},
		header: { height: 25 },
		//headerSummaries: {},
		//headerSummary: {},
		hideDeletedRows: true,
		paste: { enabled: true },
		rowIndicator: { visible: true },
		sorting: { enabled: false },
		//sortMode: {},
		stateBar: { visible: true },
		//summaryMode: {},
	},

	fields: [
		{ fieldName: 'seqId', dataType: ValueType.TEXT },
		{ fieldName: '구분', dataType: ValueType.TEXT },
		{ fieldName: '모델', dataType: ValueType.TEXT },
		{ fieldName: '제품코드', dataType: ValueType.TEXT },
		{ fieldName: 'revNo', dataType: ValueType.TEXT },
		{ fieldName: 'lotRevNo', dataType: ValueType.TEXT },
		{ fieldName: 'runRevNo', dataType: ValueType.TEXT },
		{ fieldName: '양산이관구분', dataType: ValueType.TEXT },
		{ fieldName: '양산이관Code', dataType: ValueType.TEXT },
		{ fieldName: '주요변경사항', dataType: ValueType.TEXT },
		{ fieldName: 'lotNo', dataType: ValueType.TEXT },
		{ fieldName: 'runNo', dataType: ValueType.TEXT },
		{ fieldName: '변경접수일', dataType: ValueType.TEXT },
		{ fieldName: '비고', dataType: ValueType.TEXT },
		{ fieldName: '고객사', dataType: ValueType.TEXT },
		{ fieldName: '고객사Model', dataType: ValueType.TEXT },
		{ fieldName: '고객사Code', dataType: ValueType.TEXT },
		{ fieldName: '고객사PartCodee', dataType: ValueType.TEXT },
		{ fieldName: 'glass정보제조사', dataType: ValueType.TEXT },
		{ fieldName: 'glass정보모델', dataType: ValueType.TEXT },
		{ fieldName: 'glass정보Size대각Inch', dataType: ValueType.TEXT },
		{ fieldName: 'glass정보SizeMm', dataType: ValueType.TEXT },
		{ fieldName: 'glass정보Size두께', dataType: ValueType.TEXT },
		{ fieldName: 'glass정보가공치수', dataType: ValueType.TEXT },
		{ fieldName: 'film정보전면원단사', dataType: ValueType.TEXT },
		{ fieldName: 'film정보전면원단', dataType: ValueType.TEXT },
		{ fieldName: 'film정보전면SizeMm', dataType: ValueType.TEXT },
		{ fieldName: 'film정보전면두께Mm', dataType: ValueType.TEXT },
		{ fieldName: 'film정보전면손잡이', dataType: ValueType.TEXT },
		{ fieldName: 'film정보전면타발사', dataType: ValueType.TEXT },
		{ fieldName: 'film정보전면Ver', dataType: ValueType.TEXT },
		{ fieldName: 'film정보배면원단사', dataType: ValueType.TEXT },
		{ fieldName: 'film정보배면원단', dataType: ValueType.TEXT },
		{ fieldName: 'film정보배면SizeMm', dataType: ValueType.TEXT },
		{ fieldName: 'film정보배면두께Mm', dataType: ValueType.TEXT },
		{ fieldName: 'film정보배면손잡이', dataType: ValueType.TEXT },
		{ fieldName: 'film정보배면타발사', dataType: ValueType.TEXT },
		{ fieldName: 'film정보배면Ver', dataType: ValueType.TEXT },
		{ fieldName: 'tray제조사', dataType: ValueType.TEXT },
		{ fieldName: 'trayModel', dataType: ValueType.TEXT },
		{ fieldName: 'tray원단', dataType: ValueType.TEXT },
		{ fieldName: 'tray적재수량형태', dataType: ValueType.TEXT },
		{ fieldName: 'tray원단두께Mm', dataType: ValueType.TEXT },
		{ fieldName: 'tray적재단수', dataType: ValueType.TEXT },
		{ fieldName: 'trayVer', dataType: ValueType.TEXT },
		{ fieldName: '특이사항', dataType: ValueType.TEXT },
	],

	columns: [
		{ name: '구분', fieldName: '구분', width: '80', header: { text: '구분' }, autoFilter:true},
		{ name: '모델', fieldName: '모델', width: '80', header: { text: '모델' }, autoFilter:true },
		{ name: '제품코드', fieldName: '제품코드', width: '80', header: { text: '제품코드' }, autoFilter:true },
		{ name: 'revNo', fieldName: 'revNo', width: '80', header: { text: 'RevNo' }, autoFilter:true },
		{ name: 'lotRevNo', fieldName: 'lotRevNo', width: '80', header: { text: 'LotRevNo' }, autoFilter:true },
		{ name: 'runRevNo', fieldName: 'runRevNo', width: '80', header: { text: 'RunRevNo' }, autoFilter:true },
		{ name: '양산이관구분', fieldName: '양산이관구분', width: '90', header: { text: '양산이관구분' }, autoFilter:true },
		{ name: '양산이관Code', fieldName: '양산이관Code', width: '100', header: { text: '양산이관CODE' }, autoFilter:true },
		{ name: '주요변경사항', fieldName: '주요변경사항', width: '150', header: { text: '주요변경사항' }, autoFilter:true },
		{ name: 'lotNo', fieldName: 'lotNo', width: '80', header: { text: 'LotNo' }, autoFilter:true },
		{ name: 'runNo', fieldName: 'runNo', width: '80', header: { text: 'RunNo' }, autoFilter:true },
		{ name: '변경접수일', fieldName: '변경접수일', width: '100', header: { text: '변경접수일' }, autoFilter:true },
		{ name: '비고', fieldName: '비고', width: '150', header: { text: '비고' }, autoFilter:true },
		{ name: '고객사', fieldName: '고객사', width: '80', header: { text: '고객사' }, autoFilter:true },
		{ name: '고객사Model', fieldName: '고객사Model', width: '120', header: { text: '고객사Model' }, autoFilter:true },
		{ name: '고객사Code', fieldName: '고객사Code', width: '80', header: { text: '고객사CODE' }, autoFilter:true },
		{ name: '고객사PartCodee', fieldName: '고객사PartCodee', width: '120', header: { text: '고객사PartCodeE' }, autoFilter:true },
		{ name: 'glass정보제조사', fieldName: 'glass정보제조사', width: '120', header: { text: 'Glass정보제조사' }, autoFilter:true },
		{ name: 'glass정보모델', fieldName: 'glass정보모델', width: '120', header: { text: 'Glass정보모델' }, autoFilter:true },
		{ name: 'glass정보Size대각Inch', fieldName: 'glass정보Size대각Inch', width: '120', header: { text: 'Glass정보Size대각Inch' }, autoFilter:true },
		{ name: 'glass정보SizeMm', fieldName: 'glass정보SizeMm', width: '150', header: { text: 'Glass정보SizeMm' }, autoFilter:true },
		{ name: 'glass정보Size두께', fieldName: 'glass정보Size두께', width: '120', header: { text: 'Glass정보Size두께' }, autoFilter:true },
		{ name: 'glass정보가공치수', fieldName: 'glass정보가공치수', width: '120', header: { text: 'Glass정보가공치수' }, autoFilter:true },
		{ name: 'film정보전면원단사', fieldName: 'film정보전면원단사', width: '120', header: { text: 'Film정보전면원단사' }, autoFilter:true },
		{ name: 'film정보전면원단', fieldName: 'film정보전면원단', width: '120', header: { text: 'Film정보전면원단' }, autoFilter:true },
		{ name: 'film정보전면SizeMm', fieldName: 'film정보전면SizeMm', width: '150', header: { text: 'Film정보전면SizeMm' }, autoFilter:true },
		{ name: 'film정보전면두께Mm', fieldName: 'film정보전면두께Mm', width: '120', header: { text: 'Film정보전면두께Mm' }, autoFilter:true },
		{ name: 'film정보전면손잡이', fieldName: 'film정보전면손잡이', width: '120', header: { text: 'Film정보전면손잡이' }, autoFilter:true },
		{ name: 'film정보전면타발사', fieldName: 'film정보전면타발사', width: '120', header: { text: 'Film정보전면타발사' }, autoFilter:true },
		{ name: 'film정보전면Ver', fieldName: 'film정보전면Ver', width: '120', header: { text: 'Film정보전면Ver' }, autoFilter:true },
		{ name: 'film정보배면원단사', fieldName: 'film정보배면원단사', width: '120', header: { text: 'Film정보배면원단사' }, autoFilter:true },
		{ name: 'film정보배면원단', fieldName: 'film정보배면원단', width: '120', header: { text: 'Film정보배면원단' }, autoFilter:true },
		{ name: 'film정보배면SizeMm', fieldName: 'film정보배면SizeMm', width: '150', header: { text: 'Film정보배면SizeMm' }, autoFilter:true },
		{ name: 'film정보배면두께Mm', fieldName: 'film정보배면두께Mm', width: '120', header: { text: 'Film정보배면두께Mm' }, autoFilter:true },
		{ name: 'film정보배면손잡이', fieldName: 'film정보배면손잡이', width: '120', header: { text: 'Film정보배면손잡이' }, autoFilter:true },
		{ name: 'film정보배면타발사', fieldName: 'film정보배면타발사', width: '120', header: { text: 'Film정보배면타발사' }, autoFilter:true },
		{ name: 'film정보배면Ver', fieldName: 'film정보배면Ver', width: '120', header: { text: 'Film정보배면Ver' }, autoFilter:true },
		{ name: 'tray제조사', fieldName: 'tray제조사', width: '120', header: { text: 'Tray제조사' }, autoFilter:true },
		{ name: 'trayModel', fieldName: 'trayModel', width: '80', header: { text: 'TrayModel' }, autoFilter:true },
		{ name: 'tray원단', fieldName: 'tray원단', width: '80', header: { text: 'Tray원단' }, autoFilter:true },
		{ name: 'tray적재수량형태', fieldName: 'tray적재수량형태', width: '120', header: { text: 'Tray적재수량형태' }, autoFilter:true },
		{ name: 'tray원단두께Mm', fieldName: 'tray원단두께Mm', width: '120', header: { text: 'Tray원단두께Mm' }, autoFilter:true },
		{ name: 'tray적재단수', fieldName: 'tray적재단수', width: '120', header: { text: 'Tray적재단수' }, autoFilter:true },
		{ name: 'trayVer', fieldName: 'trayVer', width: '80', header: { text: 'TrayVer' }, autoFilter:true },
		{ name: '특이사항', fieldName: '특이사항', width: '150', header: { text: '특이사항' }, autoFilter:true },
	],
}

module.exports = grid;