/*
* 기준정보 > 모델관리 > 모델기본정보
*/
const { ValueType } = require('realgrid');

const grid = {

	options: {
		checkBar: { visible: true, exclusive: false,syncHeadCheck:true },
		copy: { enabled: true, singleMode: false },
		//dataDrop: {},
		display: { columnMovable: false, editItemMerging: true, fitStyle: "fill" },
		edit: { editable: true, commitByCell: true },
		//editor: {},
		//filtering: {},
		//filterMode: {},
		//filterPanel: {},
		//fixed: {},
		footer: { visible: false },
		//footers: {},
		//format: {},
		header: { height: 25 },
		//headerSummaries: {},
		//headerSummary: {},
		hideDeletedRows: true,
		paste: { enabled: true },
		rowIndicator: { visible: true },
		sorting: { enabled: false },
		//sortMode: {},
		stateBar: { visible: true },
		//summaryMode: {},
	},
	fields: [ 
		{ fieldName: '구분', dataType: ValueType.TEXT },
		{ fieldName: '적재매수', dataType: ValueType.TEXT },
		{ fieldName: '원장두께', dataType: ValueType.TEXT },
		{ fieldName: '원장구분', dataType: ValueType.TEXT },
		{ fieldName: 'utgVersion', dataType: ValueType.TEXT },
		{ fieldName: 'model', dataType: ValueType.TEXT },
		{ fieldName: 'sdc모델명', dataType: ValueType.TEXT },
		{ fieldName: '고객사', dataType: ValueType.TEXT },
		{ fieldName: '대각인치', dataType: ValueType.TEXT },
		{ fieldName: 'modelName', dataType: ValueType.TEXT },
		{ fieldName: 'modelCode', dataType: ValueType.TEXT },
		{ fieldName: '카세트최대적재수량', dataType: ValueType.TEXT },
		{ fieldName: 'utg가공Size장면', dataType: ValueType.TEXT },
		{ fieldName: 'utg가공Size단면', dataType: ValueType.TEXT },
		{ fieldName: 'utg가공Size두께', dataType: ValueType.TEXT },
		{ fieldName: 'utg출하Size장면', dataType: ValueType.TEXT },
		{ fieldName: 'utg출하Size단면', dataType: ValueType.TEXT },
		{ fieldName: 'utg출하Size두께', dataType: ValueType.TEXT },
		{ fieldName: 'agb적용여부', dataType: ValueType.TEXT },
		{ fieldName: 'agbBendingPoint', dataType: ValueType.TEXT },
		{ fieldName: 'agbR', dataType: ValueType.TEXT },
		{ fieldName: 'agbBeding시간', dataType: ValueType.TEXT },
		{ fieldName: 'film전면자재사양', dataType: ValueType.TEXT },
		{ fieldName: 'film전면자재코드', dataType: ValueType.TEXT },
		{ fieldName: 'film전면PfVersion', dataType: ValueType.TEXT },
		{ fieldName: 'film전면원단사', dataType: ValueType.TEXT },
		{ fieldName: 'film전면타발사', dataType: ValueType.TEXT },
		{ fieldName: 'film배면자재사양', dataType: ValueType.TEXT },
		{ fieldName: 'film배면자재코드', dataType: ValueType.TEXT },
		{ fieldName: 'film배면PfVersion', dataType: ValueType.TEXT },
		{ fieldName: 'film배면원단사', dataType: ValueType.TEXT },
		{ fieldName: 'film배면타발사', dataType: ValueType.TEXT },
		{ fieldName: 'film장변SizeMm', dataType: ValueType.TEXT },
		{ fieldName: 'film단변SizeMm', dataType: ValueType.TEXT },
		{ fieldName: 'pfl합지장변AlignMm', dataType: ValueType.TEXT },
		{ fieldName: 'pfl합지단변AlignMm', dataType: ValueType.TEXT },
		{ fieldName: 'curlMm방향', dataType: ValueType.TEXT },
		{ fieldName: 'curlMm1차', dataType: ValueType.TEXT },
		{ fieldName: 'curlMm2차', dataType: ValueType.TEXT },
		{ fieldName: 'curlMmPfl목시검사내부관리기준', dataType: ValueType.TEXT },
		{ fieldName: 'curlMm2차측정시제거필름', dataType: ValueType.TEXT },
		{ fieldName: '변경점', dataType: ValueType.TEXT },
		{ fieldName: 'film전면색1', dataType: ValueType.TEXT },
		{ fieldName: 'film전면색2', dataType: ValueType.TEXT },
		{ fieldName: 'film전면색3', dataType: ValueType.TEXT },
		{ fieldName: 'film전면색4', dataType: ValueType.TEXT },
		{ fieldName: 'film배면색1', dataType: ValueType.TEXT },
		{ fieldName: 'film배면색2', dataType: ValueType.TEXT },
		{ fieldName: 'film배면색3', dataType: ValueType.TEXT },
		{ fieldName: 'film배면색4', dataType: ValueType.TEXT },
	],
	
	columns: [
		{
			name: 'model', fieldName: 'model', width: '75', header: { text: 'MODEL' }, autoFilter: true,
			styleCallback: function(grid, dataCell){
				var ret = {}
		
				if(dataCell.item.rowState == 'created' || dataCell.item.itemState == 'appending' || dataCell.item.itemState == 'inserting'){
				ret.editable = true;
				} else {
				ret.editable = false;
				}
		
				return ret;
			}
		},
		{ name: '구분', fieldName: '구분', width: '50', header: { text: '구분' }, autoFilter: true },
		{ name: '적재매수', fieldName: '적재매수', width: '80', header: { text: '적재매수' }, autoFilter: true },
		{ name: '원장두께', fieldName: '원장두께', width: '80', header: { text: '원장두께' }, autoFilter: true },
		{ name: '원장구분', fieldName: '원장구분', width: '80', header: { text: '원장구분' }, autoFilter: true },
		{ name: 'utgVersion', fieldName: 'utgVersion', width: '150', header: { text: 'UTGVersion' }, autoFilter: true,},
		{ name: 'sdc모델명', fieldName: 'sdc모델명', width: '90', header: { text: 'SDC모델명' }, autoFilter: true },
		{ name: '고객사', fieldName: '고객사', width: '70', header: { text: '고객사' }, autoFilter: true },
		{ name: '대각인치', fieldName: '대각인치', width: '120', header: { text: '대각인치' }, autoFilter: true },
		{ name: 'modelName', fieldName: 'modelName', width: '135', header: { text: 'MODELNAME' }, autoFilter: true },
		{ name: 'modelCode', fieldName: 'modelCode', width: '135', header: { text: 'MODELCODE' }, autoFilter: true },
		{ name: '카세트최대적재수량', fieldName: '카세트최대적재수량', width: '135', header: { text: '카세트최대적재수량' }, autoFilter: true },
		{ name: 'utg가공Size장면', fieldName: 'utg가공Size장면', width: '165', header: { text: 'UTG가공SIZE장면' }, autoFilter: true },
		{ name: 'utg가공Size단면', fieldName: 'utg가공Size단면', width: '165', header: { text: 'UTG가공SIZE단면' }, autoFilter: true },
		{ name: 'utg가공Size두께', fieldName: 'utg가공Size두께', width: '165', header: { text: 'UTG가공SIZE두께' }, autoFilter: true },
		{ name: 'utg출하Size장면', fieldName: 'utg출하Size장면', width: '165', header: { text: 'UTG출하SIZE장면' }, autoFilter: true },
		{ name: 'utg출하Size단면', fieldName: 'utg출하Size단면', width: '165', header: { text: 'UTG출하SIZE단면' }, autoFilter: true },
		{ name: 'utg출하Size두께', fieldName: 'utg출하Size두께', width: '165', header: { text: 'UTG출하SIZE두께' }, autoFilter: true },
		{ name: 'agb적용여부', fieldName: 'agb적용여부', width: '105', header: { text: 'AGB적용여부' }, autoFilter: true },
		{ name: 'agbBendingPoint', fieldName: 'agbBendingPoint', width: '225', header: { text: 'AGBBendingPoint' }, autoFilter: true },
		{ name: 'agbR', fieldName: 'agbR', width: '80', header: { text: 'AGBR' }, autoFilter: true },
		{ name: 'agbBeding시간', fieldName: 'agbBeding시간', width: '165', header: { text: 'AGBBeding시간' }, autoFilter: true },
		{ name: 'film전면자재사양', fieldName: 'film전면자재사양', width: '150', header: { text: 'FILM전면자재사양' }, autoFilter: true },
		{ name: 'film전면자재코드', fieldName: 'film전면자재코드', width: '150', header: { text: 'FILM전면자재코드' }, autoFilter: true },
		{ name: 'film전면PfVersion', fieldName: 'film전면PfVersion', width: '225', header: { text: 'FILM전면PFVersion' }, autoFilter: true },
		{ name: 'film전면원단사', fieldName: 'film전면원단사', width: '135', header: { text: 'FILM전면원단사' }, autoFilter: true },
		{ name: 'film전면타발사', fieldName: 'film전면타발사', width: '135', header: { text: 'FILM전면타발사' }, autoFilter: true },
		{ name: 'film배면자재사양', fieldName: 'film배면자재사양', width: '150', header: { text: 'FILM배면자재사양' }, autoFilter: true },
		{ name: 'film배면자재코드', fieldName: 'film배면자재코드', width: '150', header: { text: 'FILM배면자재코드' }, autoFilter: true },
		{ name: 'film배면PfVersion', fieldName: 'film배면PfVersion', width: '225', header: { text: 'FILM배면PFVersion' }, autoFilter: true },
		{ name: 'film배면원단사', fieldName: 'film배면원단사', width: '135', header: { text: 'FILM배면원단사' }, autoFilter: true },
		{ name: 'film배면타발사', fieldName: 'film배면타발사', width: '135', header: { text: 'FILM배면타발사' }, autoFilter: true },
		{ name: 'film장변SizeMm', fieldName: 'film장변SizeMm', width: '180', header: { text: 'FILM장변SIZEMm' }, autoFilter: true },
		{ name: 'film단변SizeMm', fieldName: 'film단변SizeMm', width: '180', header: { text: 'FILM단변SIZEMm' }, autoFilter: true },
		{ name: 'pfl합지장변AlignMm', fieldName: 'pfl합지장변AlignMm', width: '210', header: { text: 'PFL합지장변AlignMm' }, autoFilter: true },
		{ name: 'pfl합지단변AlignMm', fieldName: 'pfl합지단변AlignMm', width: '210', header: { text: 'PFL합지단변AlignMm' }, autoFilter: true },
		{ name: 'curlMm방향', fieldName: 'curlMm방향', width: '120', header: { text: 'CURLMm방향' }, autoFilter: true },
		{ name: 'curlMm1차', fieldName: 'curlMm1차', width: '120', header: { text: 'CURLMm1차' }, autoFilter: true },
		{ name: 'curlMm2차', fieldName: 'curlMm2차', width: '120', header: { text: 'CURLMm2차' }, autoFilter: true },
		{ name: 'curlMmPfl목시검사내부관리기준', fieldName: 'curlMmPfl목시검사내부관리기준', width: '285', header: { text: 'CURLMmPFL목시검사내부관리기준' }, autoFilter: true },
		{ name: 'curlMm2차측정시제거필름', fieldName: 'curlMm2차측정시제거필름', width: '225', header: { text: 'CURLMm2차측정시제거필름' }, autoFilter: true },
		{ name: '변경점', fieldName: '변경점', width: '120', header: { text: '변경점' }, autoFilter: true },
		{ name: 'film전면색1', fieldName: 'film전면색1', width: '120', header: { text: 'FILM전면색1' }, autoFilter: true },
		{ name: 'film전면색2', fieldName: 'film전면색2', width: '120', header: { text: 'FILM전면색2' }, autoFilter: true },
		{ name: 'film전면색3', fieldName: 'film전면색3', width: '120', header: { text: 'FILM전면색3' }, autoFilter: true },
		{ name: 'film전면색4', fieldName: 'film전면색4', width: '120', header: { text: 'FILM전면색4' }, autoFilter: true },
		{ name: 'film배면색1', fieldName: 'film배면색1', width: '120', header: { text: 'FILM배면색1' }, autoFilter: true },
		{ name: 'film배면색2', fieldName: 'film배면색2', width: '120', header: { text: 'FILM배면색2' }, autoFilter: true },
		{ name: 'film배면색3', fieldName: 'film배면색3', width: '120', header: { text: 'FILM배면색3' }, autoFilter: true },
		{ name: 'film배면색4', fieldName: 'film배면색4', width: '120', header: { text: 'FILM배면색4' }, autoFilter: true }
	]	
}

module.exports = grid;