/*
 * 제조 실적 입력 > Back#2 Cell QC > 설비 로그 조회
 */
const { ValueType } = require('realgrid');
const { rgDisplayDateTime1 } = require('@/utils/dateUtils');

const grid = {
  options: {
    checkBar: { visible: false },
    copy: { enabled: true, singleMode: true },
    display: {
      columnMovable: false,
      emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'NONE',
      hscrollBar: true,
      showEmptyMessage: true,
    },
    edit: { editable: false },
    footers: { visible: false },
    paste: { enabled: false },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
    fixed: { colBarWidth: 1, colCount: 2 },
  },

  fields: [
		{ fieldName: 'seqId', dataType: ValueType.TEXT },
		{ fieldName: 'runId', dataType: ValueType.TEXT },
		{ fieldName: 'runid타입', dataType: ValueType.TEXT },
		{ fieldName: '작업차수', dataType: ValueType.NUMBER },
		{ fieldName: '일일생산일련번호', dataType: ValueType.TEXT },
		{ fieldName: 'tray번호', dataType: ValueType.NUMBER },
		{ fieldName: 'tray구분', dataType: ValueType.TEXT },
		{ fieldName: 'cellId', dataType: ValueType.TEXT },
		{ fieldName: 'originNo', dataType: ValueType.TEXT },
		{ fieldName: 'packQrno', dataType: ValueType.TEXT },
		{ fieldName: '라인구분', dataType: ValueType.TEXT },
		{ fieldName: '재작업', dataType: ValueType.NUMBER },
		{ fieldName: 'bef공정코드', dataType: ValueType.TEXT },
		{ fieldName: 'worker', dataType: ValueType.TEXT },
		{ fieldName: 'shift', dataType: ValueType.TEXT },
		{ fieldName: '작업조', dataType: ValueType.TEXT },
		{ fieldName: 'startTime', dataType: ValueType.TEXT },
		{ fieldName: 'endTime', dataType: ValueType.TEXT },
		{ fieldName: 'cell상태', dataType: ValueType.TEXT },
		{ fieldName: 'cell처리', dataType: ValueType.TEXT },
		{ fieldName: '작업일자', dataType: ValueType.TEXT },
		{ fieldName: '[result]', dataType: ValueType.TEXT },
		{ fieldName: 'scrap', dataType: ValueType.TEXT },
		{ fieldName: '특이사항', dataType: ValueType.TEXT },
		{ fieldName: '샘플의뢰여부', dataType: ValueType.NUMBER },
		{ fieldName: '샘플Result', dataType: ValueType.TEXT },
		{ fieldName: '재공적용여부', dataType: ValueType.NUMBER },
  ],

  columns: [
	  { name: 'seqId', fieldName: 'seqId', width: '90', header: { text: 'SEQ_ID' }, autoFilter: true, numberFormat: '####', styleName: 'tr' },
    { name: 'runId', fieldName: 'runId', width: '180', header: { text: 'RUN_ID' }, autoFilter: true, styleName: 'tl' },
 		{ name: 'runid타입', fieldName: 'runid타입', width: '140', header: { text: 'RUNID_타입' } , autoFilter: true, styleName: 'tl', },
		{ name: '작업차수', fieldName: '작업차수', width: '90', header: { text: '작업차수' } , autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
		{ name: '일일생산일련번호', fieldName: '일일생산일련번호', width: '160', header: { text: '일일생산일련번호' } , autoFilter: true, styleName: 'tl', },
		{ name: 'tray번호', fieldName: 'tray번호', width: '120', header: { text: 'Tray번호' } , autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
		{ name: 'tray구분', fieldName: 'tray구분', width: '120', header: { text: 'TRAY_구분' } , autoFilter: true, styleName: 'tl', },
		{ name: 'cellId', fieldName: 'cellId', width: '260', header: { text: 'CELL_ID' } , autoFilter: true, styleName: 'tl', },
		{ name: 'originNo', fieldName: 'originNo', width: '100', header: { text: 'ORIGIN_NO' } , autoFilter: true, styleName: 'tl', },
		{ name: 'packQrno', fieldName: 'packQrno', width: '270', header: { text: 'PACK_QRNO' } , autoFilter: true, styleName: 'tl', },
		{ name: '라인구분', fieldName: '라인구분', width: '90', header: { text: '라인구분' } , autoFilter: true, styleName: 'tl', },
		{ name: '재작업', fieldName: '재작업', width: '90', header: { text: '재작업' } , autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
		{ name: 'bef공정코드', fieldName: 'bef공정코드', width: '140', header: { text: 'BEF_공정코드' } , autoFilter: true, styleName: 'tl', },
		{ name: 'worker', fieldName: 'worker', width: '120', header: { text: 'Worker' } , autoFilter: true, styleName: 'tl', },
		{ name: 'shift', fieldName: 'shift', width: '100', header: { text: 'Shift' } , autoFilter: true, styleName: 'tl', },
		{ name: '작업조', fieldName: '작업조', width: '90', header: { text: '작업조' } , autoFilter: true, styleName: 'tl', },
		{ name: 'startTime', fieldName: 'startTime', width: '150', header: { text: 'Start_Time' } , autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime1},
		{ name: 'endTime', fieldName: 'endTime', width: '150', header: { text: 'End_Time' } , autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime1},
		{ name: 'cell상태', fieldName: 'cell상태', width: '120', header: { text: 'CELL상태' } , autoFilter: true, styleName: 'tl', },
		{ name: 'cell처리', fieldName: 'cell처리', width: '120', header: { text: 'CELL처리' } , autoFilter: true, styleName: 'tl', },
		{ name: '작업일자', fieldName: '작업일자', width: '90', header: { text: '작업일자' } , autoFilter: true, styleName: 'tl', },
		{ name: 'result', fieldName: 'result', width: '120', header: { text: 'RESULT' } , autoFilter: true, styleName: 'tl', },
		{ name: 'scrap', fieldName: 'scrap', width: '100', header: { text: 'SCRAP' } , autoFilter: true, styleName: 'tl', },
		{ name: '특이사항', fieldName: '특이사항', width: '200', header: { text: '특이사항' } , autoFilter: true, styleName: 'tl', },
		{ name: '샘플의뢰여부', fieldName: '샘플의뢰여부', width: '120', header: { text: '샘플의뢰여부' } , autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
		{ name: '샘플Result', fieldName: '샘플Result', width: '120', header: { text: '샘플_RESULT' } , autoFilter: true, styleName: 'tl', },
		{ name: '재공적용여부', fieldName: '재공적용여부', width: '120', header: { text: '재공적용_여부' } , autoFilter: true, numberFormat: '#,###.###', styleName: 'tr'},  
  ],
};

module.exports = grid;
