/*
 * 제조 실적 입력 > Back#2 Cell QC > 설비 로그 조회
 */
const { ValueType } = require('realgrid');
const { rgDisplayDateTime1 } = require('@/utils/dateUtils');

const grid = {
  options: {
    checkBar: { visible: false },
    copy: { enabled: true, singleMode: true },
    display: {
      columnMovable: false,
      emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'NONE',
      hscrollBar: true,
      showEmptyMessage: true,
    },
    edit: { editable: false },
    footers: { visible: false },
    paste: { enabled: false },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
    fixed: { colBarWidth: 1, colCount: 5 },
  },

  fields: [
    { fieldName: 'seqNo', dataType: ValueType.NUMBER },
    { fieldName: 'eqpId', dataType: ValueType.TEXT },
    { fieldName: '설비약명', dataType: ValueType.TEXT },
    { fieldName: 'uniqueId', dataType: ValueType.TEXT },
    { fieldName: 'packNo', dataType: ValueType.TEXT },
    { fieldName: 'productCode', dataType: ValueType.TEXT },
    { fieldName: 'vendorCode', dataType: ValueType.TEXT },
    { fieldName: 'productDate', dataType: ValueType.TEXT },
    { fieldName: 'packCount', dataType: ValueType.NUMBER },
    { fieldName: 'trayCount', dataType: ValueType.NUMBER },
    { fieldName: 'isFinish', dataType: ValueType.TEXT },
    { fieldName: 'operName', dataType: ValueType.TEXT },
    { fieldName: 'operTeam', dataType: ValueType.TEXT },
    { fieldName: 'regDate', dataType: ValueType.TEXT },
    { fieldName: 'convertRegDate', dataType: ValueType.TEXT },
    { fieldName: 'convertRegTime', dataType: ValueType.TEXT },
    { fieldName: 'convertUpdDate', dataType: ValueType.TEXT },
    { fieldName: 'convertUpdTime', dataType: ValueType.TEXT },
    { fieldName: 'updDate', dataType: ValueType.TEXT },
    { fieldName: 'pack구분', dataType: ValueType.TEXT },
    { fieldName: 'runId', dataType: ValueType.TEXT },
    { fieldName: 'cell수량', dataType: ValueType.NUMBER },
    { fieldName: 'deleteSu', dataType: ValueType.NUMBER },
    { fieldName: 'boxNo', dataType: ValueType.TEXT },
    { fieldName: '발행자', dataType: ValueType.TEXT },
    { fieldName: '발행자서명', dataType: ValueType.NUMBER },
    { fieldName: '승인자', dataType: ValueType.TEXT },
    { fieldName: '승인자서명', dataType: ValueType.NUMBER },
    { fieldName: '처리시각', dataType: ValueType.TEXT },
    { fieldName: 'pack상태', dataType: ValueType.TEXT },
    { fieldName: '폐기사유', dataType: ValueType.TEXT },
    { fieldName: '폐기시각', dataType: ValueType.TEXT },
    { fieldName: '샘플의뢰여부', dataType: ValueType.NUMBER },
    { fieldName: '재작업여부', dataType: ValueType.NUMBER },
    { fieldName: 'result', dataType: ValueType.TEXT },
  ],

  columns: [
    { name: 'seqNo', fieldName: 'seqNo', width: '90', header: { text: 'SEQ_NO' }, autoFilter: true, numberFormat: '####', styleName: 'tr' },
    { name: 'eqpId', fieldName: 'eqpId', width: '70', header: { text: 'EQP_ID' }, autoFilter: true, styleName: 'tl' },
    {
      name: '설비약명',
      fieldName: '설비약명',
      header: { text: '호기' },
      autoFilter: true,
      styleName: 'tl',
    },
    { name: 'uniqueId', fieldName: 'uniqueId', width: '300', header: { text: 'UNIQUE_ID' }, autoFilter: true, styleName: 'tl' },
    { name: 'packNo', fieldName: 'packNo', width: '250', header: { text: 'PACK_NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'productCode', fieldName: 'productCode', width: '140', header: { text: 'PRODUCT_CODE' }, autoFilter: true, styleName: 'tl' },
    { name: 'vendorCode', fieldName: 'vendorCode', width: '130', header: { text: 'VENDOR_CODE' }, autoFilter: true, styleName: 'tl' },
    { name: 'productDate', fieldName: 'productDate', width: '140', header: { text: 'PRODUCT_DATE' }, autoFilter: true, styleName: 'tl' },
    { name: 'packCount', fieldName: 'packCount', width: '120', header: { text: 'PACK_COUNT' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'trayCount', fieldName: 'trayCount', width: '120', header: { text: 'TRAY_COUNT' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'isFinish', fieldName: 'isFinish', width: '110', header: { text: 'IS_FINISH' }, autoFilter: true, styleName: 'tl' },
    { name: 'operName', fieldName: 'operName', width: '120', header: { text: 'OPER_NAME' }, autoFilter: true, styleName: 'tl' },
    { name: 'operTeam', fieldName: 'operTeam', width: '120', header: { text: 'OPER_TEAM' }, autoFilter: true, styleName: 'tl' },
    // { name: 'regDate', fieldName: 'regDate', width: '80', header: { text: 'REG_DATE' }, autoFilter: true, styleName: 'tl' },
    // { name: 'updDate', fieldName: 'updDate', width: '80', header: { text: 'UPD_DATE' }, autoFilter: true, styleName: 'tl' },
    { name: 'convertRegDate', fieldName: 'convertRegDate', width: '110', header: { text: 'REG_DATE' }, autoFilter: true, styleName: 'tl' },
    { name: 'convertRegTime', fieldName: 'convertRegTime', width: '110', header: { text: 'REG_TIME' }, autoFilter: true, styleName: 'tl' },
    { name: 'convertUpdDate', fieldName: 'convertUpdDate', width: '110', header: { text: 'UPD_DATE' }, autoFilter: true, styleName: 'tl' },
    { name: 'convertUpdTime', fieldName: 'convertUpdTime', width: '110', header: { text: 'UPD_TIME' }, autoFilter: true, styleName: 'tl' },
    { name: 'pack구분', fieldName: 'pack구분', width: '100', header: { text: 'PACK구분' }, autoFilter: true, styleName: 'tl' },
    { name: 'runId', fieldName: 'runId', width: '170', header: { text: 'RUN_ID' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량', fieldName: 'cell수량', width: '100', header: { text: 'CELL수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'deleteSu', fieldName: 'deleteSu', width: '110', header: { text: 'DELETE_SU' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'boxNo', fieldName: 'boxNo', width: '250', header: { text: 'BOX_NO' }, autoFilter: true, styleName: 'tl' },
    { name: '발행자', fieldName: '발행자', width: '100', header: { text: '발행자' }, autoFilter: true, styleName: 'tl' },
    { name: '발행자서명', fieldName: '발행자서명', width: '120', header: { text: '발행자서명' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '승인자', fieldName: '승인자', width: '100', header: { text: '승인자' }, autoFilter: true, styleName: 'tl' },
    { name: '승인자서명', fieldName: '승인자서명', width: '120', header: { text: '승인자서명' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '처리시각', fieldName: '처리시각', width: '160', header: { text: '처리시각' }, autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime1 },
    { name: 'pack상태', fieldName: 'pack상태', width: '100', header: { text: 'PACK상태' }, autoFilter: true, styleName: 'tl' },
    { name: '폐기사유', fieldName: '폐기사유', width: '100', header: { text: '폐기사유' }, autoFilter: true, styleName: 'tl' },
    { name: '폐기시각', fieldName: '폐기시각', width: '160', header: { text: '폐기시각' }, autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime1 },
    { name: '샘플의뢰여부', fieldName: '샘플의뢰여부', width: '140', header: { text: '샘플의뢰여부' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '재작업여부', fieldName: '재작업여부', width: '120', header: { text: '재작업여부' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'result', fieldName: 'result', width: '120', header: { text: 'RESULT' }, autoFilter: true, styleName: 'tl' },
  ],
};

module.exports = grid;
