/*
 * 제조 실적 입력 > Back#2 Cassette QC > 설비 로그 조회
 */
const { ValueType } = require('realgrid');
const { rgDisplayDateTime } = require('@/utils/dateUtils');

const grid = {
  options: {
    checkBar: { visible: false },
    copy: { enabled: true, singleMode: true },
    display: {
      columnMovable: false,
      emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'NONE',
      hscrollBar: true,
      showEmptyMessage: true,
    },
    edit: { editable: false },
    footers: { visible: false },
    paste: { enabled: false },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
    fixed: { colBarWidth: 1, colCount: 4 },
  },

  fields: [
    { fieldName: 'seqId', dataType: ValueType.NUMBER },
    { fieldName: '공장코드', dataType: ValueType.TEXT },
    { fieldName: '공정코드', dataType: ValueType.TEXT },
    { fieldName: 'runNo', dataType: ValueType.TEXT },
    { fieldName: '근무조', dataType: ValueType.TEXT },
    { fieldName: '작업자', dataType: ValueType.TEXT },
    //{ fieldName: '설비호기', dataType: ValueType.TEXT },
    { fieldName: '설비약명', dataType: ValueType.TEXT },
    { fieldName: 'recipeName', dataType: ValueType.TEXT },
    { fieldName: 'startTime', dataType: ValueType.TEXT },
    { fieldName: 'endTime', dataType: ValueType.TEXT },
    { fieldName: 'cassetteLd', dataType: ValueType.TEXT },
    { fieldName: 'ldCst행열', dataType: ValueType.TEXT },
    { fieldName: 'cassetteUld', dataType: ValueType.TEXT },
    { fieldName: 'uldCst행열', dataType: ValueType.TEXT },
    { fieldName: 'cellidUtg', dataType: ValueType.TEXT },
    { fieldName: '밴딩Speed', dataType: ValueType.NUMBER },
    { fieldName: 'reserve1', dataType: ValueType.NUMBER },
    { fieldName: '밴딩Gap1', dataType: ValueType.NUMBER },
    { fieldName: '밴딩stage압력1', dataType: ValueType.NUMBER },
    { fieldName: '밴딩R', dataType: ValueType.NUMBER },
    { fieldName: 'dateTime1p', dataType: ValueType.TEXT },
    { fieldName: 'preAlignX', dataType: ValueType.NUMBER },
    { fieldName: 'preAlignY', dataType: ValueType.NUMBER },
    { fieldName: 'preAlignTh', dataType: ValueType.NUMBER },
    { fieldName: '밴딩R2p', dataType: ValueType.NUMBER },
    { fieldName: 'dateTime2p', dataType: ValueType.TEXT },
    { fieldName: 'preAlignX2p', dataType: ValueType.NUMBER },
    { fieldName: 'preAlignY2p', dataType: ValueType.NUMBER },
    { fieldName: 'preAlignTh2p', dataType: ValueType.NUMBER },
    { fieldName: '밴딩R3p', dataType: ValueType.NUMBER },
    { fieldName: 'dateTime3p', dataType: ValueType.TEXT },
    { fieldName: 'preAlignX3p', dataType: ValueType.NUMBER },
    { fieldName: 'preAlignY3p', dataType: ValueType.NUMBER },
    { fieldName: 'preAlignTh3p', dataType: ValueType.NUMBER },
    { fieldName: 'uldAlignX', dataType: ValueType.NUMBER },
    { fieldName: 'uldAlignY', dataType: ValueType.NUMBER },
    { fieldName: 'uldAlignTh', dataType: ValueType.NUMBER },
    { fieldName: 'reserve2', dataType: ValueType.NUMBER },
    { fieldName: 'ldCstline', dataType: ValueType.TEXT },
    { fieldName: '밴딩Stage', dataType: ValueType.TEXT },
    { fieldName: 'uldCstline', dataType: ValueType.TEXT },
    { fieldName: '삭제위치', dataType: ValueType.TEXT },
    { fieldName: '불량명', dataType: ValueType.TEXT },
  ],

  columns: [
    { name: 'seqId', fieldName: 'seqId', width: '80', header: { text: 'SEQ_ID' }, autoFilter: true, numberFormat: '####', styleName: 'tr' },
    { name: '공장코드', fieldName: '공장코드', width: '80', header: { text: '공장코드' }, autoFilter: true, styleName: 'tl' },
    { name: '공정코드', fieldName: '공정코드', width: '80', header: { text: '공정코드' }, autoFilter: true, styleName: 'tl' },
    { name: 'runNo', fieldName: 'runNo', width: '150', header: { text: 'RUN_NO' }, autoFilter: true, styleName: 'tl' },
    { name: '근무조', fieldName: '근무조', width: '80', header: { text: '근무조' }, autoFilter: true, styleName: 'tl' },
    { name: '작업자', fieldName: '작업자', width: '80', header: { text: '작업자' }, autoFilter: true, styleName: 'tl' },
    //{ name: '설비호기', fieldName: '설비호기', width: '80', header: { text: '설비호기' }, autoFilter: true , styleName: 'tl'},
    {
      name: '설비약명',
      fieldName: '설비약명',
      header: { text: '호기' },
      autoFilter: true,
      styleName: 'tl',
    },
    { name: 'recipeName', fieldName: 'recipeName', width: '110', header: { text: 'Recipe_name' }, autoFilter: true, styleName: 'tl' },
    { name: 'startTime', fieldName: 'startTime', width: '120', header: { text: 'Start_time' }, autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime },
    { name: 'endTime', fieldName: 'endTime', width: '120', header: { text: 'End_time' }, autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime },
    { name: 'cassetteLd', fieldName: 'cassetteLd', width: '110', header: { text: 'CASSETTE_LD' }, autoFilter: true, styleName: 'tl' },
    { name: 'ldCst행열', fieldName: 'ldCst행열', width: '100', header: { text: 'LD_CST행열' }, autoFilter: true, styleName: 'tl' },
    { name: 'cassetteUld', fieldName: 'cassetteUld', width: '120', header: { text: 'CASSETTE_ULD' }, autoFilter: true, styleName: 'tl' },
    { name: 'uldCst행열', fieldName: 'uldCst행열', width: '110', header: { text: 'ULD_CST행열' }, autoFilter: true, styleName: 'tl' },
    { name: 'cellidUtg', fieldName: 'cellidUtg', width: '110', header: { text: 'CellID_UTG' }, autoFilter: true, styleName: 'tl' },
    { name: '밴딩Speed', fieldName: '밴딩Speed', width: '90', header: { text: '밴딩_SPEED' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'reserve1', fieldName: 'reserve1', width: '90', header: { text: 'Reserve_1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '밴딩Gap1', fieldName: '밴딩Gap1', width: '90', header: { text: '밴딩_Gap1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '밴딩stage압력1', fieldName: '밴딩stage압력1', width: '140', header: { text: '밴딩Stage_압력1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '밴딩R', fieldName: '밴딩R', width: '80', header: { text: '밴딩_R' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'dateTime1p', fieldName: 'dateTime1p', width: '120', header: { text: 'Date_Time_1P' }, autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime },
    { name: 'preAlignX', fieldName: 'preAlignX', width: '110', header: { text: 'Pre_Align_X' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'preAlignY', fieldName: 'preAlignY', width: '110', header: { text: 'Pre_Align_Y' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'preAlignTh', fieldName: 'preAlignTh', width: '110', header: { text: 'Pre_Align_TH' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '밴딩R2p', fieldName: '밴딩R2p', width: '90', header: { text: '밴딩_R_2P' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'dateTime2p', fieldName: 'dateTime2p', width: '110', header: { text: 'Date_Time_2P' }, autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime },
    { name: 'preAlignX2p', fieldName: 'preAlignX2p', width: '130', header: { text: 'Pre_Align_X_2P' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'preAlignY2p', fieldName: 'preAlignY2p', width: '130', header: { text: 'Pre_Align_Y_2P' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'preAlignTh2p', fieldName: 'preAlignTh2p', width: '130', header: { text: 'Pre_Align_TH_2P' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '밴딩R3p', fieldName: '밴딩R3p', width: '90', header: { text: '밴딩_R_3P' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'dateTime3p', fieldName: 'dateTime3p', width: '110', header: { text: 'Date_Time_3P' }, autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime },
    { name: 'preAlignX3p', fieldName: 'preAlignX3p', width: '130', header: { text: 'Pre_Align_X_3P' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'preAlignY3p', fieldName: 'preAlignY3p', width: '130', header: { text: 'Pre_Align_Y_3P' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'preAlignTh3p', fieldName: 'preAlignTh3p', width: '130', header: { text: 'Pre_Align_TH_3P' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'uldAlignX', fieldName: 'uldAlignX', width: '110', header: { text: 'ULD_Align_X' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'uldAlignY', fieldName: 'uldAlignY', width: '110', header: { text: 'ULD_Align_Y' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'uldAlignTh', fieldName: 'uldAlignTh', width: '110', header: { text: 'ULD_Align_TH' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'reserve2', fieldName: 'reserve2', width: '90', header: { text: 'Reserve_2' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'ldCstline', fieldName: 'ldCstline', width: '100', header: { text: 'LD_CSTLine' }, autoFilter: true, styleName: 'tl' },
    { name: '밴딩Stage', fieldName: '밴딩Stage', width: '100', header: { text: '밴딩_STAGE' }, autoFilter: true, styleName: 'tl' },
    { name: 'uldCstline', fieldName: 'uldCstline', width: '110', header: { text: 'ULD_CSTLine' }, autoFilter: true, styleName: 'tl' },
    { name: '삭제위치', fieldName: '삭제위치', width: '80', header: { text: '삭제위치' }, autoFilter: true, styleName: 'tl' },
    { name: '불량명', fieldName: '불량명', width: '80', header: { text: '불량명' }, autoFilter: true, styleName: 'tl' },
  ],
};

module.exports = grid;
