/*
 * 제조 실적 입력 > Back#1 > 설비 로그 조회 > 박리 후 세정, 강화 후 세정, (재세정?)
 */
const { ValueType } = require('realgrid');
const { rgDisplayDateTime } = require('@/utils/dateUtils');

const grid = {
  options: {
    checkBar: { visible: false },
    copy: { enabled: true, singleMode: true },
    display: {
      columnMovable: false,
      emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'NONE',
      hscrollBar: true,
      showEmptyMessage: true,
    },
    edit: { editable: false },
    footers: { visible: false },
    paste: { enabled: false },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
    fixed: { colBarWidth: 1, colCount: 5 },
  },

  fields: [
    { fieldName: 'seqId', dataType: ValueType.NUMBER },
    { fieldName: '공장코드', dataType: ValueType.TEXT },
    { fieldName: '공정코드', dataType: ValueType.TEXT },
    //{ fieldName: '설비호기', dataType: ValueType.TEXT },
    { fieldName: '설비약명', dataType: ValueType.TEXT },
    { fieldName: 'runNo', dataType: ValueType.TEXT },
    { fieldName: '근무조', dataType: ValueType.TEXT },
    { fieldName: '작업자', dataType: ValueType.TEXT },
    { fieldName: 'startTime', dataType: ValueType.TEXT },
    { fieldName: 'endTime', dataType: ValueType.TEXT },
    { fieldName: 'inCstnoL', dataType: ValueType.TEXT },
    { fieldName: 'inCstnoR', dataType: ValueType.TEXT },
    { fieldName: 'inCstsu', dataType: ValueType.NUMBER },
    { fieldName: 'inCst행열L', dataType: ValueType.TEXT },
    { fieldName: 'inCst행열R', dataType: ValueType.TEXT },
    { fieldName: 'outCstnoL', dataType: ValueType.TEXT },
    { fieldName: 'outCstnoR', dataType: ValueType.TEXT },
    { fieldName: 'outCstsu', dataType: ValueType.NUMBER },
    { fieldName: 'outCst행열L', dataType: ValueType.TEXT },
    { fieldName: 'outCst행열R', dataType: ValueType.TEXT },
    { fieldName: '불량명', dataType: ValueType.TEXT },
    { fieldName: 'recipeParameter', dataType: ValueType.NUMBER },
    { fieldName: '히터온도1조', dataType: ValueType.NUMBER },
    { fieldName: '세척조온도1조', dataType: ValueType.NUMBER },
    { fieldName: '히터온도2조', dataType: ValueType.NUMBER },
    { fieldName: '세척조온도2조', dataType: ValueType.NUMBER },
    { fieldName: '히터온도3조', dataType: ValueType.NUMBER },
    { fieldName: '세척조온도3조', dataType: ValueType.NUMBER },
    { fieldName: '히터온도4조', dataType: ValueType.NUMBER },
    { fieldName: '세척조온도4조', dataType: ValueType.NUMBER },
    { fieldName: '히터온도5조', dataType: ValueType.NUMBER },
    { fieldName: '세척조온도5조', dataType: ValueType.NUMBER },
    { fieldName: '히터온도6조', dataType: ValueType.NUMBER },
    { fieldName: '세척조온도6조', dataType: ValueType.NUMBER },
    { fieldName: '히터온도7조', dataType: ValueType.NUMBER },
    { fieldName: '세척조온도7조', dataType: ValueType.NUMBER },
    { fieldName: '히터온도8조', dataType: ValueType.NUMBER },
    { fieldName: '세척조온도8조', dataType: ValueType.NUMBER },
    { fieldName: '히터온도9조', dataType: ValueType.NUMBER },
    { fieldName: '세척조온도9조', dataType: ValueType.NUMBER },
    { fieldName: '건조내부온도', dataType: ValueType.NUMBER },
    { fieldName: '건조온도#1', dataType: ValueType.NUMBER },
    { fieldName: '건조온도#2', dataType: ValueType.NUMBER },
    { fieldName: 'spare#1', dataType: ValueType.NUMBER },
    { fieldName: 'spare#2', dataType: ValueType.NUMBER },
    { fieldName: 'spare#3', dataType: ValueType.NUMBER },
    { fieldName: 'spare#4', dataType: ValueType.NUMBER },
    { fieldName: 'spare#5', dataType: ValueType.NUMBER },
  ],

  columns: [
    { name: 'seqId', fieldName: 'seqId', width: '80', header: { text: 'SEQ_ID' }, autoFilter: true, numberFormat: '####', styleName: 'tr' },
    { name: '공장코드', fieldName: '공장코드', width: '80', header: { text: '공장코드' }, autoFilter: true, styleName: 'tl' },
    { name: '공정코드', fieldName: '공정코드', width: '80', header: { text: '공정코드' }, autoFilter: true, styleName: 'tl' },
    //{ name: '설비호기', fieldName: '설비호기', width: '80', header: { text: '설비호기' }, autoFilter: true, styleName: 'tl' },
    {
      name: '설비약명',
      fieldName: '설비약명',
      header: { text: '호기' },
      autoFilter: true,
      styleName: 'tl',
    },
    { name: 'runNo', fieldName: 'runNo', width: '150', header: { text: 'RUN_NO' }, autoFilter: true, styleName: 'tl' },
    { name: '근무조', fieldName: '근무조', width: '80', header: { text: '근무조' }, autoFilter: true, styleName: 'tl' },
    { name: '작업자', fieldName: '작업자', width: '80', header: { text: '작업자' }, autoFilter: true, styleName: 'tl' },
    {
      name: 'startTime',
      fieldName: 'startTime',
      width: '120',
      header: { text: '작업시작시간' },
      autoFilter: true,
      styleName: 'tl',
      displayCallback: rgDisplayDateTime,
    },
    {
      name: 'endTime',
      fieldName: 'endTime',
      width: '120',
      header: { text: '작업종료시간' },
      autoFilter: true,
      styleName: 'tl',
      displayCallback: rgDisplayDateTime,
    },
    { name: 'inCstnoL', fieldName: 'inCstnoL', width: '100', header: { text: 'IN_CSTNO_L' }, autoFilter: true, styleName: 'tl' },
    { name: 'inCstnoR', fieldName: 'inCstnoR', width: '100', header: { text: 'IN_CSTNO_R' }, autoFilter: true, styleName: 'tl' },
    { name: 'inCstsu', fieldName: 'inCstsu', width: '80', header: { text: 'IN_CSTSU' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'inCst행열L', fieldName: 'inCst행열L', width: '120', header: { text: 'IN_CST행열_L' }, autoFilter: true, styleName: 'tl' },
    { name: 'inCst행열R', fieldName: 'inCst행열R', width: '120', header: { text: 'IN_CST행열_R' }, autoFilter: true, styleName: 'tl' },
    { name: 'outCstnoL', fieldName: 'outCstnoL', width: '110', header: { text: 'OUT_CSTNO_L' }, autoFilter: true, styleName: 'tl' },
    { name: 'outCstnoR', fieldName: 'outCstnoR', width: '110', header: { text: 'OUT_CSTNO_R' }, autoFilter: true, styleName: 'tl' },
    { name: 'outCstsu', fieldName: 'outCstsu', width: '90', header: { text: 'OUT_CSTSU' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'outCst행열L', fieldName: 'outCst행열L', width: '120', header: { text: 'OUT_CST행열_L' }, autoFilter: true, styleName: 'tl' },
    { name: 'outCst행열R', fieldName: 'outCst행열R', width: '120', header: { text: 'OUT_CST행열_R' }, autoFilter: true, styleName: 'tl' },
    { name: '불량명', fieldName: '불량명', width: '80', header: { text: '불량명' }, autoFilter: true, styleName: 'tl' },
    { name: 'recipeParameter', fieldName: 'recipeParameter', width: '130', header: { text: 'Recipe_Parameter' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '히터온도1조', fieldName: '히터온도1조', width: '100', header: { text: '히터온도_1조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '세척조온도1조', fieldName: '세척조온도1조', width: '120', header: { text: '세척조온도_1조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '히터온도2조', fieldName: '히터온도2조', width: '100', header: { text: '히터온도_2조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '세척조온도2조', fieldName: '세척조온도2조', width: '120', header: { text: '세척조온도_2조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '히터온도3조', fieldName: '히터온도3조', width: '100', header: { text: '히터온도_3조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '세척조온도3조', fieldName: '세척조온도3조', width: '120', header: { text: '세척조온도_3조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '히터온도4조', fieldName: '히터온도4조', width: '100', header: { text: '히터온도_4조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '세척조온도4조', fieldName: '세척조온도4조', width: '120', header: { text: '세척조온도_4조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '히터온도5조', fieldName: '히터온도5조', width: '100', header: { text: '히터온도_5조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '세척조온도5조', fieldName: '세척조온도5조', width: '120', header: { text: '세척조온도_5조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '히터온도6조', fieldName: '히터온도6조', width: '100', header: { text: '히터온도_6조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '세척조온도6조', fieldName: '세척조온도6조', width: '120', header: { text: '세척조온도_6조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '히터온도7조', fieldName: '히터온도7조', width: '100', header: { text: '히터온도_7조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '세척조온도7조', fieldName: '세척조온도7조', width: '120', header: { text: '세척조온도_7조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '히터온도8조', fieldName: '히터온도8조', width: '100', header: { text: '히터온도_8조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '세척조온도8조', fieldName: '세척조온도8조', width: '120', header: { text: '세척조온도_8조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '히터온도9조', fieldName: '히터온도9조', width: '100', header: { text: '히터온도_9조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '세척조온도9조', fieldName: '세척조온도9조', width: '120', header: { text: '세척조온도_9조' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '건조내부온도', fieldName: '건조내부온도', width: '100', header: { text: '건조내부온도' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '건조온도#1', fieldName: '건조온도#1', width: '100', header: { text: '건조온도_#1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '건조온도#2', fieldName: '건조온도#2', width: '100', header: { text: '건조온도_#2' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'spare#1', fieldName: 'spare#1', width: '80', header: { text: 'Spare#1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'spare#2', fieldName: 'spare#2', width: '80', header: { text: 'Spare#2' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'spare#3', fieldName: 'spare#3', width: '80', header: { text: 'Spare#3' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'spare#4', fieldName: 'spare#4', width: '80', header: { text: 'Spare#4' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'spare#5', fieldName: 'spare#5', width: '80', header: { text: 'Spare#5' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
  ],
};

module.exports = grid;
