/*
 * 제조 실적 입력 > Back#2 Cassette QC > 설비 로그 조회
 */
const { ValueType } = require('realgrid');
const { rgDisplayDateTime } = require('@/utils/dateUtils');

const grid = {
  options: {
    checkBar: { visible: false },
    copy: { enabled: true, singleMode: true },
    display: {
      columnMovable: false,
      emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'NONE',
      hscrollBar: true,
      showEmptyMessage: true,
    },
    edit: { editable: false },
    footers: { visible: false },
    paste: { enabled: false },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
    fixed: { colBarWidth: 1, colCount: 5 },
  },

  fields: [
    { fieldName: 'seqId', dataType: ValueType.NUMBER },
    { fieldName: '공장코드', dataType: ValueType.TEXT },
    { fieldName: '가동여부', dataType: ValueType.TEXT },
    { fieldName: '정지사유', dataType: ValueType.TEXT },
    { fieldName: 'runId', dataType: ValueType.TEXT },
    { fieldName: 'startTime', dataType: ValueType.TEXT },
    { fieldName: 'endTime', dataType: ValueType.TEXT },
    { fieldName: '설비호기', dataType: ValueType.TEXT },
    { fieldName: '설비약명', dataType: ValueType.TEXT },
    { fieldName: '근무조', dataType: ValueType.TEXT },
    { fieldName: '작업자', dataType: ValueType.TEXT },
    { fieldName: 'recipeid', dataType: ValueType.TEXT },
    { fieldName: 'cstNo', dataType: ValueType.TEXT },
    { fieldName: 'cstSu', dataType: ValueType.NUMBER },
    { fieldName: 'cst행열', dataType: ValueType.TEXT },
    { fieldName: 'cst행', dataType: ValueType.TEXT },
    { fieldName: 'cst열', dataType: ValueType.TEXT },
    { fieldName: 'cellId', dataType: ValueType.TEXT },
    { fieldName: 'tableNo상', dataType: ValueType.TEXT },
    { fieldName: 'filmId상부', dataType: ValueType.TEXT },
    { fieldName: '상부부착Speed', dataType: ValueType.TEXT },
    { fieldName: '상부부착압력1', dataType: ValueType.NUMBER },
    { fieldName: '상부부착압력2', dataType: ValueType.NUMBER },
    { fieldName: '상부부착압력3', dataType: ValueType.NUMBER },
    { fieldName: '상부롤러정공1', dataType: ValueType.NUMBER },
    { fieldName: '상부롤러정공2', dataType: ValueType.NUMBER },
    { fieldName: '상부롤러정공3', dataType: ValueType.NUMBER },
    { fieldName: '상부부착Tilt각도1', dataType: ValueType.NUMBER },
    { fieldName: '상부부착Gap1', dataType: ValueType.NUMBER },
    { fieldName: '상부filmVaccum압력1', dataType: ValueType.NUMBER },
    { fieldName: '상부utgVaccum압력1', dataType: ValueType.NUMBER },
    { fieldName: 'loadingStgVaccum상', dataType: ValueType.NUMBER },
    { fieldName: '상부PreAlignX', dataType: ValueType.NUMBER },
    { fieldName: '상부PreAlignY', dataType: ValueType.NUMBER },
    { fieldName: '상부PreAlignTh', dataType: ValueType.NUMBER },
    { fieldName: '상부MainAlignX', dataType: ValueType.NUMBER },
    { fieldName: '상부MainAlignY', dataType: ValueType.NUMBER },
    { fieldName: '상부MainAlignTh', dataType: ValueType.NUMBER },
    { fieldName: '상부FilmAlignX', dataType: ValueType.NUMBER },
    { fieldName: '상부FilmAlignY', dataType: ValueType.NUMBER },
    { fieldName: '상부FilmAlignTh', dataType: ValueType.NUMBER },
    { fieldName: '상부Reserve', dataType: ValueType.NUMBER },
    { fieldName: 'tableNo하', dataType: ValueType.TEXT },
    { fieldName: 'filmId하부', dataType: ValueType.TEXT },
    { fieldName: '하부부착Speed', dataType: ValueType.TEXT },
    { fieldName: '하부부착압력1', dataType: ValueType.NUMBER },
    { fieldName: '하부부착압력2', dataType: ValueType.NUMBER },
    { fieldName: '하부부착압력3', dataType: ValueType.NUMBER },
    { fieldName: '하부롤러정공1', dataType: ValueType.NUMBER },
    { fieldName: '하부롤러정공2', dataType: ValueType.NUMBER },
    { fieldName: '하부롤러정공3', dataType: ValueType.NUMBER },
    { fieldName: '하부부착Tilt각도1', dataType: ValueType.NUMBER },
    { fieldName: '하부부착Gap1', dataType: ValueType.NUMBER },
    { fieldName: '하부filmVaccum압력1', dataType: ValueType.NUMBER },
    { fieldName: '하부utgVaccum압력1', dataType: ValueType.NUMBER },
    { fieldName: 'loadingStgVaccum하', dataType: ValueType.NUMBER },
    { fieldName: '하부PreAlignX', dataType: ValueType.NUMBER },
    { fieldName: '하부PreAlignY', dataType: ValueType.NUMBER },
    { fieldName: '하부PreAlignTh', dataType: ValueType.NUMBER },
    { fieldName: '하부MainAlignX', dataType: ValueType.NUMBER },
    { fieldName: '하부MainAlignY', dataType: ValueType.NUMBER },
    { fieldName: '하부MainAlignTh', dataType: ValueType.NUMBER },
    { fieldName: '하부FilmAlignX', dataType: ValueType.NUMBER },
    { fieldName: '하부FilmAlignY', dataType: ValueType.NUMBER },
    { fieldName: '하부FilmAlignTh', dataType: ValueType.NUMBER },
    { fieldName: '하부Reserve', dataType: ValueType.NUMBER },
    { fieldName: 'inspResult', dataType: ValueType.TEXT },
    { fieldName: 'inspData', dataType: ValueType.TEXT },
    { fieldName: 'inspCode', dataType: ValueType.NUMBER },
    { fieldName: 'insp사용미사용', dataType: ValueType.NUMBER },
    { fieldName: 'mcr사용미사용', dataType: ValueType.NUMBER },
    { fieldName: 'mcrReadingId', dataType: ValueType.TEXT },
    { fieldName: 'mcrWrite', dataType: ValueType.TEXT },
    { fieldName: 'trayId', dataType: ValueType.TEXT },
    { fieldName: 'trayPoketNo', dataType: ValueType.NUMBER },
    { fieldName: 'scrap', dataType: ValueType.TEXT },
    { fieldName: 'result', dataType: ValueType.TEXT },
    { fieldName: 'cellDel위치', dataType: ValueType.TEXT },
    { fieldName: 'cellDel사유', dataType: ValueType.TEXT },
    { fieldName: 'portNo', dataType: ValueType.TEXT },
  ],

  columns: [
    { name: 'seqId', fieldName: 'seqId', width: '80', header: { text: 'SEQ_ID' }, autoFilter: true, numberFormat: '####', styleName: 'tr' },
    { name: '공장코드', fieldName: '공장코드', width: '80', header: { text: '공장코드' }, autoFilter: true, styleName: 'tl' },
    { name: '가동여부', fieldName: '가동여부', width: '80', header: { text: '가동여부' }, autoFilter: true, styleName: 'tl' },
    { name: '정지사유', fieldName: '정지사유', width: '80', header: { text: '정지사유' }, autoFilter: true, styleName: 'tl' },
    { name: 'runId', fieldName: 'runId', width: '150', header: { text: 'RUN_ID' }, autoFilter: true, styleName: 'tl' },
    { name: 'startTime', fieldName: 'startTime', width: '120', header: { text: 'Start_time' }, autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime },
    { name: 'endTime', fieldName: 'endTime', width: '120', header: { text: 'End_time' }, autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime },
    { name: '설비호기', fieldName: '설비호기', width: '80', header: { text: '설비호기' }, autoFilter: true, styleName: 'tl' },
    {
      name: '설비약명',
      fieldName: '설비약명',
      header: { text: '호기' },
      autoFilter: true,
      styleName: 'tl',
    },
    { name: '근무조', fieldName: '근무조', width: '80', header: { text: '근무조' }, autoFilter: true, styleName: 'tl' },
    { name: '작업자', fieldName: '작업자', width: '80', header: { text: '작업자' }, autoFilter: true, styleName: 'tl' },
    { name: 'recipeid', fieldName: 'recipeid', width: '80', header: { text: 'RecipeID' }, autoFilter: true, styleName: 'tl' },
    { name: 'cstNo', fieldName: 'cstNo', width: '80', header: { text: 'CST_NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cstSu', fieldName: 'cstSu', width: '80', header: { text: 'CST_SU' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'cst행열', fieldName: 'cst행열', width: '80', header: { text: 'CST_행열' }, autoFilter: true, styleName: 'tl' },
    { name: 'cst행', fieldName: 'cst행', width: '80', header: { text: 'CST_행' }, autoFilter: true, styleName: 'tl' },
    { name: 'cst열', fieldName: 'cst열', width: '80', header: { text: 'CST_열' }, autoFilter: true, styleName: 'tl' },
    { name: 'cellId', fieldName: 'cellId', width: '220', header: { text: 'CELL_ID' }, autoFilter: true, styleName: 'tl' },
    { name: 'tableNo상', fieldName: 'tableNo상', width: '110', header: { text: 'TABLE_NO상' }, autoFilter: true, styleName: 'tl' },
    { name: 'filmId상부', fieldName: 'filmId상부', width: '250', header: { text: 'Film_ID_상부' }, autoFilter: true, styleName: 'tl' },
    { name: '상부부착Speed', fieldName: '상부부착Speed', width: '130', header: { text: '상부부착_SPEED' }, autoFilter: true, styleName: 'tl' },
    { name: '상부부착압력1', fieldName: '상부부착압력1', width: '130', header: { text: '상부부착_압력1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부부착압력2', fieldName: '상부부착압력2', width: '130', header: { text: '상부부착_압력2' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부부착압력3', fieldName: '상부부착압력3', width: '130', header: { text: '상부부착_압력3' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부롤러정공1', fieldName: '상부롤러정공1', width: '130', header: { text: '상부롤러_정공1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부롤러정공2', fieldName: '상부롤러정공2', width: '130', header: { text: '상부롤러_정공2' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부롤러정공3', fieldName: '상부롤러정공3', width: '130', header: { text: '상부롤러_정공3' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부부착Tilt각도1', fieldName: '상부부착Tilt각도1', width: '160', header: { text: '상부부착_Tilt_각도1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부부착Gap1', fieldName: '상부부착Gap1', width: '130', header: { text: '상부부착_Gap1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부filmVaccum압력1', fieldName: '상부filmVaccum압력1', width: '160', header: { text: '상부Film_Vaccum_압력1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부utgVaccum압력1', fieldName: '상부utgVaccum압력1', width: '160', header: { text: '상부UTG_Vaccum_압력1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'loadingStgVaccum상', fieldName: 'loadingStgVaccum상', width: '180', header: { text: 'Loading_STG_Vaccum_상' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부PreAlignX', fieldName: '상부PreAlignX', width: '130', header: { text: '상부_Pre_Align_X' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부PreAlignY', fieldName: '상부PreAlignY', width: '130', header: { text: '상부_Pre_Align_Y' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부PreAlignTh', fieldName: '상부PreAlignTh', width: '130', header: { text: '상부_Pre_Align_TH' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부MainAlignX', fieldName: '상부MainAlignX', width: '140', header: { text: '상부_Main_Align_X' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부MainAlignY', fieldName: '상부MainAlignY', width: '140', header: { text: '상부_Main_Align_Y' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부MainAlignTh', fieldName: '상부MainAlignTh', width: '140', header: { text: '상부_Main_Align_TH' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부FilmAlignX', fieldName: '상부FilmAlignX', width: '130', header: { text: '상부_Film_Align_X' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부FilmAlignY', fieldName: '상부FilmAlignY', width: '130', header: { text: '상부_Film_Align_Y' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부FilmAlignTh', fieldName: '상부FilmAlignTh', width: '140', header: { text: '상부_Film_Align_TH' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '상부Reserve', fieldName: '상부Reserve', width: '110', header: { text: '상부_Reserve' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'tableNo하', fieldName: 'tableNo하', width: '100', header: { text: 'TABLE_NO하' }, autoFilter: true, styleName: 'tl' },
    { name: 'filmId하부', fieldName: 'filmId하부', width: '250', header: { text: 'Film_ID_하부' }, autoFilter: true, styleName: 'tl' },
    { name: '하부부착Speed', fieldName: '하부부착Speed', width: '120', header: { text: '하부부착_SPEED' }, autoFilter: true, styleName: 'tl' },
    { name: '하부부착압력1', fieldName: '하부부착압력1', width: '120', header: { text: '하부부착_압력1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부부착압력2', fieldName: '하부부착압력2', width: '120', header: { text: '하부부착_압력2' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부부착압력3', fieldName: '하부부착압력3', width: '120', header: { text: '하부부착_압력3' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부롤러정공1', fieldName: '하부롤러정공1', width: '120', header: { text: '하부롤러_정공1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부롤러정공2', fieldName: '하부롤러정공2', width: '120', header: { text: '하부롤러_정공2' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부롤러정공3', fieldName: '하부롤러정공3', width: '120', header: { text: '하부롤러_정공3' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부부착Tilt각도1', fieldName: '하부부착Tilt각도1', width: '160', header: { text: '하부부착_Tilt_각도1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부부착Gap1', fieldName: '하부부착Gap1', width: '130', header: { text: '하부부착_Gap1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부filmVaccum압력1', fieldName: '하부filmVaccum압력1', width: '160', header: { text: '하부Film_Vaccum_압력1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부utgVaccum압력1', fieldName: '하부utgVaccum압력1', width: '160', header: { text: '하부UTG_Vaccum_압력1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'loadingStgVaccum하', fieldName: 'loadingStgVaccum하', width: '180', header: { text: 'Loading_STG_Vaccum_하' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부PreAlignX', fieldName: '하부PreAlignX', width: '130', header: { text: '하부_Pre_Align_X' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부PreAlignY', fieldName: '하부PreAlignY', width: '130', header: { text: '하부_Pre_Align_Y' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부PreAlignTh', fieldName: '하부PreAlignTh', width: '130', header: { text: '하부_Pre_Align_TH' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부MainAlignX', fieldName: '하부MainAlignX', width: '140', header: { text: '하부_Main_Align_X' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부MainAlignY', fieldName: '하부MainAlignY', width: '140', header: { text: '하부_Main_Align_Y' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부MainAlignTh', fieldName: '하부MainAlignTh', width: '140', header: { text: '하부_Main_Align_TH' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부FilmAlignX', fieldName: '하부FilmAlignX', width: '130', header: { text: '하부_Film_Align_X' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부FilmAlignY', fieldName: '하부FilmAlignY', width: '130', header: { text: '하부_Film_Align_Y' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부FilmAlignTh', fieldName: '하부FilmAlignTh', width: '140', header: { text: '하부_Film_Align_TH' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '하부Reserve', fieldName: '하부Reserve', width: '110', header: { text: '하부_Reserve' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'inspResult', fieldName: 'inspResult', width: '100', header: { text: 'Insp_Result' }, autoFilter: true, styleName: 'tl' },
    { name: 'inspData', fieldName: 'inspData', width: '200', header: { text: 'Insp_DATA' }, autoFilter: true, styleName: 'tl' },
    { name: 'inspCode', fieldName: 'inspCode', width: '80', header: { text: 'Insp_Code' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'insp사용미사용', fieldName: 'insp사용미사용', width: '130', header: { text: 'INSP_사용_미사용' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'mcr사용미사용', fieldName: 'mcr사용미사용', width: '130', header: { text: 'MCR_사용_미사용' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'mcrReadingId', fieldName: 'mcrReadingId', width: '250', header: { text: 'MCR_reading_ID' }, autoFilter: true, styleName: 'tl' },
    { name: 'mcrWrite', fieldName: 'mcrWrite', width: '300', header: { text: 'MCR_Write' }, autoFilter: true, styleName: 'tl' },
    { name: 'trayId', fieldName: 'trayId', width: '150', header: { text: 'Tray_ID' }, autoFilter: true, styleName: 'tl' },
    { name: 'trayPoketNo', fieldName: 'trayPoketNo', width: '120', header: { text: 'Tray_Poket_No' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'scrap', fieldName: 'scrap', width: '80', header: { text: 'SCRAP' }, autoFilter: true, styleName: 'tl' },
    { name: 'result', fieldName: 'result', width: '80', header: { text: 'RESULT' }, autoFilter: true, styleName: 'tl' },
    { name: 'cellDel위치', fieldName: 'cellDel위치', width: '110', header: { text: 'CELL_DEL위치' }, autoFilter: true, styleName: 'tl' },
    { name: 'cellDel사유', fieldName: 'cellDel사유', width: '110', header: { text: 'CELL_DEL사유' }, autoFilter: true, styleName: 'tl' },
    { name: 'portNo', fieldName: 'portNo', width: '80', header: { text: 'PORT_NO' }, autoFilter: true, styleName: 'tl' },
  ],
};

module.exports = grid;
