/*
 * 제조 실적 입력 > Back#2 Cassette QC > 설비 로그 조회
 */
const { ValueType } = require('realgrid');
const { rgDisplayDateTime } = require('@/utils/dateUtils');

const grid = {
  options: {
    checkBar: { visible: true },
    copy: { enabled: true, singleMode: true },
    display: {
      columnMovable: false,
      emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'NONE',
      hscrollBar: true,
      showEmptyMessage: true,
    },
    hideDeletedRows: true,
    edit: { editable: false, columnEditableFirst: true, commitByCell: true, commitWhenLeave: true },
    footers: { visible: false },
    paste: { enabled: true, checkReadOnly: true, commitEdit: true, enableAppend: false, selectBlockPaste: true },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
    fixed: { colBarWidth: 1, colCount: 8 },
  },

  fields: [
    { fieldName: 'seqId', dataType: ValueType.NUMBER },
    { fieldName: '공장코드', dataType: ValueType.TEXT },
    { fieldName: '공정코드', dataType: ValueType.TEXT },
    { fieldName: '시작시간', dataType: ValueType.TEXT },
    { fieldName: '종료시간', dataType: ValueType.TEXT },
    { fieldName: '설비호기', dataType: ValueType.TEXT },
    { fieldName: '설비약명', dataType: ValueType.TEXT },
    { fieldName: 'runNo', dataType: ValueType.TEXT },
    { fieldName: 'incstNo', dataType: ValueType.TEXT },
    { fieldName: 'incstSu', dataType: ValueType.NUMBER },
    { fieldName: 'incst행열', dataType: ValueType.TEXT },
    { fieldName: 'cellId', dataType: ValueType.TEXT },
    { fieldName: 'result', dataType: ValueType.TEXT },
    { fieldName: 'scrap', dataType: ValueType.TEXT },
    { fieldName: 'pointX', dataType: ValueType.TEXT },
    { fieldName: 'pointY', dataType: ValueType.TEXT },
    { fieldName: 'outcstNo', dataType: ValueType.TEXT },
    { fieldName: 'outcstSu', dataType: ValueType.NUMBER },
    { fieldName: 'outcst행열', dataType: ValueType.TEXT },
    { fieldName: '설비구간', dataType: ValueType.TEXT },
    { fieldName: '설비stage', dataType: ValueType.TEXT },
    { fieldName: 'scrap유형', dataType: ValueType.TEXT },
    { fieldName: '근무조', dataType: ValueType.TEXT },
    { fieldName: '검사원', dataType: ValueType.TEXT },
    { fieldName: '검사원사번', dataType: ValueType.TEXT },
    { fieldName: '물류작업자', dataType: ValueType.TEXT },
  ],

  columns: [
    { name: 'seqId', fieldName: 'seqId', width: '80', header: { text: 'SEQ_ID' }, autoFilter: true, numberFormat: '####', styleName: 'tr' },
    { name: '공장코드', fieldName: '공장코드', width: '80', header: { text: '공장코드' }, autoFilter: true, styleName: 'tl' },
    { name: '공정코드', fieldName: '공정코드', width: '80', header: { text: '공정코드' }, autoFilter: true, styleName: 'tl' },
    { name: '시작시간', fieldName: '시작시간', width: '120', header: { text: '시작시간' }, autoFilter: true, styleName: 'edit tl', editable: true, displayCallback: rgDisplayDateTime },
    { name: '종료시간', fieldName: '종료시간', width: '120', header: { text: '종료시간' }, autoFilter: true, styleName: 'edit tl', editable: true, displayCallback: rgDisplayDateTime },
    { name: '설비호기', fieldName: '설비호기', width: '80', header: { text: '설비호기' }, autoFilter: true, styleName: 'edit tl', editable: true },
    {
      name: '설비약명',
      fieldName: '설비약명',
      header: { text: '호기' },
      autoFilter: true,
      styleName: 'tl',
    },
    { name: 'runNo', fieldName: 'runNo', width: '150', header: { text: 'RUN_NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'incstNo', fieldName: 'incstNo', width: '80', header: { text: 'INCST_NO' }, autoFilter: true, styleName: 'edit tl', editable: true },
    { name: 'incstSu', fieldName: 'incstSu', width: '80', header: { text: 'INCST_SU' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'incst행열', fieldName: 'incst행열', width: '100', header: { text: 'INCST_행열' }, autoFilter: true, styleName: 'tl' },
    { name: 'cellId', fieldName: 'cellId', width: '110', header: { text: 'CELL_ID' }, autoFilter: true, styleName: 'tl' },
    { name: 'result', fieldName: 'result', width: '80', header: { text: 'RESULT' }, autoFilter: true, styleName: 'edit tl', editable: true },
    { name: 'scrap', fieldName: 'scrap', width: '80', header: { text: 'SCRAP' }, autoFilter: true, styleName: 'edit tl', editable: true },
    { name: 'pointX', fieldName: 'pointX', width: '80', header: { text: 'POINT_X' }, autoFilter: true, styleName: 'tl' },
    { name: 'pointY', fieldName: 'pointY', width: '80', header: { text: 'POINT_Y' }, autoFilter: true, styleName: 'tl' },
    { name: 'outcstNo', fieldName: 'outcstNo', width: '100', header: { text: 'OUTCST_NO' }, autoFilter: true, styleName: 'edit tl', editable: true },
    { name: 'outcstSu', fieldName: 'outcstSu', width: '90', header: { text: 'OUTCST_SU' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'outcst행열', fieldName: 'outcst행열', width: '110', header: { text: 'OUTCST_행열' }, autoFilter: true, styleName: 'tl' },
    { name: '설비구간', fieldName: '설비구간', width: '80', header: { text: '설비구간' }, autoFilter: true, styleName: 'tl' },
    { name: '설비stage', fieldName: '설비stage', width: '90', header: { text: '설비Stage' }, autoFilter: true, styleName: 'tl' },
    { name: 'scrap유형', fieldName: 'scrap유형', width: '90', header: { text: 'SCRAP유형' }, autoFilter: true, styleName: 'tl' },
    { name: '근무조', fieldName: '근무조', width: '80', header: { text: '근무조' }, autoFilter: true, styleName: 'edit tl', editable: true },
    { name: '검사원', fieldName: '검사원', width: '80', header: { text: '검사원' }, autoFilter: true, styleName: 'tl' },
    { name: '검사원사번', fieldName: '검사원사번', width: '100', header: { text: '검사원사번' }, autoFilter: true, styleName: 'tl' },
    { name: '물류작업자', fieldName: '물류작업자', width: '100', header: { text: '물류작업자' }, autoFilter: true, styleName: 'tl' },
  ],
};

module.exports = grid;
