/*
 * 제조 실적 입력 > Back#2 Cell QC > 설비 로그 조회
 */
const { ValueType } = require('realgrid');

const grid = {
  options: {
    checkBar: { visible: false },
    copy: { enabled: true, singleMode: true },
    display: {
      columnMovable: false,
      emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'NONE',
      hscrollBar: true,
      showEmptyMessage: true,
    },
    edit: { editable: false },
    footers: { visible: false },
    paste: { enabled: false },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
    fixed: { colBarWidth: 1, colCount: 6 },
  },

  fields: [
    { fieldName: 'seqNo', dataType: ValueType.NUMBER },
    { fieldName: 'eqpId', dataType: ValueType.TEXT },
    { fieldName: '설비약명', dataType: ValueType.TEXT },
    { fieldName: 'uniqueId', dataType: ValueType.TEXT },
    { fieldName: 'cellId', dataType: ValueType.TEXT },
    { fieldName: 'runNo', dataType: ValueType.TEXT },
    { fieldName: 'productCode', dataType: ValueType.TEXT },
    { fieldName: 'agbCode', dataType: ValueType.TEXT },
    { fieldName: 'ismCode', dataType: ValueType.TEXT },
    { fieldName: 'pflMachineCode', dataType: ValueType.TEXT },
    { fieldName: 'pflStage', dataType: ValueType.TEXT },
    { fieldName: 'sviMachineCode', dataType: ValueType.TEXT },
    { fieldName: 'sviResultCode', dataType: ValueType.TEXT },
    { fieldName: 'vaildation', dataType: ValueType.NUMBER },
    { fieldName: 'reasonCode', dataType: ValueType.NUMBER },
    { fieldName: 'description', dataType: ValueType.TEXT },
    { fieldName: 'isScrap', dataType: ValueType.TEXT },
    { fieldName: 'prevSeqNo', dataType: ValueType.NUMBER },
    { fieldName: 'operName', dataType: ValueType.TEXT },
    { fieldName: 'operTeam', dataType: ValueType.TEXT },
    { fieldName: 'regDate', dataType: ValueType.TEXT },
    { fieldName: 'updDate', dataType: ValueType.TEXT },
    { fieldName: 'convertRegDate', dataType: ValueType.TEXT },
    { fieldName: 'convertRegTime', dataType: ValueType.TEXT },
    { fieldName: 'convertUpdDate', dataType: ValueType.TEXT },
    { fieldName: 'convertUpdTime', dataType: ValueType.TEXT },
    { fieldName: 'scrap', dataType: ValueType.TEXT },
    { fieldName: 'remark', dataType: ValueType.TEXT },
  ],

  columns: [
    { name: 'seqNo', fieldName: 'seqNo', width: '90', header: { text: 'SEQ_NO' }, autoFilter: true, numberFormat: '####', styleName: 'tr' },
    { name: 'eqpId', fieldName: 'eqpId', width: '80', header: { text: 'EQP_ID' }, autoFilter: true, styleName: 'tl' },
    {
      name: '설비약명',
      fieldName: '설비약명',
      header: { text: '호기' },
      autoFilter: true,
      styleName: 'tl',
    },
    { name: 'uniqueId', fieldName: 'uniqueId', width: '300', header: { text: 'UNIQUE_ID' }, autoFilter: true, styleName: 'tl' },
    { name: 'cellId', fieldName: 'cellId', width: '260', header: { text: 'CELL No.' }, autoFilter: true, styleName: 'tl' },
    { name: 'runNo', fieldName: 'runNo', width: '150', header: { text: 'RUN No.' }, autoFilter: true, styleName: 'tl' },
    { name: 'productCode', fieldName: 'productCode', width: '130', header: { text: 'PRODUCT_CODE' }, autoFilter: true, styleName: 'tl' },
    { name: 'agbCode', fieldName: 'agbCode', width: '110', header: { text: 'AGB_CODE' }, autoFilter: true, styleName: 'tl' },
    { name: 'ismCode', fieldName: 'ismCode', width: '110', header: { text: 'ISM_CODE' }, autoFilter: true, styleName: 'tl' },
    { name: 'pflMachineCode', fieldName: 'pflMachineCode', width: '180', header: { text: 'PFL_MACHINE_CODE' }, autoFilter: true, styleName: 'tl' },
    { name: 'pflStage', fieldName: 'pflStage', width: '110', header: { text: 'PFL_STAGE' }, autoFilter: true, styleName: 'tl' },
    { name: 'sviMachineCode', fieldName: 'sviMachineCode', width: '180', header: { text: 'SVI_MACHINE_CODE' }, autoFilter: true, styleName: 'tl' },
    { name: 'sviResultCode', fieldName: 'sviResultCode', width: '170', header: { text: 'SVI_RESULT_CODE' }, autoFilter: true, styleName: 'tl' },
    { name: 'vaildation', fieldName: 'vaildation', width: '120', header: { text: 'VAILDATION' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'reasonCode', fieldName: 'reasonCode', width: '130', header: { text: 'REASON_CODE' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'description', fieldName: 'description', width: '240', header: { text: 'DESCRIPTION' }, autoFilter: true, styleName: 'tl' },
    { name: 'isScrap', fieldName: 'isScrap', width: '100', header: { text: 'IS_SCRAP' }, autoFilter: true, styleName: 'tl' },
    { name: 'prevSeqNo', fieldName: 'prevSeqNo', width: '130', header: { text: 'PREV_SEQ_NO' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'operName', fieldName: 'operName', width: '120', header: { text: 'OPER_NAME' }, autoFilter: true, styleName: 'tl' },
    { name: 'operTeam', fieldName: 'operTeam', width: '120', header: { text: 'OPER_TEAM' }, autoFilter: true, styleName: 'tl' },
    { name: 'convertRegDate', fieldName: 'convertRegDate', width: '110', header: { text: 'REG_DATE' }, autoFilter: true, styleName: 'tl' },
    { name: 'convertRegTime', fieldName: 'convertRegTime', width: '110', header: { text: 'REG_TIME' }, autoFilter: true, styleName: 'tl' },
    { name: 'convertUpdDate', fieldName: 'convertUpdDate', width: '110', header: { text: 'UPD_DATE' }, autoFilter: true, styleName: 'tl' },
    { name: 'convertUpdTime', fieldName: 'convertUpdTime', width: '110', header: { text: 'UPD_TIME' }, autoFilter: true, styleName: 'tl' },
    { name: 'scrap', fieldName: 'scrap', width: '100', header: { text: 'SCRAP' }, autoFilter: true, styleName: 'tl' },
    { name: 'remark', fieldName: 'remark', width: '120', header: { text: 'Remark' }, autoFilter: true, styleName: 'tl' },
  ],
};

module.exports = grid;
