/*
 * 제조 실적 입력 > FRONT > 설비 로그 조회
 */
const { ValueType } = require('realgrid');
const { rgDisplayDateTime } = require('@/utils/dateUtils');

const grid = {
  options: {
    checkBar: { visible: false },
    copy: { enabled: true, singleMode: true },
    display: {
      columnMovable: false,
      emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'NONE',
      hscrollBar: true,
      showEmptyMessage: true,
    },
    edit: { editable: false },
    footers: { visible: false },
    paste: { enabled: false },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
    fixed: { colBarWidth: 1, colCount: 8 },
  },

  fields: [
    { fieldName: 'seqId', dataType: ValueType.NUMBER },
    { fieldName: '공장코드', dataType: ValueType.TEXT },
    { fieldName: '설비약명', dataType: ValueType.TEXT },
    { fieldName: '근무조', dataType: ValueType.TEXT },
    { fieldName: '작업자', dataType: ValueType.TEXT },
    { fieldName: 'startTime', dataType: ValueType.TEXT },
    { fieldName: 'endTime', dataType: ValueType.TEXT },
    { fieldName: 'panelId', dataType: ValueType.TEXT },
    { fieldName: 'lotNo', dataType: ValueType.TEXT },
    { fieldName: 'boxNo', dataType: ValueType.TEXT },
    { fieldName: 'glassId', dataType: ValueType.TEXT },
    { fieldName: '층수No', dataType: ValueType.NUMBER },
    { fieldName: 'resinId', dataType: ValueType.TEXT },
    { fieldName: 'resinTankno', dataType: ValueType.TEXT },
    { fieldName: 'resin제조일자', dataType: ValueType.TEXT },
    { fieldName: 'resin구분', dataType: ValueType.TEXT },
    { fieldName: 'stgLoad', dataType: ValueType.NUMBER },
    { fieldName: 'pinLoad', dataType: ValueType.NUMBER },
    { fieldName: '부착Speed', dataType: ValueType.NUMBER },
    { fieldName: '부착압력1', dataType: ValueType.NUMBER },
    { fieldName: '상부MainAlignX', dataType: ValueType.NUMBER },
    { fieldName: '상부MainAlignY', dataType: ValueType.NUMBER },
    { fieldName: '상부MainAlignTh', dataType: ValueType.NUMBER },
    { fieldName: 'stageAlignX', dataType: ValueType.NUMBER },
    { fieldName: 'stageAlignY', dataType: ValueType.NUMBER },
    { fieldName: '합착StageAlignX2', dataType: ValueType.NUMBER },
    { fieldName: '합착StageAlignY2', dataType: ValueType.NUMBER },
    { fieldName: 'coverGlassAlignX', dataType: ValueType.NUMBER },
    { fieldName: 'coverGlassAlignY', dataType: ValueType.NUMBER },
    { fieldName: '합착CgAlignX2', dataType: ValueType.NUMBER },
    { fieldName: '합착CgAlignY2', dataType: ValueType.NUMBER },
    { fieldName: '합착InspectResult', dataType: ValueType.TEXT },
    { fieldName: 'scrapPosition', dataType: ValueType.TEXT },
    { fieldName: 'lamiStageLoad', dataType: ValueType.NUMBER },
    { fieldName: 'lamiStagePinLoad', dataType: ValueType.NUMBER },
    { fieldName: 'uvStageLoad', dataType: ValueType.NUMBER },
    { fieldName: 'uvStagePinLoad', dataType: ValueType.NUMBER },
    { fieldName: '검사StageLoad', dataType: ValueType.NUMBER },
    { fieldName: '검사StagePinLoad', dataType: ValueType.NUMBER },
    { fieldName: '부착압력LeftStart', dataType: ValueType.NUMBER },
    { fieldName: '부착압력LeftMiddle', dataType: ValueType.NUMBER },
    { fieldName: '부착압력LeftEnd', dataType: ValueType.NUMBER },
    { fieldName: '부착압력RightStart', dataType: ValueType.NUMBER },
    { fieldName: '부착압력RightMiddle', dataType: ValueType.NUMBER },
    { fieldName: '부착압력RightEnd', dataType: ValueType.NUMBER },
  ],

  columns: [
    {
      name: 'seqId',
      fieldName: 'seqId',
      header: { text: 'SEQ_ID' },
      width: '80',
      autoFilter: true,
      numberFormat: '####',
      styleName: 'tr',
    },
    { name: '공장코드', fieldName: '공장코드', header: { text: '공장코드' }, width: '80', autoFilter: true, styleName: 'tl' },
    {
      name: '설비약명',
      fieldName: '설비약명',
      header: { text: '호기' },
      width: '60',
      autoFilter: true,
      styleName: 'tl',
    },
    { name: '근무조', fieldName: '근무조', header: { text: '근무조' }, width: '70', autoFilter: true, styleName: 'tl' },
    { name: '작업자', fieldName: '작업자', header: { text: '작업자' }, width: '70', autoFilter: true, styleName: 'tl' },
    {
      name: 'startTime',
      fieldName: 'startTime',
      width: '120',
      header: { text: '작업시작시간' },
      autoFilter: true,
      styleName: 'tl',
      displayCallback: rgDisplayDateTime,
    },
    {
      name: 'endTime',
      fieldName: 'endTime',
      width: '120',
      header: { text: '작업종료시간' },
      autoFilter: true,
      styleName: 'tl',
      displayCallback: rgDisplayDateTime,
    },
    {
      name: 'panelId',
      fieldName: 'panelId',
      header: { text: 'PANEL_ID' },
      autoFilter: true,
      width: 210,
      styleName: 'tl',
    },
    {
      name: 'lotNo',
      fieldName: 'lotNo',
      header: { text: 'LOT_NO' },
      width: 150,
      autoFilter: true,
      styleName: 'tl',
    },
    {
      name: 'boxNo',
      fieldName: 'boxNo',
      header: { text: 'BOX_NO' },
      width: 100,
      autoFilter: true,
      styleName: 'tl',
    },
    {
      name: 'glassId',
      fieldName: 'glassId',
      header: { text: 'GLASS_ID' },
      width: 230,
      autoFilter: true,
      styleName: 'tl',
    },
    {
      name: '층수No',
      fieldName: '층수No',
      header: { text: '층수_No' },
      width: '90',
      numberFormat: '#,###.####',
      autoFilter: true,
      styleName: 'tr',
    },
    {
      name: 'resinId',
      fieldName: 'resinId',
      header: { text: 'RESIN_ID' },
      width: 160,
      autoFilter: true,
      styleName: 'tl',
    },
    {
      name: 'resinTankno',
      fieldName: 'resinTankno',
      header: { text: 'RESIN TANKNO' },
      width: '120',
      autoFilter: true,
      styleName: 'tl',
    },
    {
      name: 'resin제조일자',
      fieldName: 'resin제조일자',
      header: { text: 'RESIN제조일자' },
      width: '120',
      autoFilter: true,
      styleName: 'tl',
    },
    {
      name: 'resin구분',
      fieldName: 'resin구분',
      header: { text: 'RESIN구분' },
      width: '90',
      autoFilter: true,
      styleName: 'tl',
    },
    {
      name: 'stgLoad',
      fieldName: 'stgLoad',
      header: { text: 'STG_Load' },
      width: '80',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: 'pinLoad',
      fieldName: 'pinLoad',
      header: { text: 'Pin_Load' },
      width: '80',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '부착Speed',
      fieldName: '부착Speed',
      header: { text: '부착_SPEED' },
      width: '90',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '부착압력1',
      fieldName: '부착압력1',
      header: { text: '부착_압력1' },
      width: '90',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '상부MainAlignX',
      fieldName: '상부MainAlignX',
      header: { text: '상부_Main_Align_X' },
      width: '150',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '상부MainAlignY',
      fieldName: '상부MainAlignY',
      header: { text: '상부_Main_Align_Y' },
      width: '150',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '상부MainAlignTh',
      fieldName: '상부MainAlignTh',
      header: { text: '상부_Main_Align_TH' },
      width: '150',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: 'stageAlignX',
      fieldName: 'stageAlignX',
      header: { text: 'Stage_Align_X' },
      width: '100',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: 'stageAlignY',
      fieldName: 'stageAlignY',
      header: { text: 'Stage_Align_Y' },
      width: '100',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '합착StageAlignX2',
      fieldName: '합착StageAlignX2',
      header: { text: '합착_STAGE_ALIGN_X2' },
      width: '160',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '합착StageAlignY2',
      fieldName: '합착StageAlignY2',
      header: { text: '합착_STAGE_ALIGN_Y2' },
      width: '160',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: 'coverGlassAlignX',
      fieldName: 'coverGlassAlignX',
      header: { text: 'Cover_Glass_Align_X' },
      width: '140',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: 'coverGlassAlignY',
      fieldName: 'coverGlassAlignY',
      header: { text: 'Cover_Glass_Align_Y' },
      width: '140',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '합착CgAlignX2',
      fieldName: '합착CgAlignX2',
      header: { text: '합착_CG_ALIGN_X2' },
      width: '140',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '합착CgAlignY2',
      fieldName: '합착CgAlignY2',
      header: { text: '합착_CG_ALIGN_Y2' },
      width: '140',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '합착InspectResult',
      fieldName: '합착InspectResult',
      header: { text: '합착_INSPECT_RESULT' },
      width: '160',
      autoFilter: true,
      styleName: 'tl',
    },
    {
      name: 'scrapPosition',
      fieldName: 'scrapPosition',
      header: { text: 'SCRAP_POSITION' },
      width: '120',
      autoFilter: true,
      styleName: 'tl',
    },
    {
      name: 'lamiStageLoad',
      fieldName: 'lamiStageLoad',
      header: { text: 'LAMI_STAGE_LOAD' },
      width: '140',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: 'lamiStagePinLoad',
      fieldName: 'lamiStagePinLoad',
      header: { text: 'LAMI_STAGE_PIN_LOAD' },
      width: '160',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: 'uvStageLoad',
      fieldName: 'uvStageLoad',
      header: { text: 'UV_STAGE_LOAD' },
      width: '140',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: 'uvStagePinLoad',
      fieldName: 'uvStagePinLoad',
      header: { text: 'UV_STAGE_PIN_LOAD' },
      width: '160',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '검사StageLoad',
      fieldName: '검사StageLoad',
      header: { text: '검사_STAGE_LOAD' },
      width: '160',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '검사StagePinLoad',
      fieldName: '검사StagePinLoad',
      header: { text: '검사_STAGE_PIN_LOAD' },
      width: '160',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '부착압력LeftStart',
      fieldName: '부착압력LeftStart',
      header: { text: '부착압력_LEFT_START' },
      width: '160',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '부착압력LeftMiddle',
      fieldName: '부착압력LeftMiddle',
      header: { text: '부착압력_LEFT_MIDDLE' },
      width: '160',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '부착압력LeftEnd',
      fieldName: '부착압력LeftEnd',
      header: { text: '부착압력_LEFT_END' },
      width: '160',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '부착압력RightStart',
      fieldName: '부착압력RightStart',
      header: { text: '부착압력_RIGHT_START' },
      width: '160',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
    {
      name: '부착압력RightMiddle',
      fieldName: '부착압력RightMiddle',
      header: { text: '부착압력_RIGHT_MIDDLE' },
      width: '170',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },

    {
      name: '부착압력RightEnd',
      fieldName: '부착압력RightEnd',
      header: { text: '부착압력_RIGHT_END' },
      width: '160',
      autoFilter: true,
      numberFormat: '#,###.####',
      styleName: 'tr',
    },
  ],
};

module.exports = grid;
