/*
 * 제조 실적 입력 > Back#2 Cell QC > 설비 로그 조회
 */
const { ValueType } = require('realgrid');

const grid = {
  options: {
    checkBar: { visible: false },
    copy: { enabled: true, singleMode: true },
    display: {
      columnMovable: false,
      emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'NONE',
      hscrollBar: true,
      showEmptyMessage: true,
    },
    edit: { editable: false },
    footers: { visible: false },
    paste: { enabled: false },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
    fixed: { colBarWidth: 1, colCount: 7 },
  },

  fields: [
    { fieldName: 'seqNo', dataType: ValueType.NUMBER },
    { fieldName: 'eqpId', dataType: ValueType.TEXT },
    { fieldName: '설비약명', dataType: ValueType.TEXT },
    { fieldName: 'uniqueId', dataType: ValueType.TEXT },
    { fieldName: 'vaildinfoSeq', dataType: ValueType.NUMBER },
    { fieldName: 'cellId', dataType: ValueType.TEXT },
    { fieldName: 'runNo', dataType: ValueType.TEXT },
    { fieldName: 'crackResult', dataType: ValueType.TEXT },
    { fieldName: 'tabResult', dataType: ValueType.TEXT },
    { fieldName: 'isScrap', dataType: ValueType.TEXT },
    { fieldName: 'operName', dataType: ValueType.TEXT },
    { fieldName: 'operTeam', dataType: ValueType.TEXT },
    { fieldName: 'prevSeqNo', dataType: ValueType.NUMBER },
    { fieldName: 'regDate', dataType: ValueType.TEXT },
    { fieldName: 'updDate', dataType: ValueType.TEXT },
    { fieldName: 'convertRegDate', dataType: ValueType.TEXT },
    { fieldName: 'convertRegTime', dataType: ValueType.TEXT },
    { fieldName: 'convertUpdDate', dataType: ValueType.TEXT },
    { fieldName: 'convertUpdTime', dataType: ValueType.TEXT },
    { fieldName: 'scrap', dataType: ValueType.TEXT },
    { fieldName: 'remark', dataType: ValueType.TEXT },
    { fieldName: 'packNo', dataType: ValueType.TEXT },
    { fieldName: 'pack상태', dataType: ValueType.TEXT },
    { fieldName: '폐기사유', dataType: ValueType.TEXT },
    { fieldName: '폐기시각', dataType: ValueType.TEXT },
    { fieldName: '샘플의뢰여부', dataType: ValueType.NUMBER },
    { fieldName: '샘플Result', dataType: ValueType.TEXT },
    { fieldName: '재공적용여부', dataType: ValueType.NUMBER },
  ],

  columns: [
    { name: 'seqNo', fieldName: 'seqNo', width: '90', header: { text: 'SEQ_NO' }, autoFilter: true, numberFormat: '####', styleName: 'tr' },
    { name: 'eqpId', fieldName: 'eqpId', width: '80', header: { text: 'EQP_ID' }, autoFilter: true, styleName: 'tl' },
    {
      name: '설비약명',
      fieldName: '설비약명',
      header: { text: '호기' },
      autoFilter: true,
      styleName: 'tl',
    },
    { name: 'uniqueId', fieldName: 'uniqueId', width: '300', header: { text: 'UNIQUE_ID' }, autoFilter: true, styleName: 'tl' },
    { name: 'vaildinfoSeq', fieldName: 'vaildinfoSeq', width: '150', header: { text: 'VAILDINFO_SEQ' }, autoFilter: true, numberFormat: '####', styleName: 'tr' },
    { name: 'cellId', fieldName: 'cellId', width: '260', header: { text: 'CELL_ID' }, autoFilter: true, styleName: 'tl' },
    { name: 'runNo', fieldName: 'runNo', width: '150', header: { text: 'RUN_NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'crackResult', fieldName: 'crackResult', width: '140', header: { text: 'CRACK_RESULT' }, autoFilter: true, styleName: 'tl' },
    { name: 'tabResult', fieldName: 'tabResult', width: '120', header: { text: 'TAB_RESULT' }, autoFilter: true, styleName: 'tl' },
    { name: 'isScrap', fieldName: 'isScrap', width: '100', header: { text: 'IS_SCRAP' }, autoFilter: true, styleName: 'tl' },
    { name: 'operName', fieldName: 'operName', width: '120', header: { text: 'OPER_NAME' }, autoFilter: true, styleName: 'tl' },
    { name: 'operTeam', fieldName: 'operTeam', width: '120', header: { text: 'OPER_TEAM' }, autoFilter: true, styleName: 'tl' },
    { name: 'prevSeqNo', fieldName: 'prevSeqNo', width: '130', header: { text: 'PREV_SEQ_NO' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    // { name: 'regDate', fieldName: 'regDate', width: '80', header: { text: 'REG_DATE' }, autoFilter: true, styleName: 'tl' },
    // { name: 'updDate', fieldName: 'updDate', width: '80', header: { text: 'UPD_DATE' }, autoFilter: true, styleName: 'tl' },
    { name: 'convertRegDate', fieldName: 'convertRegDate', width: '110', header: { text: 'REG_DATE' }, autoFilter: true, styleName: 'tl' },
    { name: 'convertRegTime', fieldName: 'convertRegTime', width: '110', header: { text: 'REG_TIME' }, autoFilter: true, styleName: 'tl' },
    { name: 'convertUpdDate', fieldName: 'convertUpdDate', width: '110', header: { text: 'UPD_DATE' }, autoFilter: true, styleName: 'tl' },
    { name: 'convertUpdTime', fieldName: 'convertUpdTime', width: '110', header: { text: 'UPD_TIME' }, autoFilter: true, styleName: 'tl' },
    { name: 'scrap', fieldName: 'scrap', width: '70', header: { text: 'SCRAP' }, autoFilter: true, styleName: 'tl' },
    { name: 'remark', fieldName: 'remark', width: '80', header: { text: 'Remark' }, autoFilter: true, styleName: 'tl' },
    { name: 'packNo', fieldName: 'packNo', width: '250', header: { text: 'PACK_NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'pack상태', fieldName: 'pack상태', width: '100', header: { text: 'PACK상태' }, autoFilter: true, styleName: 'tl' },
    { name: '폐기사유', fieldName: '폐기사유', width: '100', header: { text: '폐기사유' }, autoFilter: true, styleName: 'tl' },
    { name: '폐기시각', fieldName: '폐기시각', width: '100', header: { text: '폐기시각' }, autoFilter: true, styleName: 'tl' },
    { name: '샘플의뢰여부', fieldName: '샘플의뢰여부', width: '140', header: { text: '샘플의뢰여부' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '샘플Result', fieldName: '샘플Result', width: '130', header: { text: '샘플_RESULT' }, autoFilter: true, styleName: 'tl' },
    { name: '재공적용여부', fieldName: '재공적용여부', width: '140', header: { text: '재공적용_여부' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
  ],
};

module.exports = grid;
