/*
 * 제조 실적 입력 > Back#2 Cell QC > 설비 로그 조회
 */
const { ValueType } = require('realgrid');
const { rgDisplayDate, rgDisplayDateTime2 } = require('@/utils/dateUtils');

const grid = {
  options: {
    checkBar: { visible: false },
    copy: { enabled: true, singleMode: true },
    display: {
      columnMovable: false,
      emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'NONE',
      hscrollBar: true,
      showEmptyMessage: true,
    },
    edit: { editable: false },
    footers: { visible: false },
    paste: { enabled: false },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
    fixed: { colBarWidth: 1, colCount: 4 },
  },

  fields: [
    { fieldName: 'seqId', dataType: ValueType.NUMBER },
    { fieldName: '작업구분', dataType: ValueType.TEXT },
    { fieldName: 'runId', dataType: ValueType.TEXT },
    { fieldName: 'cellId', dataType: ValueType.TEXT },
    { fieldName: 'bef공정코드', dataType: ValueType.TEXT },
    { fieldName: 'worker', dataType: ValueType.TEXT },
    { fieldName: 'shift', dataType: ValueType.TEXT },
    { fieldName: '작업조', dataType: ValueType.TEXT },
    { fieldName: 'startTime', dataType: ValueType.TEXT },
    { fieldName: 'endTime', dataType: ValueType.TEXT },
    { fieldName: '설비호기', dataType: ValueType.TEXT },
    { fieldName: '설비약명', dataType: ValueType.TEXT },
    { fieldName: 'scrap', dataType: ValueType.TEXT },
    { fieldName: 'result', dataType: ValueType.TEXT },
    { fieldName: 'reworkWait', dataType: ValueType.TEXT },
    { fieldName: 'stepNo', dataType: ValueType.NUMBER },
    { fieldName: 'imageNo', dataType: ValueType.NUMBER },
    { fieldName: 'posX', dataType: ValueType.NUMBER },
    { fieldName: 'posY', dataType: ValueType.NUMBER },
    { fieldName: 'alignX', dataType: ValueType.NUMBER },
    { fieldName: 'alignY', dataType: ValueType.NUMBER },
    { fieldName: 'alignR', dataType: ValueType.NUMBER },
    { fieldName: '작업일자', dataType: ValueType.TEXT },
    { fieldName: '특이사항', dataType: ValueType.TEXT },
    { fieldName: '특별입력', dataType: ValueType.TEXT },
    { fieldName: 'mfil작업자', dataType: ValueType.TEXT },
    { fieldName: 'mfilShift', dataType: ValueType.TEXT },
    { fieldName: 'mfil작업조', dataType: ValueType.TEXT },
    { fieldName: 'mfilTime', dataType: ValueType.TEXT },
    { fieldName: '재공적용여부', dataType: ValueType.NUMBER },
  ],

  columns: [
    { name: 'seqId', fieldName: 'seqId', width: '80', header: { text: 'SEQ_ID' }, autoFilter: true, numberFormat: '####', styleName: 'tr' },
    { name: '작업구분', fieldName: '작업구분', width: '80', header: { text: '작업구분' }, autoFilter: true, styleName: 'tl' },
    { name: 'runId', fieldName: 'runId', width: '150', header: { text: 'RUN No.' }, autoFilter: true, styleName: 'tl' },
    { name: 'cellId', fieldName: 'cellId', width: '220', header: { text: 'CELL No.' }, autoFilter: true, styleName: 'tl' },
    { name: 'bef공정코드', fieldName: 'bef공정코드', width: '100', header: { text: 'BEF_공정코드' }, autoFilter: true, styleName: 'tl' },
    { name: 'worker', fieldName: 'worker', width: '70', header: { text: 'Worker' }, autoFilter: true, styleName: 'tl' },
    { name: 'shift', fieldName: 'shift', width: '50', header: { text: 'Shift' }, autoFilter: true, styleName: 'tl' },
    { name: '작업조', fieldName: '작업조', width: '70', header: { text: '작업조' }, autoFilter: true, styleName: 'tl' },
    { name: 'startTime', fieldName: 'startTime', width: '80', header: { text: 'Start_Date' }, autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDate },
    { name: 'startTime', fieldName: 'startTime', width: '80', header: { text: 'Time' }, autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime2 },
    { name: 'endTime', fieldName: 'endTime', width: '80', header: { text: 'End_Date' }, autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDate },
    { name: 'endTime', fieldName: 'endTime', width: '80', header: { text: 'Time' }, autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime2 },
    { name: '설비호기', fieldName: '설비호기', width: '80', header: { text: '설비호기' }, autoFilter: true, styleName: 'tl' },
    {
      name: '설비약명',
      fieldName: '설비약명',
      header: { text: '호기' },
      autoFilter: true,
      styleName: 'tl',
    },
    { name: 'scrap', fieldName: 'scrap', width: '70', header: { text: 'Scrap' }, autoFilter: true, styleName: 'tl' },
    { name: 'result', fieldName: 'result', width: '80', header: { text: 'RESULT' }, autoFilter: true, styleName: 'tl' },
    { name: 'reworkWait', fieldName: 'reworkWait', width: '110', header: { text: 'Rework_Wait' }, autoFilter: true, styleName: 'tl' },
    { name: 'stepNo', fieldName: 'stepNo', width: '80', header: { text: 'STEP_NO' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'imageNo', fieldName: 'imageNo', width: '90', header: { text: 'IMAGE_NO' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'posX', fieldName: 'posX', width: '80', header: { text: 'POS_X' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'posY', fieldName: 'posY', width: '80', header: { text: 'POS_Y' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'alignX', fieldName: 'alignX', width: '80', header: { text: 'ALIGN_X' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'alignY', fieldName: 'alignY', width: '80', header: { text: 'ALIGN_Y' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'alignR', fieldName: 'alignR', width: '80', header: { text: 'ALIGN_R' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '작업일자', fieldName: '작업일자', width: '80', header: { text: '작업일자' }, autoFilter: true, styleName: 'tl' },
    { name: '특이사항', fieldName: '특이사항', width: '80', header: { text: '특이사항' }, autoFilter: true, styleName: 'tl' },
    { name: '특별입력', fieldName: '특별입력', width: '80', header: { text: '특별입력' }, autoFilter: true, styleName: 'tl' },
    { name: 'mfil작업자', fieldName: 'mfil작업자', width: '100', header: { text: 'MFIL_작업자' }, autoFilter: true, styleName: 'tl' },
    { name: 'mfilShift', fieldName: 'mfilShift', width: '100', header: { text: 'MFIL_Shift' }, autoFilter: true, styleName: 'tl' },
    { name: 'mfil작업조', fieldName: 'mfil작업조', width: '100', header: { text: 'MFIL_작업조' }, autoFilter: true, styleName: 'tl' },
    { name: 'mfilTime', fieldName: 'mfilTime', width: '100', header: { text: 'MFIL_Time' }, autoFilter: true, styleName: 'tl' },
    { name: '재공적용여부', fieldName: '재공적용여부', width: '110', header: { text: '재공적용_여부' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
  ],
};

module.exports = grid;
