/*
 * 제조 실적 입력 > Back#2 Cell QC > 설비 로그 조회
 */
const { ValueType } = require('realgrid');
const { rgDisplayDate, rgDisplayDateTime1 } = require('@/utils/dateUtils');

const grid = {
  options: {
    checkBar: { visible: false },
    copy: { enabled: true, singleMode: true },
    display: {
      columnMovable: false,
      emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'NONE',
      hscrollBar: true,
      showEmptyMessage: true,
    },
    edit: { editable: false },
    footers: { visible: false },
    paste: { enabled: false },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
    fixed: { colBarWidth: 1, colCount: 4},
  },

  fields: [
		{ fieldName: '제조일자', dataType: ValueType.TEXT },
		{ fieldName: '일일생산번호', dataType: ValueType.NUMBER },
		{ fieldName: '일일생산일련번호', dataType: ValueType.TEXT },
		{ fieldName: 'runId', dataType: ValueType.TEXT },
		{ fieldName: '차수', dataType: ValueType.NUMBER },
		{ fieldName: '재작업', dataType: ValueType.NUMBER },
		{ fieldName: 'originNo', dataType: ValueType.TEXT },
		{ fieldName: 'pack번호', dataType: ValueType.TEXT },
		{ fieldName: 'boxNo', dataType: ValueType.TEXT },
		{ fieldName: 'tray수량', dataType: ValueType.NUMBER },
		{ fieldName: 'cell수량', dataType: ValueType.NUMBER },
		{ fieldName: 'cell삭제', dataType: ValueType.NUMBER },
		{ fieldName: '라인구분', dataType: ValueType.TEXT },
		{ fieldName: 'worker', dataType: ValueType.TEXT },
		{ fieldName: 'shift', dataType: ValueType.TEXT },
		{ fieldName: '작업조', dataType: ValueType.TEXT },
		{ fieldName: '상태', dataType: ValueType.TEXT },
		{ fieldName: '비고', dataType: ValueType.TEXT },
		{ fieldName: '총발행매수', dataType: ValueType.NUMBER },
		{ fieldName: 'qr제조일자', dataType: ValueType.TEXT },
		{ fieldName: 'qr일일생산번호', dataType: ValueType.TEXT },
		{ fieldName: 'qr일일생산일련번호', dataType: ValueType.TEXT },
		{ fieldName: '포장확인', dataType: ValueType.TEXT },
		{ fieldName: 'startTime', dataType: ValueType.TEXT },
		{ fieldName: 'endTime', dataType: ValueType.TEXT },
		{ fieldName: '작업시각', dataType: ValueType.TEXT },
		{ fieldName: '발행자', dataType: ValueType.TEXT },
		{ fieldName: '발행자서명', dataType: ValueType.BOOLEAN },
		{ fieldName: '승인자', dataType: ValueType.TEXT },
		{ fieldName: '승인자서명', dataType: ValueType.BOOLEAN },
		{ fieldName: '처리시각', dataType: ValueType.TEXT },
		{ fieldName: 'pack상태', dataType: ValueType.TEXT },
		{ fieldName: '폐기사유', dataType: ValueType.TEXT },
		{ fieldName: '폐기시각', dataType: ValueType.TEXT },
		{ fieldName: '샘플의뢰여부', dataType: ValueType.NUMBER },
		{ fieldName: '재작업여부', dataType: ValueType.NUMBER },
		{ fieldName: 'result', dataType: ValueType.TEXT },
  ],

  columns: [
    { name: '제조일자', fieldName: '제조일자', width: '90', header: { text: '제조일자' } , autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDate },
		{ name: '일일생산번호', fieldName: '일일생산번호', width: '120', header: { text: '일일생산번호' } , autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
		{ name: '일일생산일련번호', fieldName: '일일생산일련번호', width: '160', header: { text: '일일생산일련번호' } , autoFilter: true, styleName: 'tl', },
		{ name: 'runId', fieldName: 'runId', width: '180', header: { text: 'RUN_ID' } , autoFilter: true, styleName: 'tl', },
		{ name: '차수', fieldName: '차수', width: '90', header: { text: '차수' } , autoFilter: true, numberFormat: '#,###.###', styleName: 'tr'  },
		{ name: '재작업', fieldName: '재작업', width: '80', header: { text: '재작업' } , autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' , },
		{ name: 'originNo', fieldName: 'originNo', width: '100', header: { text: 'ORIGIN_NO' } , autoFilter: true, styleName: 'tl', },
		{ name: 'pack번호', fieldName: 'pack번호', width: '250', header: { text: 'Pack번호' } , autoFilter: true, styleName: 'tl', },
		{ name: 'boxNo', fieldName: 'boxNo', width: '250', header: { text: 'BOX_NO' } , autoFilter: true, styleName: 'tl', },
		{ name: 'tray수량', fieldName: 'tray수량', width: '120', header: { text: 'Tray수량' } , autoFilter: true, numberFormat: '#,###.###', styleName: 'tr'  },
		{ name: 'cell수량', fieldName: 'cell수량', width: '120', header: { text: 'Cell수량' } , autoFilter: true, numberFormat: '#,###.###', styleName: 'tr'  },
		{ name: 'cell삭제', fieldName: 'cell삭제', width: '120', header: { text: 'CELL삭제' } , autoFilter: true, numberFormat: '#,###.###', styleName: 'tr'  },
		{ name: '라인구분', fieldName: '라인구분', width: '90', header: { text: '라인구분' } , autoFilter: true, styleName: 'tl', },
		{ name: 'worker', fieldName: 'worker', width: '90', header: { text: 'Worker' } , autoFilter: true, styleName: 'tl', },
		{ name: 'shift', fieldName: 'shift', width: '90', header: { text: 'Shift' } , autoFilter: true, styleName: 'tl', },
		{ name: '작업조', fieldName: '작업조', width: '90', header: { text: '작업조' } , autoFilter: true, styleName: 'tl', },
		{ name: '상태', fieldName: '상태', width: '90', header: { text: '상태' } , autoFilter: true, styleName: 'tl', },
		{ name: '비고', fieldName: '비고', width: '200', header: { text: '비고' } , autoFilter: true, styleName: 'tl', },
		{ name: '총발행매수', fieldName: '총발행매수', width: '100', header: { text: '총발행매수' } , autoFilter: true, numberFormat: '#,###.###', styleName: 'tr'  },
		{ name: 'qr제조일자', fieldName: 'qr제조일자', width: '120', header: { text: 'QR제조일자' } , autoFilter: true, styleName: 'tl', },
		{ name: 'qr일일생산번호', fieldName: 'qr일일생산번호', width: '160', header: { text: 'QR일일생산번호' } , autoFilter: true, styleName: 'tl', },
		{ name: 'qr일일생산일련번호', fieldName: 'qr일일생산일련번호', width: '200', header: { text: 'QR일일생산일련번호' } , autoFilter: true, styleName: 'tl', },
		{ name: '포장확인', fieldName: '포장확인', width: '110', header: { text: '포장확인' } , autoFilter: true, styleName: 'tl', },
		{ name: 'startTime', fieldName: 'startTime', width: '150', header: { text: 'Start_Time' } , autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime1 },
		{ name: 'endTime', fieldName: 'endTime', width: '150', header: { text: 'End_Time' } , autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime1 },
		{ name: '작업시각', fieldName: '작업시각', width: '150', header: { text: '작업시각' } , autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime1 },
		{ name: '발행자', fieldName: '발행자', width: '90', header: { text: '발행자' } , autoFilter: true, styleName: 'tl', },
		{ name: '발행자서명', fieldName: '발행자서명', width: '100', header: { text: '발행자서명' } , autoFilter: true, styleName: 'tc', renderer: {  type: 'check',},},
		{ name: '승인자', fieldName: '승인자', width: '90', header: { text: '승인자' } , autoFilter: true, styleName: 'tl', },
		{ name: '승인자서명', fieldName: '승인자서명', width: '100', header: { text: '승인자서명' } , autoFilter: true, styleName: 'tc', renderer: {  type: 'check',},},
		{ name: '처리시각', fieldName: '처리시각', width: '150', header: { text: '처리시각' } , autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime1 },
		{ name: 'pack상태', fieldName: 'pack상태', width: '120', header: { text: 'PACK상태' } , autoFilter: true, styleName: 'tl', },
		{ name: '폐기사유', fieldName: '폐기사유', width: '200', header: { text: '폐기사유' } , autoFilter: true, styleName: 'tl', },
		{ name: '폐기시각', fieldName: '폐기시각', width: '150', header: { text: '폐기시각' } , autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime1 },
		{ name: '샘플의뢰여부', fieldName: '샘플의뢰여부', width: '120', header: { text: '샘플의뢰여부' } , autoFilter: true, numberFormat: '#,###.###', styleName: 'tr'},
		{ name: '재작업여부', fieldName: '재작업여부', width: '100', header: { text: '재작업여부' } , autoFilter: true, numberFormat: '#,###.###', styleName: 'tr'},
		{ name: 'result', fieldName: 'result', width: '110', header: { text: 'RESULT' } , autoFilter: true, styleName: 'tl', },  ],
};

module.exports = grid;
