/*
 * 제조 실적 입력 > Back#1 > 설비 로그 조회 > BTP, ATP
 */
const { ValueType } = require('realgrid');
const { rgDisplayDateTime } = require('@/utils/dateUtils');

const grid = {
  options: {
    checkBar: { visible: false },
    copy: { enabled: true, singleMode: true },
    display: {
      columnMovable: false,
      emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'NONE',
      hscrollBar: true,
      showEmptyMessage: true,
    },
    edit: { editable: false },
    footers: { visible: false },
    paste: { enabled: false },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
    fixed: { colBarWidth: 1, colCount: 4 },
  },

  fields: [
    { fieldName: 'seqId', dataType: ValueType.NUMBER },
    { fieldName: '공장코드', dataType: ValueType.TEXT },
    //{ fieldName: '설비호기', dataType: ValueType.TEXT },
    { fieldName: '설비약명', dataType: ValueType.TEXT },
    { fieldName: 'runNo', dataType: ValueType.TEXT },
    { fieldName: '근무조', dataType: ValueType.TEXT },
    { fieldName: '작업자', dataType: ValueType.TEXT },
    { fieldName: 'startTime', dataType: ValueType.TEXT },
    { fieldName: 'endTime', dataType: ValueType.TEXT },
    { fieldName: 'inCstnoL', dataType: ValueType.TEXT },
    { fieldName: 'inCstnoR', dataType: ValueType.TEXT },
    { fieldName: 'inCstsu', dataType: ValueType.NUMBER },
    { fieldName: 'inCst행열L', dataType: ValueType.TEXT },
    { fieldName: 'inCst행열R', dataType: ValueType.TEXT },
    { fieldName: 'outCstnoL', dataType: ValueType.TEXT },
    { fieldName: 'outCstnoR', dataType: ValueType.TEXT },
    { fieldName: 'outCstsu', dataType: ValueType.NUMBER },
    { fieldName: 'outCst행열L', dataType: ValueType.TEXT },
    { fieldName: 'outCst행열R', dataType: ValueType.TEXT },
    { fieldName: '불량명', dataType: ValueType.TEXT },
    { fieldName: 'recipeParameter', dataType: ValueType.NUMBER },
    { fieldName: 'ld이송속도', dataType: ValueType.NUMBER },
    { fieldName: 'ldLift속도', dataType: ValueType.NUMBER },
    { fieldName: '린스이송속도', dataType: ValueType.NUMBER },
    { fieldName: '린스Lift속도', dataType: ValueType.NUMBER },
    { fieldName: 'uld이송속도', dataType: ValueType.NUMBER },
    { fieldName: 'uldLift속도', dataType: ValueType.NUMBER },
  ],

  columns: [
    { name: 'seqId', fieldName: 'seqId', width: '80', header: { text: 'SEQ_ID' }, autoFilter: true, numberFormat: '####', styleName: 'tr' },
    { name: '공장코드', fieldName: '공장코드', width: '80', header: { text: '공장코드' }, autoFilter: true, styleName: 'tl' },
    //{ name: '설비호기', fieldName: '설비호기', width: '80', header: { text: '설비호기' }, autoFilter: true, styleName: 'tl'},
    {
      name: '설비약명',
      fieldName: '설비약명',
      header: { text: '호기' },
      autoFilter: true,
      styleName: 'tl',
    },
    { name: 'runNo', fieldName: 'runNo', width: '150', header: { text: 'RUN_NO' }, autoFilter: true, styleName: 'tl' },
    { name: '근무조', fieldName: '근무조', width: '80', header: { text: '근무조' }, autoFilter: true, styleName: 'tl' },
    { name: '작업자', fieldName: '작업자', width: '80', header: { text: '작업자' }, autoFilter: true, styleName: 'tl' },
    {
      name: 'startTime',
      fieldName: 'startTime',
      width: '120',
      header: { text: '작업시작시간' },
      autoFilter: true,
      styleName: 'tl',
      displayCallback: rgDisplayDateTime,
    },
    {
      name: 'endTime',
      fieldName: 'endTime',
      width: '120',
      header: { text: '작업종료시간' },
      autoFilter: true,
      styleName: 'tl',
      displayCallback: rgDisplayDateTime,
    },
    { name: 'inCstnoL', fieldName: 'inCstnoL', width: '100', header: { text: 'IN_CSTNO_L' }, autoFilter: true, styleName: 'tl' },
    { name: 'inCstnoR', fieldName: 'inCstnoR', width: '100', header: { text: 'IN_CSTNO_R' }, autoFilter: true, styleName: 'tl' },
    { name: 'inCstsu', fieldName: 'inCstsu', width: '80', header: { text: 'IN_CSTSU' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'inCst행열L', fieldName: 'inCst행열L', width: '120', header: { text: 'IN_CST행열_L' }, autoFilter: true, styleName: 'tl' },
    { name: 'inCst행열R', fieldName: 'inCst행열R', width: '120', header: { text: 'IN_CST행열_R' }, autoFilter: true, styleName: 'tl' },
    { name: 'outCstnoL', fieldName: 'outCstnoL', width: '110', header: { text: 'OUT_CSTNO_L' }, autoFilter: true, styleName: 'tl' },
    { name: 'outCstnoR', fieldName: 'outCstnoR', width: '110', header: { text: 'OUT_CSTNO_R' }, autoFilter: true, styleName: 'tl' },
    { name: 'outCstsu', fieldName: 'outCstsu', width: '90', header: { text: 'OUT_CSTSU' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'outCst행열L', fieldName: 'outCst행열L', width: '120', header: { text: 'OUT_CST행열_L' }, autoFilter: true, styleName: 'tl' },
    { name: 'outCst행열R', fieldName: 'outCst행열R', width: '120', header: { text: 'OUT_CST행열_R' }, autoFilter: true, styleName: 'tl' },
    { name: '불량명', fieldName: '불량명', width: '80', header: { text: '불량명' }, autoFilter: true, styleName: 'tl' },
    { name: 'recipeParameter', fieldName: 'recipeParameter', width: '130', header: { text: 'Recipe_Parameter' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'ld이송속도', fieldName: 'ld이송속도', width: '100', header: { text: 'LD_이송속도' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'ldLift속도', fieldName: 'ldLift속도', width: '100', header: { text: 'LD_Lift속도' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '린스이송속도', fieldName: '린스이송속도', width: '110', header: { text: '린스_이송속도' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '린스Lift속도', fieldName: '린스Lift속도', width: '110', header: { text: '린스_Lift속도' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'uld이송속도', fieldName: 'uld이송속도', width: '110', header: { text: 'ULD_이송속도' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'uldLift속도', fieldName: 'uldLift속도', width: '100', header: { text: 'ULD_Lift속도' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
  ],
};

module.exports = grid;
