/*
 * 제조 실적 입력 > Back#1 > 설비 로그 조회
 */
const { ValueType } = require('realgrid');
const { rgDisplayDateTime } = require('@/utils/dateUtils');

const grid = {
  options: {
    checkBar: { visible: false },
    copy: { enabled: true, singleMode: true },
    display: {
      columnMovable: false,
      emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'NONE',
      hscrollBar: true,
      showEmptyMessage: true,
    },
    edit: { editable: false, columnEditableFirst: true, commitByCell: true, commitWhenLeave: true },
    footers: { visible: false },
    paste: { enabled: true, checkReadOnly: true, commitEdit: true, enableAppend: false, selectBlockPaste: true },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
    fixed: { colBarWidth: 1, colCount: 9 },
  },

  fields: [
    { fieldName: 'seqId', dataType: ValueType.NUMBER },
    { fieldName: '공장코드', dataType: ValueType.TEXT },
    { fieldName: '공정코드', dataType: ValueType.TEXT },
    //{ fieldName: '설비호기', dataType: ValueType.TEXT },
    { fieldName: '설비약명', dataType: ValueType.TEXT },
    { fieldName: 'zone', dataType: ValueType.TEXT },
    { fieldName: 'ldCstSlotNo', dataType: ValueType.TEXT },
    { fieldName: '불림수조SlotNo', dataType: ValueType.TEXT },
    { fieldName: 'runNo', dataType: ValueType.TEXT },
    { fieldName: 'lotNo', dataType: ValueType.TEXT },
    { fieldName: '근무조', dataType: ValueType.TEXT },
    { fieldName: '작업자', dataType: ValueType.TEXT },
    { fieldName: 'startTime', dataType: ValueType.TEXT },
    { fieldName: 'endTime', dataType: ValueType.TEXT },
    { fieldName: 'outCst위치', dataType: ValueType.TEXT },
    { fieldName: 'outCstno', dataType: ValueType.TEXT },
    { fieldName: 'outCstsu', dataType: ValueType.NUMBER },
    { fieldName: 'outCst행열', dataType: ValueType.TEXT },
    { fieldName: '삭제위치', dataType: ValueType.TEXT },
    { fieldName: '불량명', dataType: ValueType.TEXT },
    { fieldName: '수조온도', dataType: ValueType.NUMBER },
    { fieldName: '수조Z축위치', dataType: ValueType.NUMBER },
    { fieldName: 'trZ축위치', dataType: ValueType.NUMBER },
    { fieldName: 'tr회전속도', dataType: ValueType.NUMBER },
    { fieldName: 'alignX1', dataType: ValueType.NUMBER },
    { fieldName: 'alignX2', dataType: ValueType.NUMBER },
    { fieldName: 'alignY', dataType: ValueType.NUMBER },
    { fieldName: 'trVacuum압력', dataType: ValueType.NUMBER },
    { fieldName: 'robotVacuum압력', dataType: ValueType.NUMBER },
    { fieldName: 'inspResult', dataType: ValueType.TEXT },
  ],

  columns: [
    { name: 'seqId', fieldName: 'seqId', width: '80', header: { text: 'SEQ_ID' }, autoFilter: true, numberFormat: '####', styleName: 'tr' },
    { name: '공장코드', fieldName: '공장코드', width: '80', header: { text: '공장코드' }, autoFilter: true, styleName: 'tl' },
    { name: '공정코드', fieldName: '공정코드', width: '80', header: { text: '공정코드' }, autoFilter: true, styleName: 'tl' },
    //{ name: '설비호기', fieldName: '설비호기', width: '80', header: { text: '설비호기' },autoFilter: true , styleName: "tl"},
    {
      name: '설비약명',
      fieldName: '설비약명',
      header: { text: '호기' },
      autoFilter: true,
      styleName: 'tl',
    },
    { name: 'zone', fieldName: 'zone', width: '80', header: { text: 'ZONE' }, autoFilter: true, styleName: 'tl' },
    { name: 'ldCstSlotNo', fieldName: 'ldCstSlotNo', width: '130', header: { text: 'LD_CST_SLOT_NO' }, autoFilter: true, styleName: 'tl' },
    { name: '불림수조SlotNo', fieldName: '불림수조SlotNo', width: '150', header: { text: '불림수조_SLOT_NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'runNo', fieldName: 'runNo', width: '150', header: { text: 'RUN_NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'lotNo', fieldName: 'lotNo', width: '150', header: { text: 'LOT_NO' }, autoFilter: true, styleName: 'edit tl', editable: true },
    { name: '근무조', fieldName: '근무조', width: '80', header: { text: '근무조' }, autoFilter: true, styleName: 'tl' },
    { name: '작업자', fieldName: '작업자', width: '80', header: { text: '작업자' }, autoFilter: true, styleName: 'tl' },
    {
      name: 'startTime',
      fieldName: 'startTime',
      width: '120',
      header: { text: '작업시작시간' },
      autoFilter: true,
      styleName: 'tl',
      displayCallback: rgDisplayDateTime,
    },
    {
      name: 'endTime',
      fieldName: 'endTime',
      width: '120',
      header: { text: '작업종료시간' },
      autoFilter: true,
      styleName: 'tl',
      displayCallback: rgDisplayDateTime,
    },
    { name: 'outCst위치', fieldName: 'outCst위치', width: '110', header: { text: 'OUT_CST위치' }, autoFilter: true, styleName: 'tl' },
    { name: 'outCstno', fieldName: 'outCstno', width: '100', header: { text: 'OUT_CSTNO' }, autoFilter: true, styleName: 'edit tl', editable: true },
    { name: 'outCstsu', fieldName: 'outCstsu', width: '90', header: { text: 'OUT_CSTSU' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tl' },
    { name: 'outCst행열', fieldName: 'outCst행열', width: '110', header: { text: 'OUT_CST행열' }, autoFilter: true, styleName: 'tl' },
    { name: '삭제위치', fieldName: '삭제위치', width: '80', header: { text: '삭제위치' }, autoFilter: true, styleName: 'tl' },
    { name: '불량명', fieldName: '불량명', width: '80', header: { text: '불량명' }, autoFilter: true, styleName: 'tl' },
    { name: '수조온도', fieldName: '수조온도', width: '80', header: { text: '수조_온도' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '수조Z축위치', fieldName: '수조Z축위치', width: '120', header: { text: '수조_Z축위치' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'trZ축위치', fieldName: 'trZ축위치', width: '100', header: { text: 'TR_Z축위치' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'tr회전속도', fieldName: 'tr회전속도', width: '100', header: { text: 'TR_회전속도' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'alignX1', fieldName: 'alignX1', width: '80', header: { text: 'Align_X1' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'alignX2', fieldName: 'alignX2', width: '80', header: { text: 'Align_X2' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'alignY', fieldName: 'alignY', width: '80', header: { text: 'Align_Y' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'trVacuum압력', fieldName: 'trVacuum압력', width: '130', header: { text: 'TR_Vacuum압력' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'robotVacuum압력', fieldName: 'robotVacuum압력', width: '140', header: { text: 'Robot_Vacuum압력' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'inspResult', fieldName: 'inspResult', width: '90', header: { text: 'Insp_Result' }, autoFilter: true, styleName: 'tl' },
  ],
};

module.exports = grid;
