/*
 * 카세트 관리 > 카세트 점검
 */
const { ValueType } = require('realgrid');
const { rgDisplayDate, rgDisplayTime } = require('@/utils/dateUtils');

const grid = {
  options: {
    checkBar: { visible: true },
    copy: { enabled: true, singleMode: false },
    display: {
      columnMovable: false,
      emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'NONE',
      hscrollBar: true,
      showEmptyMessage: true,
    },
    edit: { editable: true },
    footers: { visible: false },
    paste: { enabled: true, checkReadOnly: true, enableAppend: false, selectBlockPaste: true, singleMode: false, eventEachRow: true },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
    header: { height: 40 },
    fixed: { colBarWidth: 1, colCount: 4 },
  },

  fields: [
    { fieldName: '공장코드', dataType: ValueType.TEXT },
    { fieldName: '종류', dataType: ValueType.TEXT },
    { fieldName: '타입', dataType: ValueType.TEXT },
    { fieldName: '모델', dataType: ValueType.TEXT },
    { fieldName: 'cstNo', dataType: ValueType.TEXT },
    { fieldName: '열', dataType: ValueType.NUMBER },
    { fieldName: '행', dataType: ValueType.NUMBER },
    { fieldName: '위치', dataType: ValueType.TEXT },
    { fieldName: '카세트상태', dataType: ValueType.TEXT },
    { fieldName: '카세트상태값', dataType: ValueType.TEXT },
    { fieldName: '최근점검시작일', dataType: ValueType.TEXT },
    { fieldName: '최근점검시작시간', dataType: ValueType.TEXT },
    { fieldName: '최근점검종료일', dataType: ValueType.TEXT },
    { fieldName: '최근점검종료시간', dataType: ValueType.TEXT },
    { fieldName: '최근점검작업자', dataType: ValueType.TEXT },
    { fieldName: '최근점검결과', dataType: ValueType.TEXT },
    { fieldName: '강화브라켓지그일치유무', dataType: ValueType.TEXT },
    { fieldName: '강화슬롯상태', dataType: ValueType.TEXT },
    { fieldName: '강화Mesh올상태', dataType: ValueType.TEXT },
    { fieldName: '강화Mesh들뜸', dataType: ValueType.TEXT },
    { fieldName: '강화볼트체결', dataType: ValueType.TEXT },
    { fieldName: '강화외관', dataType: ValueType.TEXT },
    { fieldName: '점검자', dataType: ValueType.TEXT },
    { fieldName: '시작일자', dataType: ValueType.TEXT },
    { fieldName: '시작시간', dataType: ValueType.TEXT },
    { fieldName: '종료일자', dataType: ValueType.TEXT },
    { fieldName: '종료시간', dataType: ValueType.TEXT },
    { fieldName: '점검결과', dataType: ValueType.TEXT },
  ],

  columns: [
    // { name: '공장코드', fieldName: '공장코드', width: '80', header: { text: '공장코드' }, autoFilter: true, editable: false , styleName: 'tl'},
    { name: '종류', fieldName: '종류', width: '50', header: { text: '종류' }, autoFilter: true, editable: false, styleName: 'tl' },
    { name: '타입', fieldName: '타입', width: '50', header: { text: '타입' }, autoFilter: true, editable: false, styleName: 'tl' },
    { name: '모델', fieldName: '모델', width: '50', header: { text: '모델' }, autoFilter: true, editable: false, styleName: 'tl' },
    { name: 'cstNo', fieldName: 'cstNo', width: '80', header: { text: 'CST_NO' }, autoFilter: true, editable: false, styleName: 'tl' },
    // { name: '열', fieldName: '열', width: '80', header: { text: '열' }, autoFilter: true, numberFormat: '#,###.###', editable: false, styleName: 'tr' },
    // { name: '행', fieldName: '행', width: '80', header: { text: '행' }, autoFilter: true, numberFormat: '#,###.###', editable: false, styleName: 'tr'},
    { name: '위치', fieldName: '위치', width: '50', header: { text: '위치' }, autoFilter: true, editable: false, styleName: 'tl' },
    { name: '카세트상태', fieldName: '카세트상태', width: '70 ', header: { text: '카세트상태' }, autoFilter: true, editable: false, styleName: 'tl' },
    { name: '카세트상태값', fieldName: '카세트상태값', width: '70', header: { text: '카세트상태값' }, autoFilter: true, editable: false, styleName: 'tl', visible: false },
    { name: '최근점검시작일', fieldName: '최근점검시작일', width: '80', header: { text: '최근점검시작일' }, autoFilter: true, editable: false, styleName: 'tl', displayCallback: rgDisplayDate },
    // { name: '최근점검시작시간', fieldName: '최근점검시작시간', width: '80', header: { text: '최근점검시작시간' }, autoFilter: true, editable: false, styleName: 'tl', displayCallback: rgDisplayTime },
    // { name: '최근점검종료일', fieldName: '최근점검종료일', width: '80', header: { text: '최근점검종료일' }, autoFilter: true, editable: false, styleName: 'tl', displayCallback: rgDisplayDate },
    // { name: '최근점검종료시간', fieldName: '최근점검종료시간', width: '80', header: { text: '최근점검종료시간' }, autoFilter: true, editable: false, styleName: 'tl', displayCallback: rgDisplayTime },
    { name: '최근점검작업자', fieldName: '최근점검작업자', width: '80', header: { text: '최근점검작업자' }, autoFilter: true, editable: false, styleName: 'tl' },
    { name: '최근점검결과', fieldName: '최근점검결과', width: '80', header: { text: '최근점검결과' }, autoFilter: true, editable: false, styleName: 'tl' },
    {
      name: '강화브라켓지그일치유무',
      fieldName: '강화브라켓지그일치유무',
      width: '90',
      header: { text: '브라켓지그일치유무' },
      values: ['적합', '부적합'],
      editor: {
        type: 'dropdown',
        domainOnly: true,
        dropDownWhenClick: true,
      },
      autoFilter: true,
      styleName: 'edit tl',
      editable: true,
    },
    {
      name: '강화슬롯상태',
      fieldName: '강화슬롯상태',
      width: '80',
      header: { text: '슬롯상태' },
      values: ['적합', '부적합'],
      editor: {
        type: 'dropdown',
        domainOnly: true,
        dropDownWhenClick: true,
      },
      autoFilter: true,
      styleName: 'edit tl',
      editable: true,
    },
    {
      name: '강화Mesh올상태',
      fieldName: '강화Mesh올상태',
      width: '80',
      header: { text: 'Mesh올상태' },
      values: ['적합', '부적합'],
      editor: {
        type: 'dropdown',
        domainOnly: true,
        dropDownWhenClick: true,
      },
      autoFilter: true,
      styleName: 'edit tl',
      editable: true,
    },
    {
      name: '강화Mesh들뜸',
      fieldName: '강화Mesh들뜸',
      width: '80',
      header: { text: 'Mesh들뜸' },
      values: ['적합', '부적합'],
      editor: {
        type: 'dropdown',
        domainOnly: true,
        dropDownWhenClick: true,
      },
      autoFilter: true,
      styleName: 'edit tl',
      editable: true,
    },
    {
      name: '강화볼트체결',
      fieldName: '강화볼트체결',
      width: '80',
      header: { text: '볼트체결' },
      values: ['적합', '부적합'],
      editor: {
        type: 'dropdown',
        domainOnly: true,
        dropDownWhenClick: true,
      },
      autoFilter: true,
      styleName: 'edit tl',
      editable: true,
    },
    {
      name: '강화외관',
      fieldName: '강화외관',
      width: '80',
      header: { text: '외관' },
      values: ['적합', '부적합'],
      editor: {
        type: 'dropdown',
        domainOnly: true,
        dropDownWhenClick: true,
      },
      autoFilter: true,
      styleName: 'edit tl',
      editable: true,
    },
    { name: '점검자', fieldName: '점검자', width: '90', header: { text: '점검자' }, autoFilter: true, editable: false, styleName: 'tl' },
    { name: '시작일자', fieldName: '시작일자', width: '80', header: { text: '시작일자' }, autoFilter: true, editable: false, styleName: 'tl', displayCallback: rgDisplayDate },
    { name: '시작시간', fieldName: '시작시간', width: '80', header: { text: '시작시간' }, autoFilter: true, editable: false, styleName: 'tl', displayCallback: rgDisplayTime },
    { name: '종료일자', fieldName: '종료일자', width: '80', header: { text: '종료일자' }, autoFilter: true, editable: false, styleName: 'tl', displayCallback: rgDisplayDate },
    { name: '종료시간', fieldName: '종료시간', width: '80', header: { text: '종료시간' }, autoFilter: true, editable: false, styleName: 'tl', displayCallback: rgDisplayTime },
    { name: '점검결과', fieldName: '점검결과', width: '80', header: { text: '점검결과' }, autoFilter: true, editable: false, styleName: 'tl' },
  ],
};

module.exports = grid;
