/*
 * 카세트 관리 > 카세트 불출 > ?? 카세트 > 검사 진행
 */
const { ValueType } = require('realgrid');
const { rgDisplayDate, rgDisplayTime } = require('@/utils/dateUtils');

const grid = {
  options: {
    checkBar: { visible: true },
    copy: { enabled: true, singleMode: true },
    display: {
      columnMovable: false,
      emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'NONE',
      hscrollBar: true,
      showEmptyMessage: true,
    },
    edit: { editable: true, commitByCell: true },
    footers: { visible: false },
    paste: { enabled: true, checkReadOnly: true, enableAppend: false, selectBlockPaste: true, singleMode: false, eventEachRow: true },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
    fixed: { colBarWidth: 1, colCount: 7 },
  },

  fields: [
    { fieldName: '공장코드', dataType: ValueType.TEXT },
    { fieldName: '불출대기일자', dataType: ValueType.TEXT },
    { fieldName: 'seqNo', dataType: ValueType.NUMBER },
    { fieldName: '종류', dataType: ValueType.TEXT },
    { fieldName: '타입', dataType: ValueType.TEXT },
    { fieldName: '모델', dataType: ValueType.TEXT },
    { fieldName: 'cstNo', dataType: ValueType.TEXT },
    { fieldName: '열', dataType: ValueType.NUMBER },
    { fieldName: '행', dataType: ValueType.NUMBER },
    { fieldName: '카세트팀담당자', dataType: ValueType.TEXT },
    { fieldName: '카세트상태', dataType: ValueType.TEXT },
    { fieldName: '검사부서', dataType: ValueType.TEXT },
    { fieldName: '검사자', dataType: ValueType.TEXT },
    { fieldName: '검사일자', dataType: ValueType.TEXT },
    { fieldName: '검사시간', dataType: ValueType.TEXT },
    { fieldName: '검사결과', dataType: ValueType.TEXT },
    { fieldName: '불출부서', dataType: ValueType.TEXT },
    { fieldName: '불출담당자', dataType: ValueType.TEXT },
    { fieldName: '불출일자', dataType: ValueType.TEXT },
    { fieldName: '불출시간', dataType: ValueType.TEXT },
    { fieldName: '비고', dataType: ValueType.TEXT },
  ],

  columns: [
    { name: '공장코드', fieldName: '공장코드', width: '80', header: { text: '공장코드' }, autoFilter: true, editable: false, styleName: 'tl' },
    {
      name: '불출대기일자',
      fieldName: '불출대기일자',
      width: '100',
      header: { text: '불출대기일자' },
      autoFilter: true,
      editable: false,
      styleName: 'tl',
      displayCallback: rgDisplayDate,
    },
    { name: 'seqNo', fieldName: 'seqNo', width: '80', header: { text: 'seq_no' }, autoFilter: true, numberFormat: '#,###.###', editable: false, styleName: 'tr' },
    { name: '종류', fieldName: '종류', width: '80', header: { text: '종류' }, autoFilter: true, editable: false, styleName: 'tl' },
    { name: '타입', fieldName: '타입', width: '80', header: { text: '타입' }, autoFilter: true, editable: false, styleName: 'tl' },
    { name: '모델', fieldName: '모델', width: '80', header: { text: '모델' }, autoFilter: true, editable: false, styleName: 'tl' },
    { name: 'cstNo', fieldName: 'cstNo', width: '80', header: { text: 'CST_NO' }, autoFilter: true, editable: false, styleName: 'tl' },
    { name: '열', fieldName: '열', width: '80', header: { text: '열' }, autoFilter: true, numberFormat: '#,###.###', editable: false, styleName: 'tr' },
    { name: '행', fieldName: '행', width: '80', header: { text: '행' }, autoFilter: true, numberFormat: '#,###.###', editable: false, styleName: 'tr' },
    { name: '카세트팀담당자', fieldName: '카세트팀담당자', width: '130', header: { text: '카세트팀_담당자' }, autoFilter: true, editable: false, styleName: 'tl' },
    { name: '카세트상태', fieldName: '카세트상태', width: '100', header: { text: '카세트_상태' }, autoFilter: true, editable: false, styleName: 'tl' },
    { name: '검사부서', fieldName: '검사부서', width: '80', header: { text: '검사부서' }, autoFilter: true, editable: false, styleName: 'tl' },
    { name: '검사자', fieldName: '검사자', width: '90', header: { text: '검사자' }, autoFilter: true, editable: false, styleName: 'tl' },
    {
      name: '검사일자',
      fieldName: '검사일자',
      width: '80',
      header: { text: '검사일자' },
      autoFilter: true,
      editable: false,
      styleName: 'tl',
      displayCallback: rgDisplayDate,
    },
    {
      name: '검사시간',
      fieldName: '검사시간',
      width: '80',
      header: { text: '검사시간' },
      autoFilter: true,
      editable: false,
      styleName: 'tl',
      displayCallback: rgDisplayTime,
    },
    {
      name: '검사결과',
      fieldName: '검사결과',
      width: '80',
      header: { text: '검사결과' },
      values: ['OK', 'NG'],
      editor: {
        type: 'dropdown',
        domainOnly: true, //*** dropdown 목록에 있는 값만 허용하고자 할때
        dropDownWhenClick: true, //셀을 클릭해도 dropdown 목록이 펼쳐지길 원할때
      },
      autoFilter: true,
      styleName: 'edit tl',
      editable: true,
    },
    { name: '불출부서', fieldName: '불출부서', width: '80', header: { text: '불출부서' }, autoFilter: true, editable: false, styleName: 'tl' },
    { name: '불출담당자', fieldName: '불출담당자', width: '90', header: { text: '불출담당자' }, autoFilter: true, editable: false, styleName: 'tl' },
    {
      name: '불출일자',
      fieldName: '불출일자',
      width: '80',
      header: { text: '불출일자' },
      autoFilter: true,
      editable: false,
      styleName: 'tl',
      displayCallback: rgDisplayDate,
    },
    {
      name: '불출시간',
      fieldName: '불출시간',
      width: '80',
      header: { text: '불출시간' },
      autoFilter: true,
      editable: false,
      styleName: 'tl',
      displayCallback: rgDisplayTime,
    },
    { name: '비고', fieldName: '비고', width: '80', header: { text: '비고' }, autoFilter: true, editable: false, styleName: 'tl' },
  ],
};

module.exports = grid;
