CREATE Procedure Cancel_MboxBoxCell (
	@CELL_LIST	varchar(500),
	@MBOX_NO    varchar(20)
)AS
BEGIN
	BEGIN TRY
	   BEGIN TRANSACTION;

		IF EXISTS (SELECT * FROM d23_MRUNBOX파일 WHERE MBOX_NO=@MBOX_NO AND NULLIF(AFT_RUNNO,'') IS NOT NULL)
		BEGIN 
			SELECT @MBOX_NO||'는이미 M-RUN구성된 M-BOX입니다';
			COMMIT TRANSACTION;
			RETURN 1;
		END 
		ELSE 
		BEGIN
			DELETE FROM d23_MRUNBOX파일 where cell_no IN (SELECT value  from STRING_SPLIT(@CELL_LIST, ','));
			COMMIT TRANSACTION;
			RETURN 0;
		END
	END TRY
	
	BEGIN CATCH
	    ROLLBACK TRANSACTION;
	    SELECT ERROR_MESSAGE() AS ErrorMessage;
	    RETURN 0;
	END CATCH;
END