/*
* 제조 실적 입력 > Rework > M-BOX 관리 > GenCount
*/
const { ValueType, SelectionStyle, SelectionMode, GridFitStyle } = require('realgrid');
const grid = {
	dataProvider: null,
	gridView: null,
	options: {
		checkBar: { visible: true },
		copy: { enabled: true, singleMode: false },
		//dataDrop: {},
		display: {
			columnMovable: false,
			editItemMerging: false,
			selectionStyle: SelectionStyle.BLOCK,
			selectionMode: SelectionMode.EXTENDED,
			//selectionStyle: SelectionStyle.COLUMNS,
			//selectionMode: SelectionMode.SINGLE,
			fitStyle: GridFitStyle.EVEN_FILL,
		},
		edit: { editable: false },
		//editor: {},
		//filtering: {},
		//filterMode: {},
		//filterPanel: {},
		//fixed: {},
		footer: { visible: false },
		//footers: {},
		//format: {},
		header: { height: 25 },
		//headerSummaries: {},
		//headerSummary: {},
		//hideDeletedRows: {},
		paste: { enabled: false },
		rowIndicator: { visible: true },
		sorting: { enabled: true },
		//sortMode: {},
		stateBar: { visible: false },
   		 filtering: { enabled: true },
	},

	fields: [
		{ fieldName: '상태', dataType: ValueType.TEXT },
		{ fieldName: '등록일시', dataType: ValueType.TEXT },
		{ fieldName: 'mboxNo', dataType: ValueType.TEXT },
		{ fieldName: 'cellNo', dataType: ValueType.TEXT },
		{ fieldName: 'cstNo', dataType: ValueType.TEXT },
		{ fieldName: 'bef차수', dataType: ValueType.TEXT },
		{ fieldName: 'before', dataType: ValueType.TEXT },
		{ fieldName: 'after', dataType: ValueType.TEXT },
		{ fieldName: 'aft차수', dataType: ValueType.TEXT },
		{ fieldName: '수량', dataType: ValueType.NUMBER },
		{ fieldName: '등록자', dataType: ValueType.TEXT },
		// { fieldName: '등록서명', dataType: ValueType.BOOLEAN },
		// { fieldName: '승인자', dataType: ValueType.TEXT },
		// { fieldName: '승인서명', dataType: ValueType.BOOLEAN },
		{ fieldName: '특이사항', dataType: ValueType.TEXT },
		{ fieldName: '구분', dataType: ValueType.TEXT },
	],

	columns: [
		{ name: '상태', fieldName: '상태', width: '150', header: { text: '상태' }},
		{ name: '등록일시', fieldName: '등록일시', width: '150', header: { text: '등록일시' }, autoFilter: true },
		{ name: 'mboxNo', fieldName: 'mboxNo', width: '150', mergeRule: { criteria: "value" }, header: { text: 'M BOX NO' }, autoFilter: true },
		{ name: 'cellNo', fieldName: 'cellNo', width: '300', header: { text: 'CELL NO' }, autoFilter: true },
		{ name: 'cstNo', fieldName: 'cstNo', width: '150', header: { text: 'CST NO' }, autoFilter: true },
		{ name: 'bef차수', fieldName: 'bef차수', width: '150', header: { text: '차수' }, autoFilter: true },
		{ name: 'before', fieldName: 'before', width: '150', header: { text: 'Before' }, autoFilter: true },
		{ name: 'aft차수', fieldName: 'aft차수', width: '150', header: { text: '차수' }, autoFilter: true },
		{ name: 'after', fieldName: 'after', width: '150', header: { text: 'After' }, autoFilter: true },
		{ name: '수량', fieldName: '수량', width: '100', header: { text: '수량' }, numberFormat: "#,##0"},
		{ name: '등록자', fieldName: '등록자', width: '100', header: { text: '담당자' }, autoFilter: true },
		// { name: '등록서명', fieldName: '등록서명', width: '80', header: { text: '서명' }, renderer: {type: "check"}},
		// { name: '승인자', fieldName: '승인자', width: '100', header: { text: '담당자' }},
		// { name: '승인서명', fieldName: '승인서명', width: '80', header: { text: '서명' }, renderer: {type: "check"}},
		{ name: '구분', fieldName: '구분', width: '80', header: { text: '구분' }, autoFilter: true },
		{ name: '특이사항', fieldName: '특이사항', width: '150', header: { text: '특이사항' }, autoFilter: true },
	],

	layout: [
		"상태",
		{
			name: "작업현황",
			direction: "horizontal",
			items: ["등록일시", "mboxNo","cellNo","cstNo",
				{
					name: "RUN NO",
					direction: "horizontal",
					items: ["bef차수","before","aft차수", "after"],
					header:{ text: "RUN NO" },
				},
				"수량",
			],			
			header:{ text: "작업현황" },
		},
		"등록자",
		// {
		// 	name: "등록",
		// 	direction: "horizontal",
		// 	items: ["등록자", "등록서명"],
		// 	header:{ text: "등록" },
		// },
		// {
		// 	name: "승인",
		// 	direction: "horizontal",
		// 	items: ["승인자", "승인서명"],
		// 	header:{ text: "승인" },
		// },
		"구분",
		"특이사항",
	],
}
module.exports = grid;