/*
* 기준정보 > 공정별 불량코드 등록
*/
const { ValueType } = require('realgrid');

dupCallback=function(grid, dataCell){
	var ret = {}
	if(grid.getValue(dataCell.index.dataRow,"rank")!=1)
		ret.styleName='edit';

	return ret;
};

const grid = {

	options: {
		checkBar: { visible: false, exclusive: false,syncHeadCheck:true },
		copy: { enabled: true, singleMode: false },
		//dataDrop: {},
		display: { columnMovable: false, editItemMerging: true, fitStyle: "even" },
		edit: { editable: false},
		//editor: {},
		//filtering: {},
		//filterMode: {},
		//filterPanel: {},
		//fixed: {},
		footer: { visible: false },
		//footers: {},
		//format: {},
		header: { height: 25 },
		//headerSummaries: {},
		//headerSummary: {},
		//hideDeletedRows: true,
		//paste: { enabled: true },
		//rowIndicator: { visible: true },
		sorting: { enabled: false },
		//sortMode: {},
		//stateBar: { visible: true },
		//summaryMode: {},
	},
	fields:[
		{ fieldName: '작업일자', dataType: ValueType.TEXT },
		{ fieldName: 'eqpId', dataType: ValueType.TEXT },
		{ fieldName: '근무조', dataType: ValueType.TEXT },
		{ fieldName: '검사자', dataType: ValueType.TEXT },
		{ fieldName: 'runId', dataType: ValueType.TEXT },
		{ fieldName: 'cellId', dataType: ValueType.TEXT },
		{ fieldName: 'startTime', dataType: ValueType.TEXT },
		{ fieldName: 'endTime', dataType: ValueType.TEXT },
		{ fieldName: 'stepNo', dataType: ValueType.TEXT },
		{ fieldName: 'imageNo', dataType: ValueType.TEXT },
		{ fieldName: 'posX', dataType: ValueType.TEXT },
		{ fieldName: 'posY', dataType: ValueType.TEXT },
		{ fieldName: 'alignX', dataType: ValueType.TEXT },
		{ fieldName: 'alignY', dataType: ValueType.TEXT },
		{ fieldName: 'alignR', dataType: ValueType.TEXT },
		{ fieldName: 'stage좌', dataType: ValueType.TEXT },
		{ fieldName: 'stage우', dataType: ValueType.TEXT },
		{ fieldName: 'bin1', dataType: ValueType.TEXT },
		{ fieldName: 'bin2', dataType: ValueType.TEXT },
		{ fieldName: '불량사유', dataType: ValueType.TEXT },
		{ fieldName: 'cellRowNo', dataType: ValueType.TEXT },
		{ fieldName: 'maxCellRowNo', dataType: ValueType.TEXT },
		{ fieldName: '검사결과양품', dataType: ValueType.TEXT },
		{ fieldName: '검사결과불량', dataType: ValueType.TEXT },
		{ fieldName: 'rank', dataType: ValueType.TEXT },
	],

	columns: [
		{ name: '작업일자', fieldName: '작업일자', width: '100', header: { text: '작업일자' }, autoFilter: true,styleCallback:dupCallback },
		{ name: 'eqpId', fieldName: 'eqpId', width: '80', header: { text: 'EQP ID' }, autoFilter: true,styleCallback:dupCallback},
		{ name: '근무조', fieldName: '근무조', width: '80', header: { text: '근무조' }, autoFilter: true,styleCallback:dupCallback},
		{ name: '검사자', fieldName: '검사자', width: '80', header: { text: '검사자' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'runId', fieldName: 'runId', width: '150', header: { text: 'RUN NO' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'cellId', fieldName: 'cellId', width: '250', header: { text: 'CELL ID' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'startTime', fieldName: 'startTime', width: '200', header: { text: '시작시각' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'endTime', fieldName: 'endTime', width: '200', header: { text: '종료시각' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'stepNo', fieldName: 'stepNo', width: '80', header: { text: 'STEP NO' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'imageNo', fieldName: 'imageNo', width: '100', header: { text: 'IMAGE NO' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'posX', fieldName: 'posX', width: '80', header: { text: 'POS X' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'posY', fieldName: 'posY', width: '80', header: { text: 'POS Y' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'alignX', fieldName: 'alignX', width: '80', header: { text: 'ALIGN X' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'alignY', fieldName: 'alignY', width: '80', header: { text: 'ALIGN Y' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'alignR', fieldName: 'alignR', width: '80', header: { text: 'ALIGN R' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'stage좌', fieldName: 'stage좌', width: '80', header: { text: 'STAGE 좌' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'stage우', fieldName: 'stage우', width: '80', header: { text: 'STAGE 우' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'bin1', fieldName: 'bin1', width: '80', header: { text: 'BIN 1' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'bin2', fieldName: 'bin2', width: '80', header: { text: 'BIN 2' }, autoFilter: true,styleCallback:dupCallback},
		{ name: '불량사유', fieldName: '불량사유', width: '100', header: { text: '불량사유' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'cellRowNo', fieldName: 'cellRowNo', width: '120', header: { text: 'CELL ROW NO' }, autoFilter: true,styleCallback:dupCallback},
		{ name: 'maxCellRowNo', fieldName: 'maxCellRowNo', width: '150', header: { text: 'MAX CELL ROW NO' }, autoFilter: true,styleCallback:dupCallback},
		{ name: '검사결과양품', fieldName: '검사결과양품', width: '120', header: { text: '검사결과 양품' }, autoFilter: true,styleCallback:dupCallback},
		{ name: '검사결과불량', fieldName: '검사결과불량', width: '120', header: { text: '검사결과 불량' }, autoFilter: true,styleCallback:dupCallback},
	],
	layoutECI:[
		"작업일자",
		"eqpId",
		"근무조",
		"검사자",
		"runId",
		"cellId",
		"startTime",
		"endTime",
		"stepNo",
		"imageNo",
		"posX",
		"posY",
		"alignX",
		"alignY",
		"alignR",
		"stage좌",
		"stage우",
		"bin1",
		"bin2",
		"불량사유",
		"cellRowNo",
		"maxCellRowNo"
	],
	layoutVRS:[
		"작업일자",
		"eqpId",
		"근무조",
		"검사자",
		"runId",
		"cellId",
		"startTime",
		"endTime",
		"stepNo",
		"imageNo",
		"posX",
		"posY",
		"alignX",
		"alignY",
		"alignR",
		"검사결과양품",
		"검사결과불량",
		"bin1",
		"bin2",
		"불량사유",
		"cellRowNo"
	]
}

module.exports = grid;