/*
* 기준정보 > 공정별 불량코드 등록
*/
const { ValueType } = require('realgrid');

const grid = {

	options: {
		checkBar: { visible: false, exclusive: false,syncHeadCheck:true },
		copy: { enabled: true, singleMode: false },
		//dataDrop: {},
		display: { columnMovable: false, editItemMerging: true, fitStyle: "evenFill" },
		edit: { editable: false},
		//editor: {},
		//filtering: {},
		//filterMode: {},
		//filterPanel: {},
		//fixed: {},
		footer: { visible: false },
		//footers: {},
		//format: {},
		header: { height: 25 },
		//headerSummaries: {},
		//headerSummary: {},
		//hideDeletedRows: true,
		//paste: { enabled: true },
		//rowIndicator: { visible: true },
		sorting: { enabled: false },
		//sortMode: {},
		//stateBar: { visible: true },
		//summaryMode: {},
	},
	fields: [
		{ fieldName: '작업일자', dataType: ValueType.TEXT },
		{ fieldName: 'eqpId', dataType: ValueType.TEXT },
		{ fieldName: 'model', dataType: ValueType.TEXT },
		{ fieldName: 'runId', dataType: ValueType.TEXT },
		{ fieldName: 'startDate', dataType: ValueType.TEXT },
		{ fieldName: 'startTime', dataType: ValueType.TEXT },
		{ fieldName: 'endDate', dataType: ValueType.TEXT },
		{ fieldName: 'endTime', dataType: ValueType.TEXT },
		{ fieldName: 'timeDiff', dataType: ValueType.TEXT },
		{ fieldName: '검사수', dataType: ValueType.TEXT },
		{ fieldName: '투입수량', dataType: ValueType.TEXT },
		{ fieldName: '중복', dataType: ValueType.TEXT },
		{ fieldName: '중복SumBin1', dataType: ValueType.TEXT },
		{ fieldName: '중복SumBin2', dataType: ValueType.TEXT },
		{ fieldName: '중복제외Bin1', dataType: ValueType.TEXT },
		{ fieldName: '중복제외Bin2', dataType: ValueType.TEXT },
		{ fieldName: '양품수량', dataType: ValueType.TEXT },
		{ fieldName: '중복Loss수량', dataType: ValueType.TEXT },
		{ fieldName: '중복Out수량', dataType: ValueType.TEXT },
		{ fieldName: '중복메뉴얼수량', dataType: ValueType.TEXT },
		{ fieldName: '중복제외Out수량', dataType: ValueType.TEXT },
	],

	columns: [
		{ name: '작업일자', fieldName: '작업일자', width: '100', header: { text: '작업일자' }, autoFilter: true },
		{ name: 'eqpId', fieldName: 'eqpId', width: '80', header: { text: 'EQP ID' }, autoFilter: true },
		{ name: 'model', fieldName: 'model', width: '80', header: { text: 'MODEL' }, autoFilter: true },
		{ name: 'runId', fieldName: 'runId', width: '180', header: { text: 'RUN NO' }, autoFilter: true },
		{ name: 'startTime', fieldName: 'startTime', width: '180', header: { text: '시작시각' }, autoFilter: true },
		{ name: 'endTime', fieldName: 'endTime', width: '180', header: { text: '종료시각' }, autoFilter: true },
		{ name: 'timeDiff', fieldName: 'timeDiff', width: '150', header: { text: '소요' }, autoFilter: true },
		{ name: '검사수', fieldName: '검사수', width: '80', header: { text: '검사수' }, autoFilter: true },
		{ name: '투입수량', fieldName: '투입수량', width: '80', header: { text: '투입수량' }, autoFilter: true },
		{ name: '중복', fieldName: '중복', width: '50', header: { text: '중복' }, autoFilter: true },
		{ name: '중복SumBin1', fieldName: '중복SumBin1', width: '100', header: { text: '중복SumBin1' }, autoFilter: true },
		{ name: '중복SumBin2', fieldName: '중복SumBin2', width: '100', header: { text: '중복SumBin2' }, autoFilter: true },
		{ name: '중복제외Bin1', fieldName: '중복제외Bin1', width: '100', header: { text: '중복제외Bin1' }, autoFilter: true },
		{ name: '중복제외Bin2', fieldName: '중복제외Bin2', width: '100', header: { text: '중복제외Bin2' }, autoFilter: true },
		{ name: '양품수량', fieldName: '양품수량', width: '80', header: { text: '양품수량' }, autoFilter: true },
		{ name: '중복Loss수량', fieldName: '중복Loss수량', width: '100', header: { text: '중복Loss수량' }, autoFilter: true },
		{ name: '중복Out수량', fieldName: '중복Out수량', width: '100', header: { text: '중복Out수량' }, autoFilter: true },
		{ name: '중복메뉴얼수량', fieldName: '중복메뉴얼수량', width: '120', header: { text: '중복메뉴얼수량' }, autoFilter: true },
		{ name: '중복제외Out수량', fieldName: '중복제외Out수량', width: '120', header: { text: '중복제외Out수량' }, autoFilter: true },
	],
	layoutECI:[
		"작업일자",
		"eqpId",
		"model",
		"runId",
		"startTime",
		"endTime",
		"timeDiff",
		"검사수",
		"투입수량",
		"중복",
		"중복SumBin1",
		"중복SumBin2",
		"중복제외Bin1",
		"중복제외Bin2",
		"양품수량"
	],
	layoutVRS:[
		"작업일자",
		"eqpId",
		"model",
		"runId",
		"startTime",
		"endTime",
		"timeDiff",
		"검사수",
		"투입수량",
		"중복",
		"중복Loss수량",
		"중복Out수량",
		"중복메뉴얼수량",
		"중복제외Out수량"
	]
}

module.exports = grid;