/*
* 제조 실적 입력 > Rework > M-RUN 발행 > RUN CARD
*/
const { ValueType, SelectionStyle, SelectionMode, GridFitStyle } = require('realgrid');
const { rgDisplayDate, rgDisplayTime} = require('@/utils/dateUtils.js'); 
const grid = {
	dataProvider: null,
	gridView: null,
	options: {
		checkBar: { visible: true },
		copy: { enabled: true, singleMode: false },
		//dataDrop: {},
		display: {
			columnMovable: false,
			editItemMerging: false,
			// selectionStyle: SelectionStyle.SINGLE_ROW,
			// selectionMode: SelectionMode.SINGLE,
			fitStyle: "fill", //GridFitStyle.NONE,
		},
		edit: { editable: false },
		//editor: {},
		//filtering: {},
		//filterMode: {},
		//filterPanel: {},
		//fixed: {},
		footer: { visible: false },
		//footers: {},
		//format: {},
		header: { height: 25 },
		//headerSummaries: {},
		//headerSummary: {},
		//hideDeletedRows: {},
		paste: { enabled: false },
		rowIndicator: { visible: true },
		sorting: { enabled: false },
		//sortMode: {},
		stateBar: { visible: true },
		//summaryMode: {},
	},

	fields: [
		{ fieldName: '등록일시', dataType: ValueType.TEXT },
		{ fieldName: 'runNo', dataType: ValueType.TEXT },
		{ fieldName: '내용', dataType: ValueType.TEXT },
		{ fieldName: '제품inch', dataType: ValueType.TEXT },
		{ fieldName: '제품버젼', dataType: ValueType.TEXT },
		{ fieldName: '제품규격', dataType: ValueType.TEXT },
		{ fieldName: 'cell수', dataType: ValueType.NUMBER },
		{ fieldName: '발행자', dataType: ValueType.TEXT },
		//{ fieldName: '승인자', dataType: ValueType.TEXT },
		{ fieldName: '입고일자', dataType: ValueType.TEXT },
		{ fieldName: '입고시각', dataType: ValueType.TEXT },
		{ fieldName: '작업일자', dataType: ValueType.TEXT },
		{ fieldName: '작업시각', dataType: ValueType.TEXT },
		{ fieldName: '특기사항', dataType: ValueType.TEXT },
		{ fieldName: 'box-no1', dataType: ValueType.TEXT },
		{ fieldName: '수량1', dataType: ValueType.NUMBER},
		{ fieldName: 'box-no2', dataType: ValueType.TEXT },
		{ fieldName: '수량2', dataType: ValueType.NUMBER },
		{ fieldName: 'box-no3', dataType: ValueType.TEXT },
		{ fieldName: '수량3', dataType: ValueType.NUMBER },
		{ fieldName: 'box-no4', dataType: ValueType.TEXT },
		{ fieldName: '수량4', dataType: ValueType.NUMBER },
		{ fieldName: 'box-no5', dataType: ValueType.TEXT },
		{ fieldName: '수량5', dataType: ValueType.NUMBER },
		{ fieldName: 'box-no6', dataType: ValueType.TEXT },
		{ fieldName: '수량6', dataType: ValueType.NUMBER },
		{ fieldName: 'box-no7', dataType: ValueType.TEXT },
		{ fieldName: '수량7', dataType: ValueType.NUMBER },
		{ fieldName: 'box-no8', dataType: ValueType.TEXT },
		{ fieldName: '수량8', dataType: ValueType.NUMBER },
	],

	columns: [
		{ name: '등록일시', fieldName: '등록일시', width: '100', header: { text: '승인일자' }},
		{ name: 'runNo', fieldName: 'runNo', width: '150', header: { text: 'RUN NO' }, autoFilter: true},
		{ name: '내용', fieldName: '내용', width: '80', header: { text: '모델' }},
		{ name: '제품inch', fieldName: '제품inch', width: '80', header: { text: 'Inch' }},
		{ name: '제품버젼', fieldName: '제품버젼', width: '80', header: { text: '버전' }},
		{ name: '제품규격', fieldName: '제품규격', width: '180', header: { text: '규격' }},
		{ name: 'cell수', fieldName: 'cell수', width: '80', header: { text: 'Cell수' }, numberFormat: "#,##0"},
		{ name: '입고일자', fieldName: '입고일자', width: '100', header: { text: 'Date' },displayCallback:rgDisplayDate},
		{ name: '입고시각', fieldName: '입고시각', width: '100', header: { text: 'Time' },displayCallback:rgDisplayTime},
		{ name: '작업일자', fieldName: '작업일자', width: '100', header: { text: 'Date' },displayCallback:rgDisplayDate},
		{ name: '작업시각', fieldName: '작업시각', width: '100', header: { text: 'Time' },displayCallback:rgDisplayTime},
		{ name: '발행자', fieldName: '발행자', width: '80', header: { text: '담당자' }},
		//{ name: '승인자', fieldName: '승인자', width: '80', header: { text: '승인자' }},
		{ name: '특기사항', fieldName: '특기사항', width: '180', header: { text: '특이사항' }, styleName: 'edit tl', placeHolder: "특이사항을 입력 후 저장 버튼 클릭 하세요..." , },
		{ name: 'box-no1', fieldName: 'box-no1', width: '120', header: { text: 'BOX-NO1' }},
		{ name: '수량1', fieldName: '수량1', width: '60', header: { text: '수량1' }, numberFormat: "#,##0"},

		{ name: 'box-no2', fieldName: 'box-no2', width: '120', header: { text: 'BOX-NO2' }},
		{ name: '수량2', fieldName: '수량2', width: '60', header: { text: '수량2' }, numberFormat: "#,##0"},

		{ name: 'box-no3', fieldName: 'box-no3', width: '120', header: { text: 'BOX-NO3' }},
		{ name: '수량3', fieldName: '수량3', width: '60', header: { text: '수량3' }, numberFormat: "#,##0"},

		{ name: 'box-no4', fieldName: 'box-no4', width: '120', header: { text: 'BOX-NO4' }},
		{ name: '수량4', fieldName: '수량4', width: '60', header: { text: '수량4' }, numberFormat: "#,##0"},

		{ name: 'box-no5', fieldName: 'box-no5', width: '120', header: { text: 'BOX-NO5' }},
		{ name: '수량5', fieldName: '수량5', width: '60', header: { text: '수량5' }, numberFormat: "#,##0"},

		{ name: 'box-no6', fieldName: 'box-no6', width: '120', header: { text: 'BOX-NO6' }},
		{ name: '수량1', fieldName: '수량6', width: '60', header: { text: '수량6' }, numberFormat: "#,##0"},

		{ name: 'box-no7', fieldName: 'box-no7', width: '120', header: { text: 'BOX-NO7' }},
		{ name: '수량7', fieldName: '수량7', width: '60', header: { text: '수량7' }, numberFormat: "#,##0"},

		{ name: 'box-no8', fieldName: 'box-no8', width: '120', header: { text: 'BOX-NO8' }},
		{ name: '수량8', fieldName: '수량8', width: '60', header: { text: '수량8' }, numberFormat: "#,##0"},
	],
}
module.exports = grid;