/*
 * 제조 실적 입력 > 포장/출하 > 내포장 실적 > [MANUAL] PACK
 */
const { ValueType, SelectionStyle, SelectionMode, GridFitStyle } = require('realgrid');
const { rgDisplayDateTime1, rgDisplayDate, rgDisplayTime3 } = require('@/utils/dateUtils');

const grid = {
  options: {
    checkBar: { visible: true ,exclusive:true },
    copy: { enabled: true, singleMode: false },
    display: {
      columnMovable: false,
			editItemMerging: false,
			selectionStyle: SelectionStyle.BLOCK,
			selectionMode: SelectionMode.EXTENDED,
      //emptyMessage: '조회된 데이터가 없습니다.',
      fitStyle: 'even',
      //hscrollBar: true,
      showEmptyMessage: true,
      minRowHeight: 30,
      rowHeight : -1,
    },
    edit: { editable: false },
    footers: { visible: false },
    paste: { enabled: false },
    rowIndicator: { visible: true },
    sorting: { enabled: true },
    stateBar: { visible: false },
    filtering: { enabled: true },
    fixed: { colCount: 10 },
  },

  fields: [
    { fieldName: '발행횟수', dataType: ValueType.NUMBER },
    { fieldName: 'pack상태', dataType: ValueType.TEXT },
    //{ fieldName: '발행구분', dataType: ValueType.TEXT },
    { fieldName: '특이사항', dataType: ValueType.TEXT },
    { fieldName: '생성시각', dataType: ValueType.TEXT },
    { fieldName: 'packQrno', dataType: ValueType.TEXT },
    { fieldName: '대포장Qrno', dataType: ValueType.TEXT },
    { fieldName: '유효기간', dataType: ValueType.NUMBER },
    { fieldName: '유효일자', dataType: ValueType.TEXT },
    { fieldName: 'cell수량', dataType: ValueType.NUMBER },
    { fieldName: '발행자', dataType: ValueType.TEXT },
    { fieldName: '폐기사유', dataType: ValueType.TEXT },
    { fieldName: 'originNo1', dataType: ValueType.TEXT },
    { fieldName: 'cell수량1', dataType: ValueType.NUMBER },
    { fieldName: 'originNo2', dataType: ValueType.TEXT },
    { fieldName: 'cell수량2', dataType: ValueType.NUMBER },
    { fieldName: 'originNo3', dataType: ValueType.TEXT },
    { fieldName: 'cell수량3', dataType: ValueType.NUMBER },
    { fieldName: 'originNo4', dataType: ValueType.TEXT },
    { fieldName: 'cell수량4', dataType: ValueType.NUMBER },
    { fieldName: 'originNo5', dataType: ValueType.TEXT },
    { fieldName: 'cell수량5', dataType: ValueType.NUMBER },
    { fieldName: 'originNo6', dataType: ValueType.TEXT },
    { fieldName: 'cell수량6', dataType: ValueType.NUMBER },
    { fieldName: 'originNo7', dataType: ValueType.TEXT },
    { fieldName: 'cell수량7', dataType: ValueType.NUMBER },
    { fieldName: 'originNo8', dataType: ValueType.TEXT },
    { fieldName: 'cell수량8', dataType: ValueType.NUMBER },
    { fieldName: 'originNo9', dataType: ValueType.TEXT },
    { fieldName: 'cell수량9', dataType: ValueType.NUMBER },
    { fieldName: 'originNo10', dataType: ValueType.TEXT },
    { fieldName: 'cell수량10', dataType: ValueType.NUMBER },
    { fieldName: 'originNo11', dataType: ValueType.TEXT },
    { fieldName: 'cell수량11', dataType: ValueType.NUMBER },
    { fieldName: 'originNo12', dataType: ValueType.TEXT },
    { fieldName: 'cell수량12', dataType: ValueType.NUMBER },
    { fieldName: 'originNo13', dataType: ValueType.TEXT },
    { fieldName: 'cell수량13', dataType: ValueType.NUMBER },
    { fieldName: 'originNo14', dataType: ValueType.TEXT },
    { fieldName: 'cell수량14', dataType: ValueType.NUMBER },
    { fieldName: 'originNo15', dataType: ValueType.TEXT },
    { fieldName: 'cell수량15', dataType: ValueType.NUMBER },
    { fieldName: 'originNo16', dataType: ValueType.TEXT },
    { fieldName: 'cell수량16', dataType: ValueType.NUMBER },
    { fieldName: 'originNo17', dataType: ValueType.TEXT },
    { fieldName: 'cell수량17', dataType: ValueType.NUMBER },
    { fieldName: 'originNo18', dataType: ValueType.TEXT },
    { fieldName: 'cell수량18', dataType: ValueType.NUMBER },
    { fieldName: 'originNo19', dataType: ValueType.TEXT },
    { fieldName: 'cell수량19', dataType: ValueType.NUMBER },
    { fieldName: 'originNo20', dataType: ValueType.TEXT },
    { fieldName: 'cell수량20', dataType: ValueType.NUMBER },
    { fieldName: 'si의뢰일자', dataType: ValueType.TEXT },
    { fieldName: 'si의뢰차수', dataType: ValueType.TEXT },
    { fieldName: 'disposal', dataType: ValueType.TEXT },
  ],

  columns: [
    { name: '발행횟수', fieldName: '발행횟수', width: '80', header: { text: '발행수' }, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'pack상태', fieldName: 'pack상태', width: '100', header: { text: '상태' }, autoFilter: true, styleName: 'tl' },
    //{ name: '발행구분', fieldName: '발행구분', width: '80', header: { text: '발행구분' }, autoFilter: true, styleName: 'tl' },
    // { name: '특이사항', fieldName: '특이사항', width: '80', header: { text: '특이 사항' }, autoFilter: true, styleName: 'tl'
    //         ,styles: {  text: {wrapText: true, multiLine: true}}
    //         ,dynamicStyles: [{criteria: "value.length > 10", styles: { "textWrap": "explicit", "wordBreak": "break-all" }}]
    //         ,renderer: { type: "html",showTooltip:true },
    //  },
     {
      name: "특이사항",
      fieldName: "특이사항",
      width: 100,
      autoFilter: true,
      styles: {
        textAlignment: "near",
        textWrap: "explicit" // 명시적 줄바꿈 허용
      },
      renderer: { type: "text", showTooltip:true },
      displayCallback: function(grid, index, value) {
        // 10자만 표시 (한글/영문 모두 고려)
        if (!value) return "";
        return value.length > 10 ? value.substring(0, 10) + "..." : value;
      },
    },
    { name: '생성시각', fieldName: '생성시각', width: '150', header: { text: '생성 시각' }, autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDateTime1 },
    { name: 'packQrno', fieldName: 'packQrno', width: '260', header: { text: 'PACK NO' }, autoFilter: true, styleName: 'tl',renderer: {showTooltip:true }, },
    { name: '대포장Qrno', fieldName: '대포장Qrno', width: '260', header: { text: 'BOX NO' }, autoFilter: true, styleName: 'tl',renderer: {showTooltip:true }, },
    { name: '유효기간', fieldName: '유효기간', width: '60', header: { text: '기간' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '유효일자', fieldName: '유효일자', width: '100', header: { text: '유효일자' }, autoFilter: true, styleName: 'tl', displayCallback: rgDisplayDate },
    { name: 'cell수량', fieldName: 'cell수량', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: '발행자', fieldName: '발행자', width: '90', header: { text: '발행자' }, autoFilter: true, styleName: 'tl' },
    { name: '폐기사유', fieldName: '폐기사유', width: '120', header: { text: '폐기사유' }, visible: false, autoFilter: true, styleName: 'tl' },
    { name: 'originNo1', fieldName: 'originNo1', width: '170', fitStyle: 'even', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량1', fieldName: 'cell수량1', width: '60', fitStyle: 'even', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo2', fieldName: 'originNo2', width: '160', fitStyle: 'even', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량2', fieldName: 'cell수량2', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo3', fieldName: 'originNo3', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량3', fieldName: 'cell수량3', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo4', fieldName: 'originNo4', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량4', fieldName: 'cell수량4', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo5', fieldName: 'originNo5', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량5', fieldName: 'cell수량5', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo6', fieldName: 'originNo6', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량6', fieldName: 'cell수량6', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo7', fieldName: 'originNo7', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량7', fieldName: 'cell수량7', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo8', fieldName: 'originNo8', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량8', fieldName: 'cell수량8', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo9', fieldName: 'originNo9', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량9', fieldName: 'cell수량9', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo10', fieldName: 'originNo10', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량10', fieldName: 'cell수량10', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo11', fieldName: 'originNo11', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량11', fieldName: 'cell수량11', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo12', fieldName: 'originNo12', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량12', fieldName: 'cell수량12', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo13', fieldName: 'originNo13', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량13', fieldName: 'cell수량13', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo14', fieldName: 'originNo14', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량14', fieldName: 'cell수량14', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo15', fieldName: 'originNo15', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량15', fieldName: 'cell수량15', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo16', fieldName: 'originNo16', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량16', fieldName: 'cell수량16', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo17', fieldName: 'originNo17', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량17', fieldName: 'cell수량17', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo18', fieldName: 'originNo18', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량18', fieldName: 'cell수량18', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo19', fieldName: 'originNo19', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량19', fieldName: 'cell수량19', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'originNo20', fieldName: 'originNo20', width: '150', header: { text: 'NO' }, autoFilter: true, styleName: 'tl' },
    { name: 'cell수량20', fieldName: 'cell수량20', width: '60', header: { text: '수량' }, autoFilter: true, numberFormat: '#,###.###', styleName: 'tr' },
    { name: 'disposal', fieldName: 'disposal', width: '120', header: { text: '폐기필요' }, visible: false, autoFilter: true, styleName: 'tl' },
  ],

  layout: [
    '발행횟수',
    'pack상태',
    //'발행구분',
    '특이사항',
    '생성시각',
    'packQrno',
    '대포장Qrno',
    '유효기간',
    '유효일자',
    'cell수량',
    '발행자',
    '폐기사유',
    'disposal',
    // {
    //   name: 'PACK',
    //   direction: 'horizontal',
    //   items: ['발행횟수', 'pack상태', '발행구분', '특이사항', '생성시각', 'packQrno', '대포장Qrno', '유효기간', '유효일자', 'cell수량', '발행자', '폐기사유'],
    //   header: { text: 'PACK' },
    // },
    {
      name: 'ORIGIN1',
      direction: 'horizontal',
      items: ['originNo1', 'cell수량1'],
      header: { text: 'ORIGIN1' },
    },
    {
      name: 'ORIGIN2',
      direction: 'horizontal',
      items: ['originNo2', 'cell수량2'],
      header: { text: 'ORIGIN2' },
    },
    {
      name: 'ORIGIN3',
      direction: 'horizontal',
      items: ['originNo3', 'cell수량3'],
      header: { text: 'ORIGIN3' },
    },
    {
      name: 'ORIGIN4',
      direction: 'horizontal',
      items: ['originNo4', 'cell수량4'],
      header: { text: 'ORIGIN4' },
    },
    {
      name: 'ORIGIN5',
      direction: 'horizontal',
      items: ['originNo5', 'cell수량5'],
      header: { text: 'ORIGIN5' },
    },
    {
      name: 'ORIGIN6',
      direction: 'horizontal',
      items: ['originNo6', 'cell수량6'],
      header: { text: 'ORIGIN6' },
    },
    {
      name: 'ORIGIN7',
      direction: 'horizontal',
      items: ['originNo7', 'cell수량7'],
      header: { text: 'ORIGIN7' },
    },
    {
      name: 'ORIGIN8',
      direction: 'horizontal',
      items: ['originNo8', 'cell수량8'],
      header: { text: 'ORIGIN8' },
    },
    {
      name: 'ORIGIN9',
      direction: 'horizontal',
      items: ['originNo9', 'cell수량9'],
      header: { text: 'ORIGIN9' },
    },
    {
      name: 'ORIGIN10',
      direction: 'horizontal',
      items: ['originNo10', 'cell수량10'],
      header: { text: 'ORIGIN10' },
    },
    {
      name: 'ORIGIN11',
      direction: 'horizontal',
      items: ['originNo11', 'cell수량11'],
      header: { text: 'ORIGIN11' },
    },
    {
      name: 'ORIGIN12',
      direction: 'horizontal',
      items: ['originNo12', 'cell수량12'],
      header: { text: 'ORIGIN12' },
    },
    {
      name: 'ORIGIN13',
      direction: 'horizontal',
      items: ['originNo13', 'cell수량13'],
      header: { text: 'ORIGIN13' },
    },
    {
      name: 'ORIGIN14',
      direction: 'horizontal',
      items: ['originNo14', 'cell수량14'],
      header: { text: 'ORIGIN14' },
    },
    {
      name: 'ORIGIN15',
      direction: 'horizontal',
      items: ['originNo15', 'cell수량15'],
      header: { text: 'ORIGIN15' },
    },
    {
      name: 'ORIGIN16',
      direction: 'horizontal',
      items: ['originNo16', 'cell수량16'],
      header: { text: 'ORIGIN16' },
    },
    {
      name: 'ORIGIN17',
      direction: 'horizontal',
      items: ['originNo17', 'cell수량17'],
      header: { text: 'ORIGIN17' },
    },
    {
      name: 'ORIGIN18',
      direction: 'horizontal',
      items: ['originNo18', 'cell수량18'],
      header: { text: 'ORIGIN18' },
    },
    {
      name: 'ORIGIN19',
      direction: 'horizontal',
      items: ['originNo19', 'cell수량19'],
      header: { text: 'ORIGIN19' },
    },
    {
      name: 'ORIGIN20',
      direction: 'horizontal',
      items: ['originNo20', 'cell수량20'],
      header: { text: 'ORIGIN20' },
    },
  ],
};

module.exports = grid;
