/*
* 프로세스 플래닝 >  제품 모델 관리 > 모델별_모니터링_기준정보
*/
const { ValueType } = require('realgrid');

const grid = {

	options: {
		checkBar: { visible: true, exclusive: false,syncHeadCheck:true },
		copy: { enabled: true, singleMode: false },
		//dataDrop: {},
		display: { columnMovable: false, editItemMerging: true, fitStyle: "even" },
		edit: { editable: true, commitByCell: true },
		//editor: {},
		//filtering: {},
		//filterMode: {},
		//filterPanel: {},
		//fixed: {},
		footer: { visible: false },
		//footers: {},
		//format: {},
		header: { height: 25 },
		//headerSummaries: {},
		//headerSummary: {},
		hideDeletedRows: true,
		paste: { enabled: true },
		rowIndicator: { visible: true },
		sorting: { enabled: false },
		//sortMode: {},
		stateBar: { visible: true },
		//summaryMode: {},
	},

	fields: [
		{ fieldName: '구분', dataType: ValueType.TEXT },
		{ fieldName: '적재매수', dataType: ValueType.TEXT },
		{ fieldName: 'utg원장두께', dataType: ValueType.TEXT },
		{ fieldName: 'utg원장구분', dataType: ValueType.TEXT },
		{ fieldName: 'utgVersion', dataType: ValueType.TEXT },
		{ fieldName: 'model', dataType: ValueType.TEXT },
		{ fieldName: 'sdc모델명', dataType: ValueType.TEXT },
		{ fieldName: '고객사', dataType: ValueType.TEXT },
		{ fieldName: '대각인치', dataType: ValueType.TEXT },
		{ fieldName: 'modelName', dataType: ValueType.TEXT },
		{ fieldName: 'modelCode', dataType: ValueType.TEXT },
		{ fieldName: '가공치수장변기준', dataType: ValueType.TEXT },
		{ fieldName: '가공치수장변편차', dataType: ValueType.TEXT },
		{ fieldName: '가공치수단변기준', dataType: ValueType.TEXT },
		{ fieldName: '가공치수단변편차', dataType: ValueType.TEXT },
		{ fieldName: 'wpC길이기준', dataType: ValueType.TEXT },
		{ fieldName: 'wpC길이편차', dataType: ValueType.TEXT },
		{ fieldName: 'wpEr기준', dataType: ValueType.TEXT },
		{ fieldName: 'wpEr편차', dataType: ValueType.TEXT },
		{ fieldName: '박리Cst최대적재수량', dataType: ValueType.TEXT },
		{ fieldName: '박리불림조온도기준', dataType: ValueType.TEXT },
		{ fieldName: '박리불림조온도편차', dataType: ValueType.TEXT },
		{ fieldName: '박리박리조온도기준', dataType: ValueType.TEXT },
		{ fieldName: '박리박리조온도편차', dataType: ValueType.TEXT },
		{ fieldName: '박리후세정접촉각Min', dataType: ValueType.TEXT },
		{ fieldName: '박리후세정접촉각Max', dataType: ValueType.TEXT },
		{ fieldName: 'btp접촉각Min', dataType: ValueType.TEXT },
		{ fieldName: 'btp접촉각Max', dataType: ValueType.TEXT },
		{ fieldName: 'btpErSpec기준', dataType: ValueType.TEXT },
		{ fieldName: 'btpErSpec편차', dataType: ValueType.TEXT },
		{ fieldName: 'btpEr내부관리기준', dataType: ValueType.TEXT },
		{ fieldName: 'btpEr내부관리편차', dataType: ValueType.TEXT },
		{ fieldName: '강화CsSpec', dataType: ValueType.TEXT },
		{ fieldName: '강화Cs내부관리기준', dataType: ValueType.TEXT },
		{ fieldName: '강화DolSpecMin', dataType: ValueType.TEXT },
		{ fieldName: '강화DolSpec기준', dataType: ValueType.TEXT },
		{ fieldName: '강화DolSpecMax', dataType: ValueType.TEXT },
		{ fieldName: '강화Dol내부관리기준Min', dataType: ValueType.TEXT },
		{ fieldName: '강화Dol내부관리기준Max', dataType: ValueType.TEXT },
		{ fieldName: '강화Dol내부경고기준Min', dataType: ValueType.TEXT },
		{ fieldName: '강화Dol내부경고기준Max', dataType: ValueType.TEXT },
		{ fieldName: '강화후세정접촉각Min', dataType: ValueType.TEXT },
		{ fieldName: '강화후세정접촉각Max', dataType: ValueType.TEXT },
		{ fieldName: 'atp접촉각Min', dataType: ValueType.TEXT },
		{ fieldName: 'atp접촉각Max', dataType: ValueType.TEXT },
		{ fieldName: 'atpErSpec기준', dataType: ValueType.TEXT },
		{ fieldName: 'atpErSpec편차', dataType: ValueType.TEXT },
		{ fieldName: 'atpEr내부관리기준', dataType: ValueType.TEXT },
		{ fieldName: 'atpEr내부관리편차', dataType: ValueType.TEXT },
		{ fieldName: 'atpCsSpec', dataType: ValueType.TEXT },
		{ fieldName: 'atpCs내부관리기준', dataType: ValueType.TEXT },
		{ fieldName: 'atpDolSpecMin', dataType: ValueType.TEXT },
		{ fieldName: 'atpDolSpec기준', dataType: ValueType.TEXT },
		{ fieldName: 'atpDolSpecMax', dataType: ValueType.TEXT },
		{ fieldName: 'atpDol내부관리기준Min', dataType: ValueType.TEXT },
		{ fieldName: 'atpDol내부관리기준Max', dataType: ValueType.TEXT },
		{ fieldName: 'atpDol내부경고기준Min', dataType: ValueType.TEXT },
		{ fieldName: 'atpDol내부경고기준Max', dataType: ValueType.TEXT },
		{ fieldName: 'agb적용여부', dataType: ValueType.TEXT },
		{ fieldName: 'agbBendingPoints', dataType: ValueType.TEXT },
		{ fieldName: 'agbR', dataType: ValueType.TEXT },
		{ fieldName: 'agbBending시간', dataType: ValueType.TEXT },
		{ fieldName: '검사후세정접촉각Min', dataType: ValueType.TEXT },
		{ fieldName: '검사후세정접촉각Max', dataType: ValueType.TEXT },
		{ fieldName: '검사후세정얼룩', dataType: ValueType.TEXT },
		{ fieldName: 'pfl굴곡강도CenterMaxR', dataType: ValueType.TEXT },
		{ fieldName: 'pfl굴곡강도2mmMaxR', dataType: ValueType.TEXT },
		{ fieldName: 'pfl접촉각배면Min', dataType: ValueType.TEXT },
		{ fieldName: 'pfl접촉각배면기준', dataType: ValueType.TEXT },
		{ fieldName: 'pfl접촉각배면Max', dataType: ValueType.TEXT },
		{ fieldName: 'pfl접촉각전면Min', dataType: ValueType.TEXT },
		{ fieldName: 'pfl접촉각전면기준', dataType: ValueType.TEXT },
		{ fieldName: 'pfl접촉각전면Max', dataType: ValueType.TEXT },
		{ fieldName: 'pflAlgin장변기준', dataType: ValueType.TEXT },
		{ fieldName: 'pflAlgin장변편차', dataType: ValueType.TEXT },
		{ fieldName: 'pflAlgin단변기준', dataType: ValueType.TEXT },
		{ fieldName: 'pflAlgin단변편차', dataType: ValueType.TEXT },
		{ fieldName: 'pflFilm전면자재코드', dataType: ValueType.TEXT },
		{ fieldName: 'pflFilm전면PfVersion', dataType: ValueType.TEXT },
		{ fieldName: 'pflFilm배면자재코드', dataType: ValueType.TEXT },
		{ fieldName: 'pflFilm배면PfVersion', dataType: ValueType.TEXT },
		{ fieldName: 'pflCurlSpec1차', dataType: ValueType.TEXT },
		{ fieldName: 'pflCurlSpec내부관리기준', dataType: ValueType.TEXT },
		{ fieldName: 'pflCurlSpec2차', dataType: ValueType.TEXT },
		{ fieldName: 'filmSize장변', dataType: ValueType.TEXT },
		{ fieldName: 'filmSize단변', dataType: ValueType.TEXT },
		{ fieldName: 'urg출하Size장변', dataType: ValueType.TEXT },
		{ fieldName: 'urg출하Size단변', dataType: ValueType.TEXT },
		{ fieldName: 'urg출하Size두께', dataType: ValueType.TEXT },
		{ fieldName: '변경점', dataType: ValueType.TEXT },
	],
	
	columns: [
		{
			name: 'model', fieldName: 'model', width: '75', header: { text: 'MODEL' }, autoFilter: true,
			styleCallback: function(grid, dataCell){
				var ret = {}
		
				if(dataCell.item.rowState == 'created' || dataCell.item.itemState == 'appending' || dataCell.item.itemState == 'inserting'){
				ret.editable = true;
				} else {
				ret.editable = false;
				}
		
				return ret;
			}
		},
		{ name: '구분', fieldName: '구분', width: '50', header: { text: '구분' }, autoFilter: true },
		{ name: '적재매수', fieldName: '적재매수', width: '80', header: { text: '적재매수' }, autoFilter: true },
		{ name: 'utg원장두께', fieldName: 'utg원장두께', width: '105', header: { text: 'UTG원장두께' }, autoFilter: true },
		{ name: 'utg원장구분', fieldName: 'utg원장구분', width: '105', header: { text: 'UTG원장구분' }, autoFilter: true },
		{ name: 'utgVersion', fieldName: 'utgVersion', width: '150', header: { text: 'UTGVersion' }, autoFilter: true },
		{ name: 'sdc모델명', fieldName: 'sdc모델명', width: '90', header: { text: 'SDC모델명' }, autoFilter: true },
		{ name: '고객사', fieldName: '고객사', width: '80', header: { text: '고객사' }, autoFilter: true },
		{ name: '대각인치', fieldName: '대각인치', width: '120', header: { text: '대각인치' }, autoFilter: true },
		{ name: 'modelName', fieldName: 'modelName', width: '135', header: { text: 'MODELNAME' }, autoFilter: true },
		{ name: 'modelCode', fieldName: 'modelCode', width: '135', header: { text: 'MODELCODE' }, autoFilter: true },
		{ name: '가공치수장변기준', fieldName: '가공치수장변기준', width: '135', header: { text: '가공치수장변기준' }, autoFilter: true },
		{ name: '가공치수장변편차', fieldName: '가공치수장변편차', width: '135', header: { text: '가공치수장변편차' }, autoFilter: true },
		{ name: '가공치수단변기준', fieldName: '가공치수단변기준', width: '135', header: { text: '가공치수단변기준' }, autoFilter: true },
		{ name: '가공치수단변편차', fieldName: '가공치수단변편차', width: '135', header: { text: '가공치수단변편차' }, autoFilter: true },
		{ name: 'wpC길이기준', fieldName: 'wpC길이기준', width: '110', header: { text: 'WPC길이기준' }, autoFilter: true },
		{ name: 'wpC길이편차', fieldName: 'wpC길이편차', width: '110', header: { text: 'WPC길이편차' }, autoFilter: true },
		{ name: 'wpEr기준', fieldName: 'wpEr기준', width: '110', header: { text: 'WPER기준' }, autoFilter: true },
		{ name: 'wpEr편차', fieldName: 'wpEr편차', width: '110', header: { text: 'WPER편차' }, autoFilter: true },
		{ name: '박리Cst최대적재수량', fieldName: '박리Cst최대적재수량', width: '195', header: { text: '박리CST최대적재수량' }, autoFilter: true },
		{ name: '박리불림조온도기준', fieldName: '박리불림조온도기준', width: '195', header: { text: '박리불림조온도기준' }, autoFilter: true },
		{ name: '박리불림조온도편차', fieldName: '박리불림조온도편차', width: '195', header: { text: '박리불림조온도편차' }, autoFilter: true },
		{ name: '박리박리조온도기준', fieldName: '박리박리조온도기준', width: '195', header: { text: '박리박리조온도기준' }, autoFilter: true },
		{ name: '박리박리조온도편차', fieldName: '박리박리조온도편차', width: '195', header: { text: '박리박리조온도편차' }, autoFilter: true },
		{ name: '박리후세정접촉각Min', fieldName: '박리후세정접촉각Min', width: '210', header: { text: '박리후세정접촉각MIN' }, autoFilter: true },
		{ name: '박리후세정접촉각Max', fieldName: '박리후세정접촉각Max', width: '210', header: { text: '박리후세정접촉각MAX' }, autoFilter: true },
		{ name: 'btp접촉각Min', fieldName: 'btp접촉각Min', width: '120', header: { text: 'BTP접촉각MIN' }, autoFilter: true },
		{ name: 'btp접촉각Max', fieldName: 'btp접촉각Max', width: '120', header: { text: 'BTP접촉각MAX' }, autoFilter: true },
		{ name: 'btpErSpec기준', fieldName: 'btpErSpec기준', width: '180', header: { text: 'BTPERSPEC기준' }, autoFilter: true },
		{ name: 'btpErSpec편차', fieldName: 'btpErSpec편차', width: '180', header: { text: 'BTPERSPEC편차' }, autoFilter: true },
		{ name: 'btpEr내부관리기준', fieldName: 'btpEr내부관리기준', width: '195', header: { text: 'BTPER내부관리기준' }, autoFilter: true },
		{ name: 'btpEr내부관리편차', fieldName: 'btpEr내부관리편차', width: '195', header: { text: 'BTPER내부관리편차' }, autoFilter: true },
		{ name: '강화CsSpec', fieldName: '강화CsSpec', width: '120', header: { text: '강화CSSPEC' }, autoFilter: true },
		{ name: '강화Cs내부관리기준', fieldName: '강화Cs내부관리기준', width: '180', header: { text: '강화CS내부관리기준' }, autoFilter: true },
		{ name: '강화DolSpecMin', fieldName: '강화DolSpecMin', width: '180', header: { text: '강화DOLSPECMIN' }, autoFilter: true },
		{ name: '강화DolSpec기준', fieldName: '강화DolSpec기준', width: '180', header: { text: '강화DOLSPEC기준' }, autoFilter: true },
		{ name: '강화DolSpecMax', fieldName: '강화DolSpecMax', width: '180', header: { text: '강화DOLSPECMAX' }, autoFilter: true },
		{ name: '강화Dol내부관리기준Min', fieldName: '강화Dol내부관리기준Min', width: '225', header: { text: '강화DOL내부관리기준MIN' }, autoFilter: true },
		{ name: '강화Dol내부관리기준Max', fieldName: '강화Dol내부관리기준Max', width: '225', header: { text: '강화DOL내부관리기준MAX' }, autoFilter: true },
		{ name: '강화Dol내부경고기준Min', fieldName: '강화Dol내부경고기준Min', width: '240', header: { text: '강화DOL내부경고기준MIN' }, autoFilter: true },
		{ name: '강화Dol내부경고기준Max', fieldName: '강화Dol내부경고기준Max', width: '240', header: { text: '강화DOL내부경고기준MAX' }, autoFilter: true },
		{ name: '강화후세정접촉각Min', fieldName: '강화후세정접촉각Min', width: '240', header: { text: '강화후세정접촉각MIN' }, autoFilter: true },
		{ name: '강화후세정접촉각Max', fieldName: '강화후세정접촉각Max', width: '240', header: { text: '강화후세정접촉각MAX' }, autoFilter: true },
		{ name: 'atp접촉각Min', fieldName: 'atp접촉각Min', width: '180', header: { text: 'ATP접촉각MIN' }, autoFilter: true },
		{ name: 'atp접촉각Max', fieldName: 'atp접촉각Max', width: '180', header: { text: 'ATP접촉각MAX' }, autoFilter: true },
		{ name: 'atpErSpec기준', fieldName: 'atpErSpec기준', width: '195', header: { text: 'ATPERSPEC기준' }, autoFilter: true },
		{ name: 'atpErSpec편차', fieldName: 'atpErSpec편차', width: '195', header: { text: 'ATPERSPEC편차' }, autoFilter: true },
		{ name: 'atpEr내부관리기준', fieldName: 'atpEr내부관리기준', width: '225', header: { text: 'ATPER내부관리기준' }, autoFilter: true },
		{ name: 'atpEr내부관리편차', fieldName: 'atpEr내부관리편차', width: '225', header: { text: 'ATPER내부관리편차' }, autoFilter: true },
		{ name: 'atpCsSpec', fieldName: 'atpCsSpec', width: '150', header: { text: 'ATPCSSPEC' }, autoFilter: true },
		{ name: 'atpCs내부관리기준', fieldName: 'atpCs내부관리기준', width: '195', header: { text: 'ATPCS내부관리기준' }, autoFilter: true },
		{ name: 'atpDolSpecMin', fieldName: 'atpDolSpecMin', width: '195', header: { text: 'ATPDOLSPECMIN' }, autoFilter: true },
		{ name: 'atpDolSpec기준', fieldName: 'atpDolSpec기준', width: '195', header: { text: 'ATPDOLSPEC기준' }, autoFilter: true },
		{ name: 'atpDolSpecMax', fieldName: 'atpDolSpecMax', width: '195', header: { text: 'ATPDOLSPECMAX' }, autoFilter: true },
		{ name: 'atpDol내부관리기준Min', fieldName: 'atpDol내부관리기준Min', width: '240', header: { text: 'ATPDOL내부관리기준MIN' }, autoFilter: true },
		{ name: 'atpDol내부관리기준Max', fieldName: 'atpDol내부관리기준Max', width: '240', header: { text: 'ATPDOL내부관리기준MAX' }, autoFilter: true },
		{ name: 'atpDol내부경고기준Min', fieldName: 'atpDol내부경고기준Min', width: '255', header: { text: 'ATPDOL내부경고기준MIN' }, autoFilter: true },
		{ name: 'atpDol내부경고기준Max', fieldName: 'atpDol내부경고기준Max', width: '255', header: { text: 'ATPDOL내부경고기준MAX' }, autoFilter: true },
		{ name: 'agb적용여부', fieldName: 'agb적용여부', width: '105', header: { text: 'AGB적용여부' }, autoFilter: true },
		{ name: 'agbBendingPoints', fieldName: 'agbBendingPoints', width: '225', header: { text: 'AGBBendingPoints' }, autoFilter: true },
		{ name: 'agbR', fieldName: 'agbR', width: '60', header: { text: 'AGBR' }, autoFilter: true },
		{ name: 'agbBending시간', fieldName: 'agbBending시간', width: '165', header: { text: 'AGBBending시간' }, autoFilter: true },
		{ name: '검사후세정접촉각Min', fieldName: '검사후세정접촉각Min', width: '240', header: { text: '검사후세정접촉각MIN' }, autoFilter: true },
		{ name: '검사후세정접촉각Max', fieldName: '검사후세정접촉각Max', width: '240', header: { text: '검사후세정접촉각MAX' }, autoFilter: true },
		{ name: '검사후세정얼룩', fieldName: '검사후세정얼룩', width: '150', header: { text: '검사후세정얼룩' }, autoFilter: true },
		{ name: 'pfl굴곡강도CenterMaxR', fieldName: 'pfl굴곡강도CenterMaxR', width: '270', header: { text: 'PFL굴곡강도CenterMAXR' }, autoFilter: true },
		{ name: 'pfl굴곡강도2mmMaxR', fieldName: 'pfl굴곡강도2mmMaxR', width: '255', header: { text: 'PFL굴곡강도2mmMAXR' }, autoFilter: true },
		{ name: 'pfl접촉각배면Min', fieldName: 'pfl접촉각배면Min', width: '195', header: { text: 'PFL접촉각배면MIN' }, autoFilter: true },
		{ name: 'pfl접촉각배면기준', fieldName: 'pfl접촉각배면기준', width: '210', header: { text: 'PFL접촉각배면기준' }, autoFilter: true },
		{ name: 'pfl접촉각배면Max', fieldName: 'pfl접촉각배면Max', width: '195', header: { text: 'PFL접촉각배면MAX' }, autoFilter: true },
		{ name: 'pfl접촉각전면Min', fieldName: 'pfl접촉각전면Min', width: '195', header: { text: 'PFL접촉각전면MIN' }, autoFilter: true },
		{ name: 'pfl접촉각전면기준', fieldName: 'pfl접촉각전면기준', width: '210', header: { text: 'PFL접촉각전면기준' }, autoFilter: true },
		{ name: 'pfl접촉각전면Max', fieldName: 'pfl접촉각전면Max', width: '195', header: { text: 'PFL접촉각전면MAX' }, autoFilter: true },
		{ name: 'pflAlgin장변기준', fieldName: 'pflAlgin장변기준', width: '180', header: { text: 'PFLAlgin장변기준' }, autoFilter: true },
		{ name: 'pflAlgin장변편차', fieldName: 'pflAlgin장변편차', width: '180', header: { text: 'PFLAlgin장변편차' }, autoFilter: true },
		{ name: 'pflAlgin단변기준', fieldName: 'pflAlgin단변기준', width: '180', header: { text: 'PFLAlgin단변기준' }, autoFilter: true },
		{ name: 'pflAlgin단변편차', fieldName: 'pflAlgin단변편차', width: '180', header: { text: 'PFLAlgin단변편차' }, autoFilter: true },
		{ name: 'pflFilm전면자재코드', fieldName: 'pflFilm전면자재코드', width: '240', header: { text: 'PFLFILM전면자재코드' }, autoFilter: true },
		{ name: 'pflFilm전면PfVersion', fieldName: 'pflFilm전면PfVersion', width: '255', header: { text: 'PFLFILM전면PFVersion' }, autoFilter: true },
		{ name: 'pflFilm배면자재코드', fieldName: 'pflFilm배면자재코드', width: '240', header: { text: 'PFLFILM배면자재코드' }, autoFilter: true },
		{ name: 'pflFilm배면PfVersion', fieldName: 'pflFilm배면PfVersion', width: '255', header: { text: 'PFLFILM배면PFVersion' }, autoFilter: true },
		{ name: 'pflCurlSpec1차', fieldName: 'pflCurlSpec1차', width: '180', header: { text: 'PFLCURLSPEC1차' }, autoFilter: true },
		{ name: 'pflCurlSpec내부관리기준', fieldName: 'pflCurlSpec내부관리기준', width: '255', header: { text: 'PFLCURLSPEC내부관리기준' }, autoFilter: true },
		{ name: 'pflCurlSpec2차', fieldName: 'pflCurlSpec2차', width: '180', header: { text: 'PFLCURLSPEC2차' }, autoFilter: true },
		{ name: 'filmSize장변', fieldName: 'filmSize장변', width: '150', header: { text: 'FILMSIZE장변' }, autoFilter: true },
		{ name: 'filmSize단변', fieldName: 'filmSize단변', width: '150', header: { text: 'FILMSIZE단변' }, autoFilter: true },
		{ name: 'urg출하Size장변', fieldName: 'urg출하Size장변', width: '195', header: { text: 'URG출하SIZE장변' }, autoFilter: true },
		{ name: 'urg출하Size단변', fieldName: 'urg출하Size단변', width: '195', header: { text: 'URG출하SIZE단변' }, autoFilter: true },
		{ name: 'urg출하Size두께', fieldName: 'urg출하Size두께', width: '195', header: { text: 'URG출하SIZE두께' }, autoFilter: true },
		{ name: '변경점', fieldName: '변경점', width: '200', header: { text: '변경점' }, autoFilter: true }
	]	
}

module.exports = grid;